
@available(macOS 11.0, *)
let GCKeyA: String
@available(macOS 11.0, *)
let GCKeyB: String
@available(macOS 11.0, *)
let GCKeyC: String
@available(macOS 11.0, *)
let GCKeyD: String
@available(macOS 11.0, *)
let GCKeyE: String
@available(macOS 11.0, *)
let GCKeyF: String
@available(macOS 11.0, *)
let GCKeyG: String
@available(macOS 11.0, *)
let GCKeyH: String
@available(macOS 11.0, *)
let GCKeyI: String
@available(macOS 11.0, *)
let GCKeyJ: String
@available(macOS 11.0, *)
let GCKeyK: String
@available(macOS 11.0, *)
let GCKeyL: String
@available(macOS 11.0, *)
let GCKeyM: String
@available(macOS 11.0, *)
let GCKeyN: String
@available(macOS 11.0, *)
let GCKeyO: String
@available(macOS 11.0, *)
let GCKeyP: String
@available(macOS 11.0, *)
let GCKeyQ: String
@available(macOS 11.0, *)
let GCKeyR: String
@available(macOS 11.0, *)
let GCKeyS: String
@available(macOS 11.0, *)
let GCKeyT: String
@available(macOS 11.0, *)
let GCKeyU: String
@available(macOS 11.0, *)
let GCKeyV: String
@available(macOS 11.0, *)
let GCKeyW: String
@available(macOS 11.0, *)
let GCKeyX: String
@available(macOS 11.0, *)
let GCKeyY: String
@available(macOS 11.0, *)
let GCKeyZ: String
@available(macOS 11.0, *)
let GCKeyOne: String
@available(macOS 11.0, *)
let GCKeyTwo: String
@available(macOS 11.0, *)
let GCKeyThree: String
@available(macOS 11.0, *)
let GCKeyFour: String
@available(macOS 11.0, *)
let GCKeyFive: String
@available(macOS 11.0, *)
let GCKeySix: String
@available(macOS 11.0, *)
let GCKeySeven: String
@available(macOS 11.0, *)
let GCKeyEight: String
@available(macOS 11.0, *)
let GCKeyNine: String
@available(macOS 11.0, *)
let GCKeyZero: String
@available(macOS 11.0, *)
let GCKeyReturnOrEnter: String
@available(macOS 11.0, *)
let GCKeyEscape: String
@available(macOS 11.0, *)
let GCKeyDeleteOrBackspace: String
@available(macOS 11.0, *)
let GCKeyTab: String
@available(macOS 11.0, *)
let GCKeySpacebar: String
@available(macOS 11.0, *)
let GCKeyHyphen: String
@available(macOS 11.0, *)
let GCKeyEqualSign: String
@available(macOS 11.0, *)
let GCKeyOpenBracket: String
@available(macOS 11.0, *)
let GCKeyCloseBracket: String
@available(macOS 11.0, *)
let GCKeyBackslash: String
@available(macOS 11.0, *)
let GCKeyNonUSPound: String
@available(macOS 11.0, *)
let GCKeySemicolon: String
@available(macOS 11.0, *)
let GCKeyQuote: String
@available(macOS 11.0, *)
let GCKeyGraveAccentAndTilde: String
@available(macOS 11.0, *)
let GCKeyComma: String
@available(macOS 11.0, *)
let GCKeyPeriod: String
@available(macOS 11.0, *)
let GCKeySlash: String
@available(macOS 11.0, *)
let GCKeyCapsLock: String
@available(macOS 11.0, *)
let GCKeyF1: String
@available(macOS 11.0, *)
let GCKeyF2: String
@available(macOS 11.0, *)
let GCKeyF3: String
@available(macOS 11.0, *)
let GCKeyF4: String
@available(macOS 11.0, *)
let GCKeyF5: String
@available(macOS 11.0, *)
let GCKeyF6: String
@available(macOS 11.0, *)
let GCKeyF7: String
@available(macOS 11.0, *)
let GCKeyF8: String
@available(macOS 11.0, *)
let GCKeyF9: String
@available(macOS 11.0, *)
let GCKeyF10: String
@available(macOS 11.0, *)
let GCKeyF11: String
@available(macOS 11.0, *)
let GCKeyF12: String
@available(macOS 11.0, *)
let GCKeyPrintScreen: String
@available(macOS 11.0, *)
let GCKeyScrollLock: String
@available(macOS 11.0, *)
let GCKeyPause: String
@available(macOS 11.0, *)
let GCKeyInsert: String
@available(macOS 11.0, *)
let GCKeyHome: String
@available(macOS 11.0, *)
let GCKeyPageUp: String
@available(macOS 11.0, *)
let GCKeyDeleteForward: String
@available(macOS 11.0, *)
let GCKeyEnd: String
@available(macOS 11.0, *)
let GCKeyPageDown: String
@available(macOS 11.0, *)
let GCKeyRightArrow: String
@available(macOS 11.0, *)
let GCKeyLeftArrow: String
@available(macOS 11.0, *)
let GCKeyDownArrow: String
@available(macOS 11.0, *)
let GCKeyUpArrow: String
@available(macOS 11.0, *)
let GCKeyKeypadNumLock: String
@available(macOS 11.0, *)
let GCKeyKeypadSlash: String
@available(macOS 11.0, *)
let GCKeyKeypadAsterisk: String
@available(macOS 11.0, *)
let GCKeyKeypadHyphen: String
@available(macOS 11.0, *)
let GCKeyKeypadPlus: String
@available(macOS 11.0, *)
let GCKeyKeypadEnter: String
@available(macOS 11.0, *)
let GCKeyKeypad1: String
@available(macOS 11.0, *)
let GCKeyKeypad2: String
@available(macOS 11.0, *)
let GCKeyKeypad3: String
@available(macOS 11.0, *)
let GCKeyKeypad4: String
@available(macOS 11.0, *)
let GCKeyKeypad5: String
@available(macOS 11.0, *)
let GCKeyKeypad6: String
@available(macOS 11.0, *)
let GCKeyKeypad7: String
@available(macOS 11.0, *)
let GCKeyKeypad8: String
@available(macOS 11.0, *)
let GCKeyKeypad9: String
@available(macOS 11.0, *)
let GCKeyKeypad0: String
@available(macOS 11.0, *)
let GCKeyKeypadPeriod: String
@available(macOS 11.0, *)
let GCKeyKeypadEqualSign: String
@available(macOS 11.0, *)
let GCKeyNonUSBackslash: String
@available(macOS 11.0, *)
let GCKeyApplication: String
@available(macOS 11.0, *)
let GCKeyPower: String
@available(macOS 11.0, *)
let GCKeyInternational1: String
@available(macOS 11.0, *)
let GCKeyInternational2: String
@available(macOS 11.0, *)
let GCKeyInternational3: String
@available(macOS 11.0, *)
let GCKeyInternational4: String
@available(macOS 11.0, *)
let GCKeyInternational5: String
@available(macOS 11.0, *)
let GCKeyInternational6: String
@available(macOS 11.0, *)
let GCKeyInternational7: String
@available(macOS 11.0, *)
let GCKeyInternational8: String
@available(macOS 11.0, *)
let GCKeyInternational9: String
@available(macOS 11.0, *)
let GCKeyLANG1: String
@available(macOS 11.0, *)
let GCKeyLANG2: String
@available(macOS 11.0, *)
let GCKeyLANG3: String
@available(macOS 11.0, *)
let GCKeyLANG4: String
@available(macOS 11.0, *)
let GCKeyLANG5: String
@available(macOS 11.0, *)
let GCKeyLANG6: String
@available(macOS 11.0, *)
let GCKeyLANG7: String
@available(macOS 11.0, *)
let GCKeyLANG8: String
@available(macOS 11.0, *)
let GCKeyLANG9: String
@available(macOS 11.0, *)
let GCKeyLeftControl: String
@available(macOS 11.0, *)
let GCKeyLeftShift: String
@available(macOS 11.0, *)
let GCKeyLeftAlt: String
@available(macOS 11.0, *)
let GCKeyLeftGUI: String
@available(macOS 11.0, *)
let GCKeyRightControl: String
@available(macOS 11.0, *)
let GCKeyRightShift: String
@available(macOS 11.0, *)
let GCKeyRightAlt: String
@available(macOS 11.0, *)
let GCKeyRightGUI: String
