
@available(macOS 10.11, *)
class CNContactRelation : NSObject, NSCopying, NSSecureCoding {
  init(name: String)
  var name: String { get }
}
@available(macOS 10.11, *)
let CNLabelContactRelationAssistant: String
@available(macOS 10.11, *)
let CNLabelContactRelationManager: String
@available(macOS 10.15, *)
let CNLabelContactRelationColleague: String
@available(macOS 10.15, *)
let CNLabelContactRelationTeacher: String
@available(macOS 10.15, *)
let CNLabelContactRelationSibling: String
@available(macOS 10.15, *)
let CNLabelContactRelationYoungerSibling: String
@available(macOS 10.15, *)
let CNLabelContactRelationElderSibling: String
@available(macOS 10.11, *)
let CNLabelContactRelationSister: String
@available(macOS 10.15, *)
let CNLabelContactRelationYoungerSister: String
@available(macOS 10.15, *)
let CNLabelContactRelationYoungestSister: String
@available(macOS 10.15, *)
let CNLabelContactRelationElderSister: String
@available(macOS 10.15, *)
let CNLabelContactRelationEldestSister: String
@available(macOS 10.11, *)
let CNLabelContactRelationBrother: String
@available(macOS 10.15, *)
let CNLabelContactRelationYoungerBrother: String
@available(macOS 10.15, *)
let CNLabelContactRelationYoungestBrother: String
@available(macOS 10.15, *)
let CNLabelContactRelationElderBrother: String
@available(macOS 10.15, *)
let CNLabelContactRelationEldestBrother: String
@available(macOS 10.11, *)
let CNLabelContactRelationFriend: String
@available(macOS 10.15, *)
let CNLabelContactRelationMaleFriend: String
@available(macOS 10.15, *)
let CNLabelContactRelationFemaleFriend: String
@available(macOS 10.11, *)
let CNLabelContactRelationSpouse: String
@available(macOS 10.15, *)
let CNLabelContactRelationWife: String
@available(macOS 10.15, *)
let CNLabelContactRelationHusband: String
@available(macOS 10.11, *)
let CNLabelContactRelationPartner: String
@available(macOS 10.15, *)
let CNLabelContactRelationMalePartner: String
@available(macOS 10.15, *)
let CNLabelContactRelationFemalePartner: String
@available(macOS 10.15, *)
let CNLabelContactRelationGirlfriendOrBoyfriend: String
@available(macOS 10.15, *)
let CNLabelContactRelationGirlfriend: String
@available(macOS 10.15, *)
let CNLabelContactRelationBoyfriend: String
@available(macOS 10.11, *)
let CNLabelContactRelationParent: String
@available(macOS 10.11, *)
let CNLabelContactRelationMother: String
@available(macOS 10.11, *)
let CNLabelContactRelationFather: String
@available(macOS 10.11, *)
let CNLabelContactRelationChild: String
@available(macOS 10.13, *)
let CNLabelContactRelationDaughter: String
@available(macOS 10.13, *)
let CNLabelContactRelationSon: String
@available(macOS 10.15, *)
let CNLabelContactRelationGrandparent: String
@available(macOS 10.15, *)
let CNLabelContactRelationGrandmother: String
@available(macOS 10.15, *)
let CNLabelContactRelationGrandmotherMothersMother: String
@available(macOS 10.15, *)
let CNLabelContactRelationGrandmotherFathersMother: String
@available(macOS 10.15, *)
let CNLabelContactRelationGrandfather: String
@available(macOS 10.15, *)
let CNLabelContactRelationGrandfatherMothersFather: String
@available(macOS 10.15, *)
let CNLabelContactRelationGrandfatherFathersFather: String
@available(macOS 10.15, *)
let CNLabelContactRelationGreatGrandparent: String
@available(macOS 10.15, *)
let CNLabelContactRelationGreatGrandmother: String
@available(macOS 10.15, *)
let CNLabelContactRelationGreatGrandfather: String
@available(macOS 10.15, *)
let CNLabelContactRelationGrandchild: String
@available(macOS 10.15, *)
let CNLabelContactRelationGranddaughter: String
@available(macOS 10.15, *)
let CNLabelContactRelationGranddaughterDaughtersDaughter: String
@available(macOS 10.15, *)
let CNLabelContactRelationGranddaughterSonsDaughter: String
@available(macOS 10.15, *)
let CNLabelContactRelationGrandson: String
@available(macOS 10.15, *)
let CNLabelContactRelationGrandsonDaughtersSon: String
@available(macOS 10.15, *)
let CNLabelContactRelationGrandsonSonsSon: String
@available(macOS 10.15, *)
let CNLabelContactRelationGreatGrandchild: String
@available(macOS 10.15, *)
let CNLabelContactRelationGreatGranddaughter: String
@available(macOS 10.15, *)
let CNLabelContactRelationGreatGrandson: String
@available(macOS 10.15, *)
let CNLabelContactRelationParentInLaw: String
@available(macOS 10.15, *)
let CNLabelContactRelationMotherInLaw: String
@available(macOS 10.15, *)
let CNLabelContactRelationMotherInLawWifesMother: String
@available(macOS 10.15, *)
let CNLabelContactRelationMotherInLawHusbandsMother: String
@available(macOS 10.15, *)
let CNLabelContactRelationFatherInLaw: String
@available(macOS 10.15, *)
let CNLabelContactRelationFatherInLawWifesFather: String
@available(macOS 10.15, *)
let CNLabelContactRelationFatherInLawHusbandsFather: String
@available(macOS 10.15, *)
let CNLabelContactRelationCoParentInLaw: String
@available(macOS 10.15, *)
let CNLabelContactRelationCoMotherInLaw: String
@available(macOS 10.15, *)
let CNLabelContactRelationCoFatherInLaw: String
@available(macOS 10.15, *)
let CNLabelContactRelationSiblingInLaw: String
@available(macOS 10.15, *)
let CNLabelContactRelationYoungerSiblingInLaw: String
@available(macOS 10.15, *)
let CNLabelContactRelationElderSiblingInLaw: String
@available(macOS 10.15, *)
let CNLabelContactRelationSisterInLaw: String
@available(macOS 10.15, *)
let CNLabelContactRelationYoungerSisterInLaw: String
@available(macOS 10.15, *)
let CNLabelContactRelationElderSisterInLaw: String
@available(macOS 10.15, *)
let CNLabelContactRelationSisterInLawSpousesSister: String
@available(macOS 10.15, *)
let CNLabelContactRelationSisterInLawWifesSister: String
@available(macOS 10.15, *)
let CNLabelContactRelationSisterInLawHusbandsSister: String
@available(macOS 10.15, *)
let CNLabelContactRelationSisterInLawBrothersWife: String
@available(macOS 10.15, *)
let CNLabelContactRelationSisterInLawYoungerBrothersWife: String
@available(macOS 10.15, *)
let CNLabelContactRelationSisterInLawElderBrothersWife: String
@available(macOS 10.15, *)
let CNLabelContactRelationBrotherInLaw: String
@available(macOS 10.15, *)
let CNLabelContactRelationYoungerBrotherInLaw: String
@available(macOS 10.15, *)
let CNLabelContactRelationElderBrotherInLaw: String
@available(macOS 10.15, *)
let CNLabelContactRelationBrotherInLawSpousesBrother: String
@available(macOS 10.15, *)
let CNLabelContactRelationBrotherInLawHusbandsBrother: String
@available(macOS 10.15, *)
let CNLabelContactRelationBrotherInLawWifesBrother: String
@available(macOS 10.15, *)
let CNLabelContactRelationBrotherInLawSistersHusband: String
@available(macOS 10.15, *)
let CNLabelContactRelationBrotherInLawYoungerSistersHusband: String
@available(macOS 10.15, *)
let CNLabelContactRelationBrotherInLawElderSistersHusband: String
@available(macOS 10.15, *)
let CNLabelContactRelationSisterInLawWifesBrothersWife: String
@available(macOS 10.15, *)
let CNLabelContactRelationSisterInLawHusbandsBrothersWife: String
@available(macOS 10.15, *)
let CNLabelContactRelationBrotherInLawWifesSistersHusband: String
@available(macOS 10.15, *)
let CNLabelContactRelationBrotherInLawHusbandsSistersHusband: String
@available(macOS 10.15, *)
let CNLabelContactRelationCoSiblingInLaw: String
@available(macOS 10.15, *)
let CNLabelContactRelationCoSisterInLaw: String
@available(macOS 10.15, *)
let CNLabelContactRelationCoBrotherInLaw: String
@available(macOS 10.15, *)
let CNLabelContactRelationChildInLaw: String
@available(macOS 10.15, *)
let CNLabelContactRelationDaughterInLaw: String
@available(macOS 10.15, *)
let CNLabelContactRelationSonInLaw: String
@available(macOS 10.15, *)
let CNLabelContactRelationCousin: String
@available(macOS 10.15, *)
let CNLabelContactRelationYoungerCousin: String
@available(macOS 10.15, *)
let CNLabelContactRelationElderCousin: String
@available(macOS 10.15, *)
let CNLabelContactRelationMaleCousin: String
@available(macOS 10.15, *)
let CNLabelContactRelationFemaleCousin: String
@available(macOS 10.15, *)
let CNLabelContactRelationCousinParentsSiblingsChild: String
@available(macOS 10.15, *)
let CNLabelContactRelationCousinParentsSiblingsSon: String
@available(macOS 10.15, *)
let CNLabelContactRelationYoungerCousinParentsSiblingsSon: String
@available(macOS 10.15, *)
let CNLabelContactRelationElderCousinParentsSiblingsSon: String
@available(macOS 10.15, *)
let CNLabelContactRelationCousinParentsSiblingsDaughter: String
@available(macOS 10.15, *)
let CNLabelContactRelationYoungerCousinParentsSiblingsDaughter: String
@available(macOS 10.15, *)
let CNLabelContactRelationElderCousinParentsSiblingsDaughter: String
@available(macOS 10.15, *)
let CNLabelContactRelationCousinMothersSistersDaughter: String
@available(macOS 10.15, *)
let CNLabelContactRelationYoungerCousinMothersSistersDaughter: String
@available(macOS 10.15, *)
let CNLabelContactRelationElderCousinMothersSistersDaughter: String
@available(macOS 10.15, *)
let CNLabelContactRelationCousinMothersSistersSon: String
@available(macOS 10.15, *)
let CNLabelContactRelationYoungerCousinMothersSistersSon: String
@available(macOS 10.15, *)
let CNLabelContactRelationElderCousinMothersSistersSon: String
@available(macOS 10.15, *)
let CNLabelContactRelationCousinMothersBrothersDaughter: String
@available(macOS 10.15, *)
let CNLabelContactRelationYoungerCousinMothersBrothersDaughter: String
@available(macOS 10.15, *)
let CNLabelContactRelationElderCousinMothersBrothersDaughter: String
@available(macOS 10.15, *)
let CNLabelContactRelationCousinMothersBrothersSon: String
@available(macOS 10.15, *)
let CNLabelContactRelationYoungerCousinMothersBrothersSon: String
@available(macOS 10.15, *)
let CNLabelContactRelationElderCousinMothersBrothersSon: String
@available(macOS 10.15, *)
let CNLabelContactRelationCousinFathersSistersDaughter: String
@available(macOS 10.15, *)
let CNLabelContactRelationYoungerCousinFathersSistersDaughter: String
@available(macOS 10.15, *)
let CNLabelContactRelationElderCousinFathersSistersDaughter: String
@available(macOS 10.15, *)
let CNLabelContactRelationCousinFathersSistersSon: String
@available(macOS 10.15, *)
let CNLabelContactRelationYoungerCousinFathersSistersSon: String
@available(macOS 10.15, *)
let CNLabelContactRelationElderCousinFathersSistersSon: String
@available(macOS 10.15, *)
let CNLabelContactRelationCousinFathersBrothersDaughter: String
@available(macOS 10.15, *)
let CNLabelContactRelationYoungerCousinFathersBrothersDaughter: String
@available(macOS 10.15, *)
let CNLabelContactRelationElderCousinFathersBrothersDaughter: String
@available(macOS 10.15, *)
let CNLabelContactRelationCousinFathersBrothersSon: String
@available(macOS 10.15, *)
let CNLabelContactRelationYoungerCousinFathersBrothersSon: String
@available(macOS 10.15, *)
let CNLabelContactRelationElderCousinFathersBrothersSon: String
@available(macOS 10.15, *)
let CNLabelContactRelationCousinGrandparentsSiblingsChild: String
@available(macOS 10.15, *)
let CNLabelContactRelationCousinGrandparentsSiblingsDaughter: String
@available(macOS 10.15, *)
let CNLabelContactRelationCousinGrandparentsSiblingsSon: String
@available(macOS 10.15, *)
let CNLabelContactRelationYoungerCousinMothersSiblingsSonOrFathersSistersSon: String
@available(macOS 10.15, *)
let CNLabelContactRelationElderCousinMothersSiblingsSonOrFathersSistersSon: String
@available(macOS 10.15, *)
let CNLabelContactRelationYoungerCousinMothersSiblingsDaughterOrFathersSistersDaughter: String
@available(macOS 10.15, *)
let CNLabelContactRelationElderCousinMothersSiblingsDaughterOrFathersSistersDaughter: String
@available(macOS 10.15, *)
let CNLabelContactRelationParentsSibling: String
@available(macOS 10.15, *)
let CNLabelContactRelationParentsYoungerSibling: String
@available(macOS 10.15, *)
let CNLabelContactRelationParentsElderSibling: String
@available(macOS 10.15, *)
let CNLabelContactRelationParentsSiblingMothersSibling: String
@available(macOS 10.15, *)
let CNLabelContactRelationParentsSiblingMothersYoungerSibling: String
@available(macOS 10.15, *)
let CNLabelContactRelationParentsSiblingMothersElderSibling: String
@available(macOS 10.15, *)
let CNLabelContactRelationParentsSiblingFathersSibling: String
@available(macOS 10.15, *)
let CNLabelContactRelationParentsSiblingFathersYoungerSibling: String
@available(macOS 10.15, *)
let CNLabelContactRelationParentsSiblingFathersElderSibling: String
@available(macOS 10.15, *)
let CNLabelContactRelationAunt: String
@available(macOS 10.15, *)
let CNLabelContactRelationAuntParentsSister: String
@available(macOS 10.15, *)
let CNLabelContactRelationAuntParentsYoungerSister: String
@available(macOS 10.15, *)
let CNLabelContactRelationAuntParentsElderSister: String
@available(macOS 10.15, *)
let CNLabelContactRelationAuntFathersSister: String
@available(macOS 10.15, *)
let CNLabelContactRelationAuntFathersYoungerSister: String
@available(macOS 10.15, *)
let CNLabelContactRelationAuntFathersElderSister: String
@available(macOS 10.15, *)
let CNLabelContactRelationAuntFathersBrothersWife: String
@available(macOS 10.15, *)
let CNLabelContactRelationAuntFathersYoungerBrothersWife: String
@available(macOS 10.15, *)
let CNLabelContactRelationAuntFathersElderBrothersWife: String
@available(macOS 10.15, *)
let CNLabelContactRelationAuntMothersSister: String
@available(macOS 10.15, *)
let CNLabelContactRelationAuntMothersYoungerSister: String
@available(macOS 10.15, *)
let CNLabelContactRelationAuntMothersElderSister: String
@available(macOS 10.15, *)
let CNLabelContactRelationAuntMothersBrothersWife: String
@available(macOS 10.15, *)
let CNLabelContactRelationGrandaunt: String
@available(macOS 10.15, *)
let CNLabelContactRelationUncle: String
@available(macOS 10.15, *)
let CNLabelContactRelationUncleParentsBrother: String
@available(macOS 10.15, *)
let CNLabelContactRelationUncleParentsYoungerBrother: String
@available(macOS 10.15, *)
let CNLabelContactRelationUncleParentsElderBrother: String
@available(macOS 10.15, *)
let CNLabelContactRelationUncleMothersBrother: String
@available(macOS 10.15, *)
let CNLabelContactRelationUncleMothersYoungerBrother: String
@available(macOS 10.15, *)
let CNLabelContactRelationUncleMothersElderBrother: String
@available(macOS 10.15, *)
let CNLabelContactRelationUncleMothersSistersHusband: String
@available(macOS 10.15, *)
let CNLabelContactRelationUncleFathersBrother: String
@available(macOS 10.15, *)
let CNLabelContactRelationUncleFathersYoungerBrother: String
@available(macOS 10.15, *)
let CNLabelContactRelationUncleFathersElderBrother: String
@available(macOS 10.15, *)
let CNLabelContactRelationUncleFathersSistersHusband: String
@available(macOS 10.15, *)
let CNLabelContactRelationUncleFathersYoungerSistersHusband: String
@available(macOS 10.15, *)
let CNLabelContactRelationUncleFathersElderSistersHusband: String
@available(macOS 10.15, *)
let CNLabelContactRelationGranduncle: String
@available(macOS 10.15, *)
let CNLabelContactRelationSiblingsChild: String
@available(macOS 10.15, *)
let CNLabelContactRelationNiece: String
@available(macOS 10.15, *)
let CNLabelContactRelationNieceSistersDaughter: String
@available(macOS 10.15, *)
let CNLabelContactRelationNieceBrothersDaughter: String
@available(macOS 10.15, *)
let CNLabelContactRelationNieceSistersDaughterOrWifesSiblingsDaughter: String
@available(macOS 10.15, *)
let CNLabelContactRelationNieceBrothersDaughterOrHusbandsSiblingsDaughter: String
@available(macOS 10.15, *)
let CNLabelContactRelationNephew: String
@available(macOS 10.15, *)
let CNLabelContactRelationNephewSistersSon: String
@available(macOS 10.15, *)
let CNLabelContactRelationNephewBrothersSon: String
@available(macOS 10.15, *)
let CNLabelContactRelationNephewBrothersSonOrHusbandsSiblingsSon: String
@available(macOS 10.15, *)
let CNLabelContactRelationNephewSistersSonOrWifesSiblingsSon: String
@available(macOS 10.15, *)
let CNLabelContactRelationGrandniece: String
@available(macOS 10.15, *)
let CNLabelContactRelationGrandnieceSistersGranddaughter: String
@available(macOS 10.15, *)
let CNLabelContactRelationGrandnieceBrothersGranddaughter: String
@available(macOS 10.15, *)
let CNLabelContactRelationGrandnephew: String
@available(macOS 10.15, *)
let CNLabelContactRelationGrandnephewSistersGrandson: String
@available(macOS 10.15, *)
let CNLabelContactRelationGrandnephewBrothersGrandson: String
@available(macOS 10.15, *)
let CNLabelContactRelationStepparent: String
@available(macOS 10.15, *)
let CNLabelContactRelationStepmother: String
@available(macOS 10.15, *)
let CNLabelContactRelationStepfather: String
@available(macOS 10.15, *)
let CNLabelContactRelationStepchild: String
@available(macOS 10.15, *)
let CNLabelContactRelationStepdaughter: String
@available(macOS 10.15, *)
let CNLabelContactRelationStepson: String
@available(macOS 10.15, *)
let CNLabelContactRelationStepsister: String
@available(macOS 10.15, *)
let CNLabelContactRelationStepbrother: String
@available(macOS 10.15, *)
let CNLabelContactRelationMotherInLawOrStepmother: String
@available(macOS 10.15, *)
let CNLabelContactRelationFatherInLawOrStepfather: String
@available(macOS 10.15, *)
let CNLabelContactRelationDaughterInLawOrStepdaughter: String
@available(macOS 10.15, *)
let CNLabelContactRelationSonInLawOrStepson: String
@available(macOS 10.15, *)
let CNLabelContactRelationCousinOrSiblingsChild: String
@available(macOS 10.15, *)
let CNLabelContactRelationNieceOrCousin: String
@available(macOS 10.15, *)
let CNLabelContactRelationNephewOrCousin: String
@available(macOS 10.15, *)
let CNLabelContactRelationGrandchildOrSiblingsChild: String
@available(macOS 11.0, *)
let CNLabelContactRelationGranddaughterOrNiece: String
@available(macOS 11.0, *)
let CNLabelContactRelationGrandsonOrNephew: String
@available(macOS 10.15, *)
let CNLabelContactRelationGreatGrandchildOrSiblingsGrandchild: String
@available(macOS 10.15, *)
let CNLabelContactRelationDaughterInLawOrSisterInLaw: String
@available(macOS 10.15, *)
let CNLabelContactRelationSonInLawOrBrotherInLaw: String
