
@available(macOS 11.0, *)
let __UTTypeItem: UTTypeReference
@available(macOS 11.0, *)
let __UTTypeContent: UTTypeReference
@available(macOS 11.0, *)
let __UTTypeCompositeContent: UTTypeReference
@available(macOS 11.0, *)
let __UTTypeDiskImage: UTTypeReference
@available(macOS 11.0, *)
let __UTTypeData: UTTypeReference
@available(macOS 11.0, *)
let __UTTypeDirectory: UTTypeReference
@available(macOS 11.0, *)
let __UTTypeResolvable: UTTypeReference
@available(macOS 11.0, *)
let __UTTypeSymbolicLink: UTTypeReference
@available(macOS 11.0, *)
let __UTTypeExecutable: UTTypeReference
@available(macOS 11.0, *)
let __UTTypeMountPoint: UTTypeReference
@available(macOS 11.0, *)
let __UTTypeAliasFile: UTTypeReference
@available(macOS 11.0, *)
let __UTTypeURLBookmarkData: UTTypeReference
@available(macOS 11.0, *)
let __UTTypeURL: UTTypeReference
@available(macOS 11.0, *)
let __UTTypeFileURL: UTTypeReference
@available(macOS 11.0, *)
let __UTTypeText: UTTypeReference
@available(macOS 11.0, *)
let __UTTypePlainText: UTTypeReference
@available(macOS 11.0, *)
let __UTTypeUTF8PlainText: UTTypeReference
@available(macOS 11.0, *)
let __UTTypeUTF16ExternalPlainText: UTTypeReference
@available(macOS 11.0, *)
let __UTTypeUTF16PlainText: UTTypeReference
@available(macOS 11.0, *)
let __UTTypeDelimitedText: UTTypeReference
@available(macOS 11.0, *)
let __UTTypeCommaSeparatedText: UTTypeReference
@available(macOS 11.0, *)
let __UTTypeTabSeparatedText: UTTypeReference
@available(macOS 11.0, *)
let __UTTypeUTF8TabSeparatedText: UTTypeReference
@available(macOS 11.0, *)
let __UTTypeRTF: UTTypeReference
@available(macOS 11.0, *)
let __UTTypeHTML: UTTypeReference
@available(macOS 11.0, *)
let __UTTypeXML: UTTypeReference
@available(macOS 11.0, *)
let __UTTypeYAML: UTTypeReference
@available(macOS 11.0, *)
let __UTTypeSourceCode: UTTypeReference
@available(macOS 11.0, *)
let __UTTypeAssemblyLanguageSource: UTTypeReference
@available(macOS 11.0, *)
let __UTTypeCSource: UTTypeReference
@available(macOS 11.0, *)
let __UTTypeObjectiveCSource: UTTypeReference
@available(macOS 11.0, *)
let __UTTypeSwiftSource: UTTypeReference
@available(macOS 11.0, *)
let __UTTypeCPlusPlusSource: UTTypeReference
@available(macOS 11.0, *)
let __UTTypeObjectiveCPlusPlusSource: UTTypeReference
@available(macOS 11.0, *)
let __UTTypeCHeader: UTTypeReference
@available(macOS 11.0, *)
let __UTTypeCPlusPlusHeader: UTTypeReference
@available(macOS 11.0, *)
let __UTTypeScript: UTTypeReference
@available(macOS 11.0, *)
let __UTTypeAppleScript: UTTypeReference
@available(macOS 11.0, *)
let __UTTypeOSAScript: UTTypeReference
@available(macOS 11.0, *)
let __UTTypeOSAScriptBundle: UTTypeReference
@available(macOS 11.0, *)
let __UTTypeJavaScript: UTTypeReference
@available(macOS 11.0, *)
let __UTTypeShellScript: UTTypeReference
@available(macOS 11.0, *)
let __UTTypePerlScript: UTTypeReference
@available(macOS 11.0, *)
let __UTTypePythonScript: UTTypeReference
@available(macOS 11.0, *)
let __UTTypeRubyScript: UTTypeReference
@available(macOS 11.0, *)
let __UTTypePHPScript: UTTypeReference
@available(macOS 11.0, *)
let __UTTypeJSON: UTTypeReference
@available(macOS 11.0, *)
let __UTTypePropertyList: UTTypeReference
@available(macOS 11.0, *)
let __UTTypeXMLPropertyList: UTTypeReference
@available(macOS 11.0, *)
let __UTTypeBinaryPropertyList: UTTypeReference
@available(macOS 11.0, *)
let __UTTypePDF: UTTypeReference
@available(macOS 11.0, *)
let __UTTypeRTFD: UTTypeReference
@available(macOS 11.0, *)
let __UTTypeFlatRTFD: UTTypeReference
@available(macOS 11.0, *)
let __UTTypeWebArchive: UTTypeReference
@available(macOS 11.0, *)
let __UTTypeImage: UTTypeReference
@available(macOS 11.0, *)
let __UTTypeJPEG: UTTypeReference
@available(macOS 11.0, *)
let __UTTypeTIFF: UTTypeReference
@available(macOS 11.0, *)
let __UTTypeGIF: UTTypeReference
@available(macOS 11.0, *)
let __UTTypePNG: UTTypeReference
@available(macOS 11.0, *)
let __UTTypeICNS: UTTypeReference
@available(macOS 11.0, *)
let __UTTypeBMP: UTTypeReference
@available(macOS 11.0, *)
let __UTTypeICO: UTTypeReference
@available(macOS 11.0, *)
let __UTTypeRAWImage: UTTypeReference
@available(macOS 11.0, *)
let __UTTypeSVG: UTTypeReference
@available(macOS 11.0, *)
let __UTTypeLivePhoto: UTTypeReference
@available(macOS 11.0, *)
let __UTTypeHEIF: UTTypeReference
@available(macOS 11.0, *)
let __UTTypeHEIC: UTTypeReference
@available(macOS 11.0, *)
let __UTTypeWebP: UTTypeReference
@available(macOS 11.0, *)
let __UTType3DContent: UTTypeReference
@available(macOS 11.0, *)
let __UTTypeUSD: UTTypeReference
@available(macOS 11.0, *)
let __UTTypeUSDZ: UTTypeReference
@available(macOS 11.0, *)
let __UTTypeRealityFile: UTTypeReference
@available(macOS 11.0, *)
let __UTTypeSceneKitScene: UTTypeReference
@available(macOS 11.0, *)
let __UTTypeARReferenceObject: UTTypeReference
@available(macOS 11.0, *)
let __UTTypeAudiovisualContent: UTTypeReference
@available(macOS 11.0, *)
let __UTTypeMovie: UTTypeReference
@available(macOS 11.0, *)
let __UTTypeVideo: UTTypeReference
@available(macOS 11.0, *)
let __UTTypeAudio: UTTypeReference
@available(macOS 11.0, *)
let __UTTypeQuickTimeMovie: UTTypeReference
@available(macOS 11.0, *)
let __UTTypeMPEG: UTTypeReference
@available(macOS 11.0, *)
let __UTTypeMPEG2Video: UTTypeReference
@available(macOS 11.0, *)
let __UTTypeMPEG2TransportStream: UTTypeReference
@available(macOS 11.0, *)
let __UTTypeMP3: UTTypeReference
@available(macOS 11.0, *)
let __UTTypeMPEG4Movie: UTTypeReference
@available(macOS 11.0, *)
let __UTTypeMPEG4Audio: UTTypeReference
@available(macOS 11.0, *)
let __UTTypeAppleProtectedMPEG4Audio: UTTypeReference
@available(macOS 11.0, *)
let __UTTypeAppleProtectedMPEG4Video: UTTypeReference
@available(macOS 11.0, *)
let __UTTypeAVI: UTTypeReference
@available(macOS 11.0, *)
let __UTTypeAIFF: UTTypeReference
@available(macOS 11.0, *)
let __UTTypeWAV: UTTypeReference
@available(macOS 11.0, *)
let __UTTypeMIDI: UTTypeReference
@available(macOS 11.0, *)
let __UTTypePlaylist: UTTypeReference
@available(macOS 11.0, *)
let __UTTypeM3UPlaylist: UTTypeReference
@available(macOS 11.0, *)
let __UTTypeFolder: UTTypeReference
@available(macOS 11.0, *)
let __UTTypeVolume: UTTypeReference
@available(macOS 11.0, *)
let __UTTypePackage: UTTypeReference
@available(macOS 11.0, *)
let __UTTypeBundle: UTTypeReference
@available(macOS 11.0, *)
let __UTTypePluginBundle: UTTypeReference
@available(macOS 11.0, *)
let __UTTypeSpotlightImporter: UTTypeReference
@available(macOS 11.0, *)
let __UTTypeQuickLookGenerator: UTTypeReference
@available(macOS 11.0, *)
let __UTTypeXPCService: UTTypeReference
@available(macOS 11.0, *)
let __UTTypeFramework: UTTypeReference
@available(macOS 11.0, *)
let __UTTypeApplication: UTTypeReference
@available(macOS 11.0, *)
let __UTTypeApplicationBundle: UTTypeReference
@available(macOS 11.0, *)
let __UTTypeApplicationExtension: UTTypeReference
@available(macOS 11.0, *)
let __UTTypeUnixExecutable: UTTypeReference
@available(macOS 11.0, *)
let __UTTypeEXE: UTTypeReference
@available(macOS 11.0, *)
let __UTTypeSystemPreferencesPane: UTTypeReference
@available(macOS 11.0, *)
let __UTTypeArchive: UTTypeReference
@available(macOS 11.0, *)
let __UTTypeGZIP: UTTypeReference
@available(macOS 11.0, *)
let __UTTypeBZ2: UTTypeReference
@available(macOS 11.0, *)
let __UTTypeZIP: UTTypeReference
@available(macOS 11.0, *)
let __UTTypeAppleArchive: UTTypeReference
@available(macOS 11.0, *)
let __UTTypeSpreadsheet: UTTypeReference
@available(macOS 11.0, *)
let __UTTypePresentation: UTTypeReference
@available(macOS 11.0, *)
let __UTTypeDatabase: UTTypeReference
@available(macOS 11.0, *)
let __UTTypeMessage: UTTypeReference
@available(macOS 11.0, *)
let __UTTypeContact: UTTypeReference
@available(macOS 11.0, *)
let __UTTypeVCard: UTTypeReference
@available(macOS 11.0, *)
let __UTTypeToDoItem: UTTypeReference
@available(macOS 11.0, *)
let __UTTypeCalendarEvent: UTTypeReference
@available(macOS 11.0, *)
let __UTTypeEmailMessage: UTTypeReference
@available(macOS 11.0, *)
let __UTTypeInternetLocation: UTTypeReference
@available(macOS 11.0, *)
let __UTTypeInternetShortcut: UTTypeReference
@available(macOS 11.0, *)
let __UTTypeFont: UTTypeReference
@available(macOS 11.0, *)
let __UTTypeBookmark: UTTypeReference
@available(macOS 11.0, *)
let __UTTypePKCS12: UTTypeReference
@available(macOS 11.0, *)
let __UTTypeX509Certificate: UTTypeReference
@available(macOS 11.0, *)
let __UTTypeEPUB: UTTypeReference
@available(macOS 11.0, *)
let __UTTypeLog: UTTypeReference
