
@available(watchOS 2.0, *)
let HMAccessoryCategoryTypeOther: String
@available(watchOS 2.0, *)
let HMAccessoryCategoryTypeSecuritySystem: String
@available(watchOS 2.0, *)
let HMAccessoryCategoryTypeBridge: String
@available(watchOS 2.0, *)
let HMAccessoryCategoryTypeDoor: String
@available(watchOS 2.0, *)
let HMAccessoryCategoryTypeDoorLock: String
@available(watchOS 2.0, *)
let HMAccessoryCategoryTypeFan: String
@available(watchOS 2.0, *)
let HMAccessoryCategoryTypeGarageDoorOpener: String
@available(watchOS 3.0, *)
let HMAccessoryCategoryTypeIPCamera: String
@available(watchOS 2.0, *)
let HMAccessoryCategoryTypeLightbulb: String
@available(watchOS 2.0, *)
let HMAccessoryCategoryTypeOutlet: String
@available(watchOS 2.0, *)
let HMAccessoryCategoryTypeProgrammableSwitch: String
@available(watchOS 2.2, *)
let HMAccessoryCategoryTypeRangeExtender: String
@available(watchOS 2.0, *)
let HMAccessoryCategoryTypeSensor: String
@available(watchOS 2.0, *)
let HMAccessoryCategoryTypeSwitch: String
@available(watchOS 2.0, *)
let HMAccessoryCategoryTypeThermostat: String
@available(watchOS 3.0, *)
let HMAccessoryCategoryTypeVideoDoorbell: String
@available(watchOS 2.0, *)
let HMAccessoryCategoryTypeWindow: String
@available(watchOS 2.0, *)
let HMAccessoryCategoryTypeWindowCovering: String
@available(watchOS 3.1.1, *)
let HMAccessoryCategoryTypeAirPurifier: String
@available(watchOS 3.1.1, *)
let HMAccessoryCategoryTypeAirHeater: String
@available(watchOS 3.1.1, *)
let HMAccessoryCategoryTypeAirConditioner: String
@available(watchOS 3.1.1, *)
let HMAccessoryCategoryTypeAirHumidifier: String
@available(watchOS 3.1.1, *)
let HMAccessoryCategoryTypeAirDehumidifier: String
@available(watchOS 4.2, *)
let HMAccessoryCategoryTypeSprinkler: String
@available(watchOS 4.2, *)
let HMAccessoryCategoryTypeFaucet: String
@available(watchOS 4.2, *)
let HMAccessoryCategoryTypeShowerHead: String
