
extension NSNotification.Name {
  @available(watchOS 2.0, *)
  static let HMCharacteristicPropertySupportsEvent: NSNotification.Name
}
@available(watchOS 2.0, *)
let HMCharacteristicPropertyReadable: String
@available(watchOS 2.0, *)
let HMCharacteristicPropertyWritable: String
@available(watchOS 2.2, *)
let HMCharacteristicPropertyHidden: String
@available(watchOS 2.0, *)
let HMCharacteristicTypeTargetRelativeHumidity: String
@available(watchOS, introduced: 2.0, deprecated: 4.0)
let HMCharacteristicTypeManufacturer: String
@available(watchOS, introduced: 2.0, deprecated: 4.0)
let HMCharacteristicTypeModel: String
@available(watchOS, introduced: 2.0, deprecated: 4.0, message: "No longer supported")
let HMCharacteristicTypeSerialNumber: String
@available(watchOS 2.0, *)
let HMCharacteristicTypeIdentify: String
@available(watchOS 2.0, *)
let HMCharacteristicTypeOutletInUse: String
@available(watchOS 2.0, *)
let HMCharacteristicTypeLogs: String
@available(watchOS 2.0, *)
let HMCharacteristicTypeAudioFeedback: String
@available(watchOS 2.0, *)
let HMCharacteristicTypeAdminOnlyAccess: String
@available(watchOS 2.0, *)
let HMCharacteristicTypeSecuritySystemAlarmType: String
@available(watchOS 2.0, *)
let HMCharacteristicTypeMotionDetected: String
@available(watchOS 2.0, *)
let HMCharacteristicTypeLockMechanismLastKnownAction: String
@available(watchOS 2.0, *)
let HMCharacteristicTypeLockManagementControlPoint: String
@available(watchOS 2.0, *)
let HMCharacteristicTypeLockManagementAutoSecureTimeout: String
@available(watchOS 2.0, *)
let HMCharacteristicTypeAirParticulateDensity: String
@available(watchOS 2.0, *)
let HMCharacteristicTypeAirParticulateSize: String
@available(watchOS 2.0, *)
let HMCharacteristicTypeAirQuality: String
@available(watchOS 2.0, *)
let HMCharacteristicTypeCarbonDioxideDetected: String
@available(watchOS 2.0, *)
let HMCharacteristicTypeCarbonDioxideLevel: String
@available(watchOS 2.0, *)
let HMCharacteristicTypeCarbonDioxidePeakLevel: String
@available(watchOS 2.0, *)
let HMCharacteristicTypeCarbonMonoxideDetected: String
@available(watchOS 2.0, *)
let HMCharacteristicTypeCarbonMonoxideLevel: String
@available(watchOS 2.0, *)
let HMCharacteristicTypeCarbonMonoxidePeakLevel: String
@available(watchOS 2.0, *)
let HMCharacteristicTypeContactState: String
@available(watchOS 2.0, *)
let HMCharacteristicTypeCurrentHorizontalTilt: String
@available(watchOS 2.0, *)
let HMCharacteristicTypeCurrentPosition: String
@available(watchOS 2.0, *)
let HMCharacteristicTypeCurrentSecuritySystemState: String
@available(watchOS 2.0, *)
let HMCharacteristicTypeCurrentVerticalTilt: String
@available(watchOS, introduced: 2.0, deprecated: 4.0)
let HMCharacteristicTypeFirmwareVersion: String
@available(watchOS 2.0, *)
let HMCharacteristicTypeHardwareVersion: String
@available(watchOS 2.0, *)
let HMCharacteristicTypeHoldPosition: String
@available(watchOS 2.0, *)
let HMCharacteristicTypeLeakDetected: String
@available(watchOS 2.0, *)
let HMCharacteristicTypeOccupancyDetected: String
@available(watchOS 2.0, *)
let HMCharacteristicTypeOutputState: String
@available(watchOS 2.0, *)
let HMCharacteristicTypePositionState: String
@available(watchOS 2.0, *)
let HMCharacteristicTypeSoftwareVersion: String
@available(watchOS 2.0, *)
let HMCharacteristicTypeStatusActive: String
@available(watchOS 2.0, *)
let HMCharacteristicTypeStatusFault: String
@available(watchOS 2.0, *)
let HMCharacteristicTypeStatusJammed: String
@available(watchOS 2.0, *)
let HMCharacteristicTypeStatusTampered: String
@available(watchOS 2.0, *)
let HMCharacteristicTypeTargetHorizontalTilt: String
@available(watchOS 2.0, *)
let HMCharacteristicTypeTargetSecuritySystemState: String
@available(watchOS 2.0, *)
let HMCharacteristicTypeTargetPosition: String
@available(watchOS 2.0, *)
let HMCharacteristicTypeTargetVerticalTilt: String
@available(watchOS 3.0, *)
let HMCharacteristicTypeStreamingStatus: String
@available(watchOS 3.0, *)
let HMCharacteristicTypeSetupStreamEndpoint: String
@available(watchOS 3.0, *)
let HMCharacteristicTypeSupportedVideoStreamConfiguration: String
@available(watchOS 3.0, *)
let HMCharacteristicTypeSupportedRTPConfiguration: String
@available(watchOS 3.0, *)
let HMCharacteristicTypeSelectedStreamConfiguration: String
@available(watchOS 3.0, *)
let HMCharacteristicTypeOpticalZoom: String
@available(watchOS 3.0, *)
let HMCharacteristicTypeDigitalZoom: String
@available(watchOS 3.0, *)
let HMCharacteristicTypeImageRotation: String
@available(watchOS 3.0, *)
let HMCharacteristicTypeImageMirroring: String
@available(watchOS 3.2, *)
let HMCharacteristicTypeLabelNamespace: String
@available(watchOS 3.2, *)
let HMCharacteristicTypeLabelIndex: String
@available(watchOS 3.1.1, *)
let HMCharacteristicTypeCurrentAirPurifierState: String
@available(watchOS 3.1.1, *)
let HMCharacteristicTypeTargetAirPurifierState: String
@available(watchOS 3.1.1, *)
let HMCharacteristicTypeCurrentSlatState: String
@available(watchOS 3.1.1, *)
let HMCharacteristicTypeFilterChangeIndication: String
@available(watchOS 3.1.1, *)
let HMCharacteristicTypeFilterLifeLevel: String
@available(watchOS 3.1.1, *)
let HMCharacteristicTypeFilterResetChangeIndication: String
@available(watchOS 3.1.1, *)
let HMCharacteristicTypeSlatType: String
@available(watchOS 3.1.1, *)
let HMCharacteristicTypeCurrentTilt: String
@available(watchOS 3.1.1, *)
let HMCharacteristicTypeTargetTilt: String
@available(watchOS 3.1.1, *)
let HMCharacteristicTypeOzoneDensity: String
@available(watchOS 3.1.1, *)
let HMCharacteristicTypeNitrogenDioxideDensity: String
@available(watchOS 3.1.1, *)
let HMCharacteristicTypeSulphurDioxideDensity: String
@available(watchOS 3.1.1, *)
let HMCharacteristicTypePM2_5Density: String
@available(watchOS 3.1.1, *)
let HMCharacteristicTypePM10Density: String
@available(watchOS 3.1.1, *)
let HMCharacteristicTypeVolatileOrganicCompoundDensity: String
@available(watchOS 4.2, *)
let HMCharacteristicTypeProgramMode: String
@available(watchOS 4.2, *)
let HMCharacteristicTypeInUse: String
@available(watchOS 4.2, *)
let HMCharacteristicTypeSetDuration: String
@available(watchOS 4.2, *)
let HMCharacteristicTypeRemainingDuration: String
@available(watchOS 4.2, *)
let HMCharacteristicTypeValveType: String
@available(watchOS 2.0, *)
let HMCharacteristicTypeBrightness: String
@available(watchOS 2.0, *)
let HMCharacteristicTypeCoolingThreshold: String
@available(watchOS 2.0, *)
let HMCharacteristicTypeCurrentDoorState: String
@available(watchOS 2.0, *)
let HMCharacteristicTypeCurrentHeatingCooling: String
@available(watchOS 2.0, *)
let HMCharacteristicTypeCurrentRelativeHumidity: String
@available(watchOS 2.0, *)
let HMCharacteristicTypeCurrentTemperature: String
@available(watchOS 2.0, *)
let HMCharacteristicTypeHeatingThreshold: String
@available(watchOS 2.0, *)
let HMCharacteristicTypeHue: String
@available(watchOS 2.0, *)
let HMCharacteristicTypeCurrentLockMechanismState: String
@available(watchOS 2.0, *)
let HMCharacteristicTypeTargetLockMechanismState: String
@available(watchOS 2.0, *)
let HMCharacteristicTypeName: String
@available(watchOS 2.0, *)
let HMCharacteristicTypeObstructionDetected: String
@available(watchOS 2.0, *)
let HMCharacteristicTypePowerState: String
@available(watchOS 2.0, *)
let HMCharacteristicTypeRotationDirection: String
@available(watchOS 2.0, *)
let HMCharacteristicTypeRotationSpeed: String
@available(watchOS 2.0, *)
let HMCharacteristicTypeSaturation: String
@available(watchOS 2.0, *)
let HMCharacteristicTypeTargetDoorState: String
@available(watchOS 2.0, *)
let HMCharacteristicTypeTargetHeatingCooling: String
@available(watchOS 2.0, *)
let HMCharacteristicTypeTargetTemperature: String
@available(watchOS 2.0, *)
let HMCharacteristicTypeTemperatureUnits: String
@available(watchOS 2.0, *)
let HMCharacteristicTypeVersion: String
@available(watchOS 2.0, *)
let HMCharacteristicTypeBatteryLevel: String
@available(watchOS 2.0, *)
let HMCharacteristicTypeCurrentLightLevel: String
@available(watchOS 2.0, *)
let HMCharacteristicTypeInputEvent: String
@available(watchOS 2.0, *)
let HMCharacteristicTypeSmokeDetected: String
@available(watchOS 2.0, *)
let HMCharacteristicTypeStatusLowBattery: String
@available(watchOS 2.0, *)
let HMCharacteristicTypeChargingState: String
@available(watchOS 3.1.1, *)
let HMCharacteristicTypeLockPhysicalControls: String
@available(watchOS 3.1.1, *)
let HMCharacteristicTypeCurrentFanState: String
@available(watchOS 3.1.1, *)
let HMCharacteristicTypeActive: String
@available(watchOS 3.1.1, *)
let HMCharacteristicTypeCurrentHeaterCoolerState: String
@available(watchOS 3.1.1, *)
let HMCharacteristicTypeTargetHeaterCoolerState: String
@available(watchOS 3.1.1, *)
let HMCharacteristicTypeCurrentHumidifierDehumidifierState: String
@available(watchOS 3.1.1, *)
let HMCharacteristicTypeTargetHumidifierDehumidifierState: String
@available(watchOS 3.1.1, *)
let HMCharacteristicTypeWaterLevel: String
@available(watchOS 3.1.1, *)
let HMCharacteristicTypeSwingMode: String
@available(watchOS 3.1.1, *)
let HMCharacteristicTypeTargetFanState: String
@available(watchOS 3.1.1, *)
let HMCharacteristicTypeDehumidifierThreshold: String
@available(watchOS 3.1.1, *)
let HMCharacteristicTypeHumidifierThreshold: String
@available(watchOS 4.0, *)
let HMCharacteristicTypeColorTemperature: String
@available(watchOS 4.2, *)
let HMCharacteristicTypeIsConfigured: String
@available(watchOS 3.0, *)
let HMCharacteristicTypeSupportedAudioStreamConfiguration: String
@available(watchOS 3.0, *)
let HMCharacteristicTypeVolume: String
@available(watchOS 3.0, *)
let HMCharacteristicTypeMute: String
@available(watchOS 3.0, *)
let HMCharacteristicTypeNightVision: String
