
@available(tvOS 14.0, *)
let GCInputButtonA: String
@available(tvOS 14.0, *)
let GCInputButtonB: String
@available(tvOS 14.0, *)
let GCInputButtonX: String
@available(tvOS 14.0, *)
let GCInputButtonY: String
@available(tvOS 14.0, *)
let GCInputDirectionPad: String
@available(tvOS 14.0, *)
let GCInputLeftThumbstick: String
@available(tvOS 14.0, *)
let GCInputRightThumbstick: String
@available(tvOS 14.0, *)
let GCInputLeftShoulder: String
@available(tvOS 14.0, *)
let GCInputRightShoulder: String
@available(tvOS 14.0, *)
let GCInputLeftTrigger: String
@available(tvOS 14.0, *)
let GCInputRightTrigger: String
@available(tvOS 14.0, *)
let GCInputLeftThumbstickButton: String
@available(tvOS 14.0, *)
let GCInputRightThumbstickButton: String
@available(tvOS 14.0, *)
let GCInputButtonHome: String
@available(tvOS 14.0, *)
let GCInputButtonMenu: String
@available(tvOS 14.0, *)
let GCInputButtonOptions: String
@available(tvOS 14.0, *)
let GCInputXboxPaddleOne: String
@available(tvOS 14.0, *)
let GCInputXboxPaddleTwo: String
@available(tvOS 14.0, *)
let GCInputXboxPaddleThree: String
@available(tvOS 14.0, *)
let GCInputXboxPaddleFour: String
@available(tvOS 14.0, *)
let GCInputDualShockTouchpadOne: String
@available(tvOS 14.0, *)
let GCInputDualShockTouchpadTwo: String
@available(tvOS 14.0, *)
let GCInputDualShockTouchpadButton: String
