
@available(iOS 8.0, *)
let HMServiceTypeSwitch: String
@available(iOS 8.0, *)
let HMServiceTypeThermostat: String
@available(iOS 8.0, *)
let HMServiceTypeAccessoryInformation: String
@available(iOS 8.0, *)
let HMServiceTypeOutlet: String
@available(iOS 8.0, *)
let HMServiceTypeLockManagement: String
@available(iOS 9.0, *)
let HMServiceTypeAirQualitySensor: String
@available(iOS 9.0, *)
let HMServiceTypeCarbonDioxideSensor: String
@available(iOS 9.0, *)
let HMServiceTypeCarbonMonoxideSensor: String
@available(iOS 9.0, *)
let HMServiceTypeContactSensor: String
@available(iOS 9.0, *)
let HMServiceTypeDoor: String
@available(iOS 9.0, *)
let HMServiceTypeHumiditySensor: String
@available(iOS 9.0, *)
let HMServiceTypeLeakSensor: String
@available(iOS 9.0, *)
let HMServiceTypeLightSensor: String
@available(iOS 9.0, *)
let HMServiceTypeMotionSensor: String
@available(iOS 9.0, *)
let HMServiceTypeOccupancySensor: String
@available(iOS 9.0, *)
let HMServiceTypeSecuritySystem: String
@available(iOS 9.0, *)
let HMServiceTypeStatefulProgrammableSwitch: String
@available(iOS 9.0, *)
let HMServiceTypeStatelessProgrammableSwitch: String
@available(iOS 9.0, *)
let HMServiceTypeSmokeSensor: String
@available(iOS 9.0, *)
let HMServiceTypeTemperatureSensor: String
@available(iOS 9.0, *)
let HMServiceTypeWindow: String
@available(iOS 9.0, *)
let HMServiceTypeWindowCovering: String
@available(iOS 10.0, *)
let HMServiceTypeCameraRTPStreamManagement: String
@available(iOS 10.0, *)
let HMServiceTypeCameraControl: String
@available(iOS 10.0, *)
let HMServiceTypeMicrophone: String
@available(iOS 10.0, *)
let HMServiceTypeSpeaker: String
@available(iOS 10.2, *)
let HMServiceTypeAirPurifier: String
@available(iOS 10.2, *)
let HMServiceTypeFilterMaintenance: String
@available(iOS 10.2, *)
let HMServiceTypeSlats: String
@available(iOS 10.3, *)
let HMServiceTypeLabel: String
@available(iOS 11.2, *)
let HMServiceTypeIrrigationSystem: String
@available(iOS 11.2, *)
let HMServiceTypeValve: String
@available(iOS 11.2, *)
let HMServiceTypeFaucet: String
@available(iOS 8.0, *)
let HMServiceTypeFan: String
@available(iOS 8.0, *)
let HMServiceTypeGarageDoorOpener: String
@available(iOS 8.0, *)
let HMServiceTypeLightbulb: String
@available(iOS 8.0, *)
let HMServiceTypeLockMechanism: String
@available(iOS 9.0, *)
let HMServiceTypeBattery: String
@available(iOS 10.2, *)
let HMServiceTypeVentilationFan: String
@available(iOS 10.2, *)
let HMServiceTypeHeaterCooler: String
@available(iOS 10.2, *)
let HMServiceTypeHumidifierDehumidifier: String
@available(iOS 10.0, *)
let HMServiceTypeDoorbell: String
