
let kABUIDProperty: String
let kABCreationDateProperty: String
let kABModificationDateProperty: String
let kABFirstNameProperty: String
let kABLastNameProperty: String
let kABFirstNamePhoneticProperty: String
let kABLastNamePhoneticProperty: String
let kABNicknameProperty: String
let kABMaidenNameProperty: String
let kABBirthdayProperty: String
@available(macOS 10.7, *)
let kABBirthdayComponentsProperty: String
let kABAlternateBirthdayComponentsProperty: String
let kABOrganizationProperty: String
let kABOrganizationPhoneticProperty: String
let kABJobTitleProperty: String
let kABHomePageProperty: String
@available(macOS 10.4, *)
let kABURLsProperty: String
@available(macOS 10.4, *)
let kABHomePageLabel: String
@available(macOS 10.5, *)
let kABCalendarURIsProperty: String
let kABEmailProperty: String
let kABEmailWorkLabel: String
let kABEmailHomeLabel: String
let kABEmailMobileMeLabel: String
let kABAddressProperty: String
let kABAddressStreetKey: String
let kABAddressCityKey: String
let kABAddressStateKey: String
let kABAddressZIPKey: String
let kABAddressCountryKey: String
let kABAddressCountryCodeKey: String
let kABAddressHomeLabel: String
let kABAddressWorkLabel: String
@available(macOS 10.3, *)
let kABOtherDatesProperty: String
@available(macOS 10.7, *)
let kABOtherDateComponentsProperty: String
@available(macOS 10.3, *)
let kABAnniversaryLabel: String
@available(macOS 10.3, *)
let kABRelatedNamesProperty: String
@available(macOS 10.3, *)
let kABFatherLabel: String
@available(macOS 10.3, *)
let kABMotherLabel: String
@available(macOS 10.3, *)
let kABParentLabel: String
@available(macOS 10.3, *)
let kABBrotherLabel: String
@available(macOS 10.3, *)
let kABSisterLabel: String
@available(macOS 10.3, *)
let kABChildLabel: String
@available(macOS 10.3, *)
let kABFriendLabel: String
@available(macOS 10.3, *)
let kABSpouseLabel: String
@available(macOS 10.3, *)
let kABPartnerLabel: String
@available(macOS 10.3, *)
let kABAssistantLabel: String
@available(macOS 10.3, *)
let kABManagerLabel: String
@available(macOS 10.3, *)
let kABDepartmentProperty: String
@available(macOS 10.3, *)
let kABPersonFlags: String
var kABShowAsMask: Int32 { get }
var kABShowAsPerson: Int32 { get }
var kABShowAsCompany: Int32 { get }
var kABShowAsResource: Int32 { get }
var kABShowAsRoom: Int32 { get }
var kABNameOrderingMask: Int32 { get }
var kABDefaultNameOrdering: Int32 { get }
var kABFirstNameFirst: Int32 { get }
var kABLastNameFirst: Int32 { get }
let kABPhoneProperty: String
let kABPhoneWorkLabel: String
let kABPhoneHomeLabel: String
let kABPhoneiPhoneLabel: String
let kABPhoneMobileLabel: String
let kABPhoneMainLabel: String
let kABPhoneHomeFAXLabel: String
let kABPhoneWorkFAXLabel: String
let kABPhonePagerLabel: String
@available(macOS 10.7, *)
let kABInstantMessageProperty: String
@available(macOS 10.7, *)
let kABInstantMessageUsernameKey: String
@available(macOS 10.7, *)
let kABInstantMessageServiceKey: String
@available(macOS 10.7, *)
let kABInstantMessageServiceAIM: String
@available(macOS 10.7, *)
let kABInstantMessageServiceFacebook: String
@available(macOS 10.7, *)
let kABInstantMessageServiceGaduGadu: String
@available(macOS 10.7, *)
let kABInstantMessageServiceGoogleTalk: String
@available(macOS 10.7, *)
let kABInstantMessageServiceICQ: String
@available(macOS 10.7, *)
let kABInstantMessageServiceJabber: String
@available(macOS 10.7, *)
let kABInstantMessageServiceMSN: String
@available(macOS 10.7, *)
let kABInstantMessageServiceQQ: String
@available(macOS 10.7, *)
let kABInstantMessageServiceSkype: String
@available(macOS 10.7, *)
let kABInstantMessageServiceYahoo: String
@available(macOS 10.7, *)
let kABSocialProfileProperty: String
@available(macOS 10.7, *)
let kABSocialProfileURLKey: String
@available(macOS 10.7, *)
let kABSocialProfileUsernameKey: String
@available(macOS 10.7, *)
let kABSocialProfileUserIdentifierKey: String
@available(macOS 10.7, *)
let kABSocialProfileServiceKey: String
@available(macOS 10.7, *)
let kABSocialProfileServiceTwitter: String
@available(macOS 10.7, *)
let kABSocialProfileServiceFacebook: String
@available(macOS 10.7, *)
let kABSocialProfileServiceLinkedIn: String
@available(macOS 10.7, *)
let kABSocialProfileServiceFlickr: String
@available(macOS 10.7, *)
let kABSocialProfileServiceMySpace: String
@available(macOS 10.8, *)
let kABSocialProfileServiceSinaWeibo: String
@available(macOS 10.9, *)
let kABSocialProfileServiceTencentWeibo: String
@available(macOS 10.9, *)
let kABSocialProfileServiceYelp: String
let kABNoteProperty: String
let kABMiddleNameProperty: String
let kABMiddleNamePhoneticProperty: String
let kABTitleProperty: String
let kABSuffixProperty: String
let kABGroupNameProperty: String
let kABWorkLabel: String
let kABHomeLabel: String
let kABOtherLabel: String
@available(macOS 10.7, *)
let kABMobileMeLabel: String
extension NSNotification.Name {
  static let abDatabaseChanged: NSNotification.Name
  static let abDatabaseChangedExternally: NSNotification.Name
}
@available(macOS 10.3, *)
let kABInsertedRecords: String
@available(macOS 10.3, *)
let kABUpdatedRecords: String
@available(macOS 10.3, *)
let kABDeletedRecords: String
func ABLocalizedPropertyOrLabel(_ propertyOrLabel: String!) -> String!
