
protocol CLLocationManagerDelegate : NSObjectProtocol {
  @available(watchOS, introduced: 2.0, deprecated: 2.0, message: "Implement -locationManager:didUpdateLocations: instead")
  optional func locationManager(_ manager: CLLocationManager, didUpdateTo newLocation: CLLocation, from oldLocation: CLLocation)
  @available(watchOS 2.0, *)
  optional func locationManager(_ manager: CLLocationManager, didUpdateLocations locations: [CLLocation])
  @available(watchOS 2.0, *)
  optional func locationManager(_ manager: CLLocationManager, didUpdateHeading newHeading: CLHeading)
  @available(watchOS 2.0, *)
  optional func locationManagerShouldDisplayHeadingCalibration(_ manager: CLLocationManager) -> Bool
  @available(watchOS 2.0, *)
  optional func locationManager(_ manager: CLLocationManager, didDetermineState state: CLRegionState, for region: CLRegion)
  @available(watchOS, introduced: 2.0, deprecated: 6.0)
  optional func locationManager(_ manager: CLLocationManager, didRangeBeacons beacons: [CLBeacon], in region: CLBeaconRegion)
  @available(watchOS, introduced: 2.0, deprecated: 6.0)
  optional func locationManager(_ manager: CLLocationManager, rangingBeaconsDidFailFor region: CLBeaconRegion, withError error: Error)
  @available(watchOS 6.0, *)
  optional func locationManager(_ manager: CLLocationManager, didRange beacons: [CLBeacon], satisfying beaconConstraint: CLBeaconIdentityConstraint)
  @available(watchOS 6.0, *)
  optional func locationManager(_ manager: CLLocationManager, didFailRangingFor beaconConstraint: CLBeaconIdentityConstraint, error: Error)
  @available(watchOS 2.0, *)
  optional func locationManager(_ manager: CLLocationManager, didEnterRegion region: CLRegion)
  @available(watchOS 2.0, *)
  optional func locationManager(_ manager: CLLocationManager, didExitRegion region: CLRegion)
  @available(watchOS 2.0, *)
  optional func locationManager(_ manager: CLLocationManager, didFailWithError error: Error)
  @available(watchOS 2.0, *)
  optional func locationManager(_ manager: CLLocationManager, monitoringDidFailFor region: CLRegion?, withError error: Error)
  @available(watchOS, introduced: 1.0, deprecated: 7.0)
  optional func locationManager(_ manager: CLLocationManager, didChangeAuthorization status: CLAuthorizationStatus)
  @available(watchOS 7.0, *)
  optional func locationManagerDidChangeAuthorization(_ manager: CLLocationManager)
  @available(watchOS 2.0, *)
  optional func locationManager(_ manager: CLLocationManager, didStartMonitoringFor region: CLRegion)
  @available(watchOS 2.0, *)
  optional func locationManagerDidPauseLocationUpdates(_ manager: CLLocationManager)
  @available(watchOS 2.0, *)
  optional func locationManagerDidResumeLocationUpdates(_ manager: CLLocationManager)
  @available(watchOS 2.0, *)
  optional func locationManager(_ manager: CLLocationManager, didFinishDeferredUpdatesWithError error: Error?)
  @available(watchOS 2.0, *)
  optional func locationManager(_ manager: CLLocationManager, didVisit visit: CLVisit)
}
