
@available(macOS 10.7, *)
class IOBluetoothHandsFreeDevice : IOBluetoothHandsFree {
  @available(macOS 10.7, *)
  func dialNumber(_ aNumber: String!)
  @available(macOS 10.7, *)
  func memoryDial(_ memoryLocation: Int32)
  @available(macOS 10.7, *)
  func redial()
  @available(macOS 10.7, *)
  func endCall()
  @available(macOS 10.7, *)
  func acceptCall()
  @available(macOS 10.7, *)
  func acceptCallOnPhone()
  @available(macOS 10.7, *)
  func sendDTMF(_ character: String!)
  @available(macOS 10.7, *)
  func subscriberNumber()
  @available(macOS 10.7, *)
  func currentCallList()
  @available(macOS 10.7, *)
  func releaseHeldCalls()
  @available(macOS 10.7, *)
  func releaseActiveCalls()
  @available(macOS 10.7, *)
  func releaseCall(_ index: Int32)
  @available(macOS 10.7, *)
  func holdCall()
  @available(macOS 10.7, *)
  func placeAllOthers(onHold index: Int32)
  @available(macOS 10.7, *)
  func addHeldCall()
  @available(macOS 10.7, *)
  func callTransfer()
  @available(macOS 10.7, *)
  func transferAudioToComputer()
  @available(macOS 10.7, *)
  func transferAudioToPhone()
  @available(macOS 10.7, *)
  func sendSMS(_ aNumber: String!, message aMessage: String!)
  @available(macOS 10.7, *)
  func send(atCommand: String!)
  @available(macOS 10.7, *)
  func send(atCommand: String!, timeout: Float, selector: Selector!, target: Any!)
}
protocol IOBluetoothHandsFreeDeviceDelegate : IOBluetoothHandsFreeDelegate {
  @available(macOS 10.7, *)
  optional func handsFree(_ device: IOBluetoothHandsFreeDevice!, isServiceAvailable: NSNumber!)
  @available(macOS 10.7, *)
  optional func handsFree(_ device: IOBluetoothHandsFreeDevice!, isCallActive: NSNumber!)
  @available(macOS 10.7, *)
  optional func handsFree(_ device: IOBluetoothHandsFreeDevice!, callSetupMode: NSNumber!)
  @available(macOS 10.7, *)
  optional func handsFree(_ device: IOBluetoothHandsFreeDevice!, callHoldState: NSNumber!)
  @available(macOS 10.7, *)
  optional func handsFree(_ device: IOBluetoothHandsFreeDevice!, signalStrength: NSNumber!)
  @available(macOS 10.7, *)
  optional func handsFree(_ device: IOBluetoothHandsFreeDevice!, isRoaming: NSNumber!)
  @available(macOS 10.7, *)
  optional func handsFree(_ device: IOBluetoothHandsFreeDevice!, batteryCharge: NSNumber!)
  @available(macOS 10.7, *)
  optional func handsFree(_ device: IOBluetoothHandsFreeDevice!, incomingCallFrom number: String!)
  @available(macOS 10.7, *)
  optional func handsFree(_ device: IOBluetoothHandsFreeDevice!, ringAttempt: NSNumber!)
  @available(macOS 10.7, *)
  optional func handsFree(_ device: IOBluetoothHandsFreeDevice!, currentCall: [AnyHashable : Any]!)
  @available(macOS 10.7, *)
  optional func handsFree(_ device: IOBluetoothHandsFreeDevice!, subscriberNumber: String!)
  @available(macOS 10.7, *)
  optional func handsFree(_ device: IOBluetoothHandsFreeDevice!, incomingSMS sms: [AnyHashable : Any]!)
  @available(macOS 10.7, *)
  optional func handsFree(_ device: IOBluetoothHandsFreeDevice!, unhandledResultCode resultCode: String!)
}
