
@available(tvOS 9.0, *)
let NSMetadataItemFSNameKey: String
@available(tvOS 9.0, *)
let NSMetadataItemDisplayNameKey: String
@available(tvOS 9.0, *)
let NSMetadataItemURLKey: String
@available(tvOS 9.0, *)
let NSMetadataItemPathKey: String
@available(tvOS 9.0, *)
let NSMetadataItemFSSizeKey: String
@available(tvOS 9.0, *)
let NSMetadataItemFSCreationDateKey: String
@available(tvOS 9.0, *)
let NSMetadataItemFSContentChangeDateKey: String
@available(tvOS 9.0, *)
let NSMetadataItemContentTypeKey: String
@available(tvOS 9.0, *)
let NSMetadataItemContentTypeTreeKey: String
@available(tvOS 9.0, *)
let NSMetadataItemIsUbiquitousKey: String
@available(tvOS 9.0, *)
let NSMetadataUbiquitousItemHasUnresolvedConflictsKey: String
@available(tvOS, introduced: 9.0, deprecated: 9.0, message: "Use NSMetadataUbiquitousItemDownloadingStatusKey instead")
let NSMetadataUbiquitousItemIsDownloadedKey: String
@available(tvOS 9.0, *)
let NSMetadataUbiquitousItemDownloadingStatusKey: String
@available(tvOS 9.0, *)
let NSMetadataUbiquitousItemDownloadingStatusNotDownloaded: String
@available(tvOS 9.0, *)
let NSMetadataUbiquitousItemDownloadingStatusDownloaded: String
@available(tvOS 9.0, *)
let NSMetadataUbiquitousItemDownloadingStatusCurrent: String
@available(tvOS 9.0, *)
let NSMetadataUbiquitousItemIsDownloadingKey: String
@available(tvOS 9.0, *)
let NSMetadataUbiquitousItemIsUploadedKey: String
@available(tvOS 9.0, *)
let NSMetadataUbiquitousItemIsUploadingKey: String
@available(tvOS 9.0, *)
let NSMetadataUbiquitousItemPercentDownloadedKey: String
@available(tvOS 9.0, *)
let NSMetadataUbiquitousItemPercentUploadedKey: String
@available(tvOS 9.0, *)
let NSMetadataUbiquitousItemDownloadingErrorKey: String
@available(tvOS 9.0, *)
let NSMetadataUbiquitousItemUploadingErrorKey: String
@available(tvOS 9.0, *)
let NSMetadataUbiquitousItemDownloadRequestedKey: String
@available(tvOS 9.0, *)
let NSMetadataUbiquitousItemIsExternalDocumentKey: String
@available(tvOS 9.0, *)
let NSMetadataUbiquitousItemContainerDisplayNameKey: String
@available(tvOS 9.0, *)
let NSMetadataUbiquitousItemURLInLocalContainerKey: String
@available(tvOS 10.0, *)
let NSMetadataUbiquitousItemIsSharedKey: String
@available(tvOS 10.0, *)
let NSMetadataUbiquitousSharedItemCurrentUserRoleKey: String
@available(tvOS 10.0, *)
let NSMetadataUbiquitousSharedItemCurrentUserPermissionsKey: String
@available(tvOS 10.0, *)
let NSMetadataUbiquitousSharedItemOwnerNameComponentsKey: String
@available(tvOS 10.0, *)
let NSMetadataUbiquitousSharedItemMostRecentEditorNameComponentsKey: String
@available(tvOS 10.0, *)
let NSMetadataUbiquitousSharedItemRoleOwner: String
@available(tvOS 10.0, *)
let NSMetadataUbiquitousSharedItemRoleParticipant: String
@available(tvOS 10.0, *)
let NSMetadataUbiquitousSharedItemPermissionsReadOnly: String
@available(tvOS 10.0, *)
let NSMetadataUbiquitousSharedItemPermissionsReadWrite: String
