
@available(tvOS 10.2, *)
let kVTCompressionPropertyKey_NumberOfPendingFrames: CFString
@available(tvOS 10.2, *)
let kVTCompressionPropertyKey_PixelBufferPoolIsShared: CFString
@available(tvOS 10.2, *)
let kVTCompressionPropertyKey_VideoEncoderPixelBufferAttributes: CFString
@available(tvOS 10.2, *)
let kVTCompressionPropertyKey_MaxKeyFrameInterval: CFString
@available(tvOS 10.2, *)
let kVTCompressionPropertyKey_MaxKeyFrameIntervalDuration: CFString
@available(tvOS 10.2, *)
let kVTCompressionPropertyKey_AllowTemporalCompression: CFString
@available(tvOS 10.2, *)
let kVTCompressionPropertyKey_AllowFrameReordering: CFString
@available(tvOS 12.0, *)
let kVTCompressionPropertyKey_AllowOpenGOP: CFString
@available(tvOS 10.2, *)
let kVTCompressionPropertyKey_AverageBitRate: CFString
@available(tvOS 10.2, *)
let kVTCompressionPropertyKey_DataRateLimits: CFString
@available(tvOS 10.2, *)
let kVTCompressionPropertyKey_Quality: CFString
@available(tvOS 13.0, *)
let kVTCompressionPropertyKey_TargetQualityForAlpha: CFString
@available(tvOS 10.2, *)
let kVTCompressionPropertyKey_MoreFramesBeforeStart: CFString
@available(tvOS 10.2, *)
let kVTCompressionPropertyKey_MoreFramesAfterEnd: CFString
@available(tvOS 14.0, *)
let kVTCompressionPropertyKey_PrioritizeEncodingSpeedOverQuality: CFString
@available(tvOS 10.2, *)
let kVTCompressionPropertyKey_ProfileLevel: CFString
@available(tvOS 11.0, *)
let kVTProfileLevel_HEVC_Main_AutoLevel: CFString
@available(tvOS 11.0, *)
let kVTProfileLevel_HEVC_Main10_AutoLevel: CFString
@available(tvOS 10.2, *)
let kVTProfileLevel_H264_Baseline_1_3: CFString
@available(tvOS 10.2, *)
let kVTProfileLevel_H264_Baseline_3_0: CFString
@available(tvOS 10.2, *)
let kVTProfileLevel_H264_Baseline_3_1: CFString
@available(tvOS 10.2, *)
let kVTProfileLevel_H264_Baseline_3_2: CFString
@available(tvOS 10.2, *)
let kVTProfileLevel_H264_Baseline_4_0: CFString
@available(tvOS 10.2, *)
let kVTProfileLevel_H264_Baseline_4_1: CFString
@available(tvOS 10.2, *)
let kVTProfileLevel_H264_Baseline_4_2: CFString
@available(tvOS 10.2, *)
let kVTProfileLevel_H264_Baseline_5_0: CFString
@available(tvOS 10.2, *)
let kVTProfileLevel_H264_Baseline_5_1: CFString
@available(tvOS 10.2, *)
let kVTProfileLevel_H264_Baseline_5_2: CFString
@available(tvOS 10.2, *)
let kVTProfileLevel_H264_Baseline_AutoLevel: CFString
@available(tvOS 10.2, *)
let kVTProfileLevel_H264_Main_3_0: CFString
@available(tvOS 10.2, *)
let kVTProfileLevel_H264_Main_3_1: CFString
@available(tvOS 10.2, *)
let kVTProfileLevel_H264_Main_3_2: CFString
@available(tvOS 10.2, *)
let kVTProfileLevel_H264_Main_4_0: CFString
@available(tvOS 10.2, *)
let kVTProfileLevel_H264_Main_4_1: CFString
@available(tvOS 10.2, *)
let kVTProfileLevel_H264_Main_4_2: CFString
@available(tvOS 10.2, *)
let kVTProfileLevel_H264_Main_5_0: CFString
@available(tvOS 10.2, *)
let kVTProfileLevel_H264_Main_5_1: CFString
@available(tvOS 10.2, *)
let kVTProfileLevel_H264_Main_5_2: CFString
@available(tvOS 10.2, *)
let kVTProfileLevel_H264_Main_AutoLevel: CFString
@available(tvOS 10.2, *)
let kVTProfileLevel_H264_Extended_5_0: CFString
@available(tvOS 10.2, *)
let kVTProfileLevel_H264_Extended_AutoLevel: CFString
@available(tvOS 10.2, *)
let kVTProfileLevel_H264_High_3_0: CFString
@available(tvOS 10.2, *)
let kVTProfileLevel_H264_High_3_1: CFString
@available(tvOS 10.2, *)
let kVTProfileLevel_H264_High_3_2: CFString
@available(tvOS 10.2, *)
let kVTProfileLevel_H264_High_4_0: CFString
@available(tvOS 10.2, *)
let kVTProfileLevel_H264_High_4_1: CFString
@available(tvOS 10.2, *)
let kVTProfileLevel_H264_High_4_2: CFString
@available(tvOS 10.2, *)
let kVTProfileLevel_H264_High_5_0: CFString
@available(tvOS 10.2, *)
let kVTProfileLevel_H264_High_5_1: CFString
@available(tvOS 10.2, *)
let kVTProfileLevel_H264_High_5_2: CFString
@available(tvOS 10.2, *)
let kVTProfileLevel_H264_High_AutoLevel: CFString
@available(tvOS 10.2, *)
let kVTProfileLevel_MP4V_Simple_L0: CFString
@available(tvOS 10.2, *)
let kVTProfileLevel_MP4V_Simple_L1: CFString
@available(tvOS 10.2, *)
let kVTProfileLevel_MP4V_Simple_L2: CFString
@available(tvOS 10.2, *)
let kVTProfileLevel_MP4V_Simple_L3: CFString
@available(tvOS 10.2, *)
let kVTProfileLevel_MP4V_Main_L2: CFString
@available(tvOS 10.2, *)
let kVTProfileLevel_MP4V_Main_L3: CFString
@available(tvOS 10.2, *)
let kVTProfileLevel_MP4V_Main_L4: CFString
@available(tvOS 10.2, *)
let kVTProfileLevel_MP4V_AdvancedSimple_L0: CFString
@available(tvOS 10.2, *)
let kVTProfileLevel_MP4V_AdvancedSimple_L1: CFString
@available(tvOS 10.2, *)
let kVTProfileLevel_MP4V_AdvancedSimple_L2: CFString
@available(tvOS 10.2, *)
let kVTProfileLevel_MP4V_AdvancedSimple_L3: CFString
@available(tvOS 10.2, *)
let kVTProfileLevel_MP4V_AdvancedSimple_L4: CFString
@available(tvOS 10.2, *)
let kVTProfileLevel_H263_Profile0_Level10: CFString
@available(tvOS 10.2, *)
let kVTProfileLevel_H263_Profile0_Level45: CFString
@available(tvOS 10.2, *)
let kVTProfileLevel_H263_Profile3_Level45: CFString
@available(tvOS 14.0, *)
let kVTCompressionPropertyKey_HDRMetadataInsertionMode: CFString
@available(tvOS 14.0, *)
let kVTHDRMetadataInsertionMode_None: CFString
@available(tvOS 14.0, *)
let kVTHDRMetadataInsertionMode_Auto: CFString
@available(tvOS 10.2, *)
let kVTCompressionPropertyKey_H264EntropyMode: CFString
@available(tvOS 10.2, *)
let kVTH264EntropyMode_CAVLC: CFString
@available(tvOS 10.2, *)
let kVTH264EntropyMode_CABAC: CFString
@available(tvOS 10.2, *)
let kVTCompressionPropertyKey_Depth: CFString
@available(tvOS 10.2, *)
let kVTCompressionPropertyKey_MaxFrameDelayCount: CFString
var kVTUnlimitedFrameDelayCount: Int { get }
@available(tvOS 10.2, *)
let kVTCompressionPropertyKey_MaxH264SliceBytes: CFString
@available(tvOS 10.2, *)
let kVTCompressionPropertyKey_RealTime: CFString
@available(tvOS 12.0, *)
let kVTCompressionPropertyKey_MaximizePowerEfficiency: CFString
@available(tvOS 10.2, *)
let kVTCompressionPropertyKey_SourceFrameCount: CFString
@available(tvOS 10.2, *)
let kVTCompressionPropertyKey_ExpectedFrameRate: CFString
@available(tvOS 10.2, *)
let kVTCompressionPropertyKey_ExpectedDuration: CFString
@available(tvOS 11.0, *)
let kVTCompressionPropertyKey_BaseLayerFrameRate: CFString
let kVTVideoEncoderSpecification_RequiredEncoderGPURegistryID: CFString
let kVTVideoEncoderSpecification_PreferredEncoderGPURegistryID: CFString
let kVTCompressionPropertyKey_UsingGPURegistryID: CFString
@available(tvOS 10.2, *)
let kVTEncodeFrameOptionKey_ForceKeyFrame: CFString
@available(tvOS 10.2, *)
let kVTCompressionPropertyKey_CleanAperture: CFString
@available(tvOS 10.2, *)
let kVTCompressionPropertyKey_PixelAspectRatio: CFString
@available(tvOS 10.2, *)
let kVTCompressionPropertyKey_FieldCount: CFString
@available(tvOS 10.2, *)
let kVTCompressionPropertyKey_FieldDetail: CFString
@available(tvOS 10.2, *)
let kVTCompressionPropertyKey_AspectRatio16x9: CFString
@available(tvOS 10.2, *)
let kVTCompressionPropertyKey_ProgressiveScan: CFString
@available(tvOS 10.2, *)
let kVTCompressionPropertyKey_ColorPrimaries: CFString
@available(tvOS 10.2, *)
let kVTCompressionPropertyKey_TransferFunction: CFString
@available(tvOS 10.2, *)
let kVTCompressionPropertyKey_YCbCrMatrix: CFString
@available(tvOS 10.2, *)
let kVTCompressionPropertyKey_ICCProfile: CFString
@available(tvOS 11.0, *)
let kVTCompressionPropertyKey_MasteringDisplayColorVolume: CFString
@available(tvOS 11.0, *)
let kVTCompressionPropertyKey_ContentLightLevelInfo: CFString
let kVTCompressionPropertyKey_GammaLevel: CFString
@available(tvOS 13.0, *)
let kVTCompressionPropertyKey_AlphaChannelMode: CFString
@available(tvOS 13.0, *)
let kVTAlphaChannelMode_StraightAlpha: CFString
@available(tvOS 13.0, *)
let kVTAlphaChannelMode_PremultipliedAlpha: CFString
@available(tvOS 10.2, *)
let kVTCompressionPropertyKey_PixelTransferProperties: CFString
@available(tvOS 10.2, *)
let kVTCompressionPropertyKey_MultiPassStorage: CFString
@available(tvOS 11.0, *)
let kVTCompressionPropertyKey_EncoderID: CFString
