
@available(tvOS 10.2, *)
let kVTDecompressionPropertyKey_PixelBufferPool: CFString
@available(tvOS 10.2, *)
let kVTDecompressionPropertyKey_PixelBufferPoolIsShared: CFString
@available(tvOS 10.2, *)
let kVTDecompressionPropertyKey_OutputPoolRequestedMinimumBufferCount: CFString
@available(tvOS 10.2, *)
let kVTDecompressionPropertyKey_NumberOfFramesBeingDecoded: CFString
@available(tvOS 10.2, *)
let kVTDecompressionPropertyKey_MinOutputPresentationTimeStampOfFramesBeingDecoded: CFString
@available(tvOS 10.2, *)
let kVTDecompressionPropertyKey_MaxOutputPresentationTimeStampOfFramesBeingDecoded: CFString
@available(tvOS 10.2, *)
let kVTDecompressionPropertyKey_ContentHasInterframeDependencies: CFString
@available(tvOS 10.2, *)
let kVTDecompressionPropertyKey_RealTime: CFString
@available(tvOS 10.2, *)
let kVTDecompressionPropertyKey_MaximizePowerEfficiency: CFString
@available(tvOS 10.2, *)
let kVTDecompressionPropertyKey_ThreadCount: CFString
@available(tvOS 10.2, *)
let kVTDecompressionPropertyKey_FieldMode: CFString
@available(tvOS 10.2, *)
let kVTDecompressionProperty_FieldMode_BothFields: CFString
@available(tvOS 10.2, *)
let kVTDecompressionProperty_FieldMode_TopFieldOnly: CFString
@available(tvOS 10.2, *)
let kVTDecompressionProperty_FieldMode_BottomFieldOnly: CFString
@available(tvOS 10.2, *)
let kVTDecompressionProperty_FieldMode_SingleField: CFString
@available(tvOS 10.2, *)
let kVTDecompressionProperty_FieldMode_DeinterlaceFields: CFString
@available(tvOS 10.2, *)
let kVTDecompressionPropertyKey_DeinterlaceMode: CFString
@available(tvOS 10.2, *)
let kVTDecompressionProperty_DeinterlaceMode_VerticalFilter: CFString
@available(tvOS 10.2, *)
let kVTDecompressionProperty_DeinterlaceMode_Temporal: CFString
@available(tvOS 10.2, *)
let kVTDecompressionPropertyKey_ReducedResolutionDecode: CFString
@available(tvOS 10.2, *)
let kVTDecompressionResolutionKey_Width: CFString
@available(tvOS 10.2, *)
let kVTDecompressionResolutionKey_Height: CFString
@available(tvOS 10.2, *)
let kVTDecompressionPropertyKey_ReducedCoefficientDecode: CFString
@available(tvOS 10.2, *)
let kVTDecompressionPropertyKey_ReducedFrameDelivery: CFString
@available(tvOS 10.2, *)
let kVTDecompressionPropertyKey_OnlyTheseFrames: CFString
@available(tvOS 10.2, *)
let kVTDecompressionProperty_OnlyTheseFrames_AllFrames: CFString
@available(tvOS 10.2, *)
let kVTDecompressionProperty_OnlyTheseFrames_NonDroppableFrames: CFString
@available(tvOS 10.2, *)
let kVTDecompressionProperty_OnlyTheseFrames_IFrames: CFString
@available(tvOS 10.2, *)
let kVTDecompressionProperty_OnlyTheseFrames_KeyFrames: CFString
@available(tvOS 10.4, *)
let kVTDecompressionProperty_TemporalLevelLimit: CFString
@available(tvOS 10.2, *)
let kVTDecompressionPropertyKey_SuggestedQualityOfServiceTiers: CFString
@available(tvOS 10.2, *)
let kVTDecompressionPropertyKey_SupportedPixelFormatsOrderedByQuality: CFString
@available(tvOS 10.2, *)
let kVTDecompressionPropertyKey_SupportedPixelFormatsOrderedByPerformance: CFString
@available(tvOS 10.2, *)
let kVTDecompressionPropertyKey_PixelFormatsWithReducedResolutionSupport: CFString
@available(tvOS 10.2, *)
let kVTDecompressionPropertyKey_PixelTransferProperties: CFString
let kVTVideoDecoderSpecification_RequiredDecoderGPURegistryID: CFString
let kVTVideoDecoderSpecification_PreferredDecoderGPURegistryID: CFString
let kVTDecompressionPropertyKey_UsingGPURegistryID: CFString
@available(tvOS 14.0, *)
let kVTDecompressionPropertyKey_PropagatePerFrameHDRDisplayMetadata: CFString
