
@available(macOS 10.6, *)
let kSecClass: CFString
@available(macOS 10.6, *)
let kSecClassInternetPassword: CFString
@available(macOS 10.7, *)
let kSecClassGenericPassword: CFString
@available(macOS 10.7, *)
let kSecClassCertificate: CFString
@available(macOS 10.7, *)
let kSecClassKey: CFString
@available(macOS 10.7, *)
let kSecClassIdentity: CFString
@available(macOS 10.9, *)
let kSecAttrAccessible: CFString
@available(macOS 10.7, *)
let kSecAttrAccess: CFString
@available(macOS 10.10, *)
let kSecAttrAccessControl: CFString
@available(macOS 10.9, *)
let kSecAttrAccessGroup: CFString
@available(macOS 10.9, *)
let kSecAttrSynchronizable: CFString
@available(macOS 10.9, *)
let kSecAttrSynchronizableAny: CFString
@available(macOS 10.6, *)
let kSecAttrCreationDate: CFString
@available(macOS 10.6, *)
let kSecAttrModificationDate: CFString
@available(macOS 10.6, *)
let kSecAttrDescription: CFString
@available(macOS 10.6, *)
let kSecAttrComment: CFString
@available(macOS 10.6, *)
let kSecAttrCreator: CFString
@available(macOS 10.6, *)
let kSecAttrType: CFString
@available(macOS 10.6, *)
let kSecAttrLabel: CFString
@available(macOS 10.6, *)
let kSecAttrIsInvisible: CFString
@available(macOS 10.6, *)
let kSecAttrIsNegative: CFString
@available(macOS 10.6, *)
let kSecAttrAccount: CFString
@available(macOS 10.6, *)
let kSecAttrService: CFString
@available(macOS 10.6, *)
let kSecAttrGeneric: CFString
@available(macOS 10.6, *)
let kSecAttrSecurityDomain: CFString
@available(macOS 10.6, *)
let kSecAttrServer: CFString
@available(macOS 10.6, *)
let kSecAttrProtocol: CFString
@available(macOS 10.6, *)
let kSecAttrAuthenticationType: CFString
@available(macOS 10.6, *)
let kSecAttrPort: CFString
@available(macOS 10.6, *)
let kSecAttrPath: CFString
@available(macOS 10.6, *)
let kSecAttrSubject: CFString
@available(macOS 10.6, *)
let kSecAttrIssuer: CFString
@available(macOS 10.6, *)
let kSecAttrSerialNumber: CFString
@available(macOS 10.6, *)
let kSecAttrSubjectKeyID: CFString
@available(macOS 10.6, *)
let kSecAttrPublicKeyHash: CFString
@available(macOS 10.6, *)
let kSecAttrCertificateType: CFString
@available(macOS 10.6, *)
let kSecAttrCertificateEncoding: CFString
@available(macOS 10.6, *)
let kSecAttrKeyClass: CFString
@available(macOS 10.6, *)
let kSecAttrApplicationLabel: CFString
@available(macOS 10.6, *)
let kSecAttrIsPermanent: CFString
@available(macOS 10.6, *)
let kSecAttrIsSensitive: CFString
@available(macOS 10.6, *)
let kSecAttrIsExtractable: CFString
@available(macOS 10.6, *)
let kSecAttrApplicationTag: CFString
@available(macOS 10.6, *)
let kSecAttrKeyType: CFString
@available(macOS 10.7, *)
let kSecAttrPRF: CFString
@available(macOS 10.7, *)
let kSecAttrSalt: CFString
@available(macOS 10.7, *)
let kSecAttrRounds: CFString
@available(macOS 10.6, *)
let kSecAttrKeySizeInBits: CFString
@available(macOS 10.6, *)
let kSecAttrEffectiveKeySize: CFString
@available(macOS 10.6, *)
let kSecAttrCanEncrypt: CFString
@available(macOS 10.6, *)
let kSecAttrCanDecrypt: CFString
@available(macOS 10.6, *)
let kSecAttrCanDerive: CFString
@available(macOS 10.6, *)
let kSecAttrCanSign: CFString
@available(macOS 10.6, *)
let kSecAttrCanVerify: CFString
@available(macOS 10.6, *)
let kSecAttrCanWrap: CFString
@available(macOS 10.6, *)
let kSecAttrCanUnwrap: CFString
@available(macOS 10.11, *)
let kSecAttrSyncViewHint: CFString
@available(macOS 10.12, *)
let kSecAttrTokenID: CFString
@available(macOS 10.13, *)
let kSecAttrPersistantReference: CFString
@available(macOS 10.13, *)
let kSecAttrPersistentReference: CFString
@available(macOS 10.9, *)
let kSecAttrAccessibleWhenUnlocked: CFString
@available(macOS 10.9, *)
let kSecAttrAccessibleAfterFirstUnlock: CFString
@available(macOS, introduced: 10.9, deprecated: 10.14, message: "Use an accessibility level that provides some user protection, such as kSecAttrAccessibleAfterFirstUnlock")
let kSecAttrAccessibleAlways: CFString
@available(macOS 10.10, *)
let kSecAttrAccessibleWhenPasscodeSetThisDeviceOnly: CFString
@available(macOS 10.9, *)
let kSecAttrAccessibleWhenUnlockedThisDeviceOnly: CFString
@available(macOS 10.9, *)
let kSecAttrAccessibleAfterFirstUnlockThisDeviceOnly: CFString
@available(macOS, introduced: 10.9, deprecated: 10.14, message: "Use an accessibility level that provides some user protection, such as kSecAttrAccessibleAfterFirstUnlockThisDeviceOnly")
let kSecAttrAccessibleAlwaysThisDeviceOnly: CFString
@available(macOS 10.6, *)
let kSecAttrProtocolFTP: CFString
@available(macOS 10.6, *)
let kSecAttrProtocolFTPAccount: CFString
@available(macOS 10.6, *)
let kSecAttrProtocolHTTP: CFString
@available(macOS 10.6, *)
let kSecAttrProtocolIRC: CFString
@available(macOS 10.6, *)
let kSecAttrProtocolNNTP: CFString
@available(macOS 10.6, *)
let kSecAttrProtocolPOP3: CFString
@available(macOS 10.6, *)
let kSecAttrProtocolSMTP: CFString
@available(macOS 10.6, *)
let kSecAttrProtocolSOCKS: CFString
@available(macOS 10.6, *)
let kSecAttrProtocolIMAP: CFString
@available(macOS 10.6, *)
let kSecAttrProtocolLDAP: CFString
@available(macOS 10.6, *)
let kSecAttrProtocolAppleTalk: CFString
@available(macOS 10.6, *)
let kSecAttrProtocolAFP: CFString
@available(macOS 10.6, *)
let kSecAttrProtocolTelnet: CFString
@available(macOS 10.6, *)
let kSecAttrProtocolSSH: CFString
@available(macOS 10.6, *)
let kSecAttrProtocolFTPS: CFString
@available(macOS 10.6, *)
let kSecAttrProtocolHTTPS: CFString
@available(macOS 10.6, *)
let kSecAttrProtocolHTTPProxy: CFString
@available(macOS 10.6, *)
let kSecAttrProtocolHTTPSProxy: CFString
@available(macOS 10.6, *)
let kSecAttrProtocolFTPProxy: CFString
@available(macOS 10.6, *)
let kSecAttrProtocolSMB: CFString
@available(macOS 10.6, *)
let kSecAttrProtocolRTSP: CFString
@available(macOS 10.6, *)
let kSecAttrProtocolRTSPProxy: CFString
@available(macOS 10.6, *)
let kSecAttrProtocolDAAP: CFString
@available(macOS 10.6, *)
let kSecAttrProtocolEPPC: CFString
@available(macOS 10.6, *)
let kSecAttrProtocolIPP: CFString
@available(macOS 10.6, *)
let kSecAttrProtocolNNTPS: CFString
@available(macOS 10.6, *)
let kSecAttrProtocolLDAPS: CFString
@available(macOS 10.6, *)
let kSecAttrProtocolTelnetS: CFString
@available(macOS 10.6, *)
let kSecAttrProtocolIMAPS: CFString
@available(macOS 10.6, *)
let kSecAttrProtocolIRCS: CFString
@available(macOS 10.6, *)
let kSecAttrProtocolPOP3S: CFString
@available(macOS 10.6, *)
let kSecAttrAuthenticationTypeNTLM: CFString
@available(macOS 10.6, *)
let kSecAttrAuthenticationTypeMSN: CFString
@available(macOS 10.6, *)
let kSecAttrAuthenticationTypeDPA: CFString
@available(macOS 10.6, *)
let kSecAttrAuthenticationTypeRPA: CFString
@available(macOS 10.6, *)
let kSecAttrAuthenticationTypeHTTPBasic: CFString
@available(macOS 10.6, *)
let kSecAttrAuthenticationTypeHTTPDigest: CFString
@available(macOS 10.6, *)
let kSecAttrAuthenticationTypeHTMLForm: CFString
@available(macOS 10.6, *)
let kSecAttrAuthenticationTypeDefault: CFString
@available(macOS 10.7, *)
let kSecAttrKeyClassPublic: CFString
@available(macOS 10.7, *)
let kSecAttrKeyClassPrivate: CFString
@available(macOS 10.7, *)
let kSecAttrKeyClassSymmetric: CFString
@available(macOS 10.7, *)
let kSecAttrKeyTypeRSA: CFString
@available(macOS 10.7, *)
let kSecAttrKeyTypeDSA: CFString
@available(macOS 10.7, *)
let kSecAttrKeyTypeAES: CFString
@available(macOS 10.7, *)
let kSecAttrKeyTypeDES: CFString
@available(macOS 10.7, *)
let kSecAttrKeyType3DES: CFString
@available(macOS 10.7, *)
let kSecAttrKeyTypeRC4: CFString
@available(macOS 10.7, *)
let kSecAttrKeyTypeRC2: CFString
@available(macOS 10.7, *)
let kSecAttrKeyTypeCAST: CFString
@available(macOS 10.7, *)
let kSecAttrKeyTypeECDSA: CFString
@available(macOS 10.9, *)
let kSecAttrKeyTypeEC: CFString
@available(macOS 10.12, *)
let kSecAttrKeyTypeECSECPrimeRandom: CFString
@available(macOS 10.7, *)
let kSecAttrPRFHmacAlgSHA1: CFString
@available(macOS 10.7, *)
let kSecAttrPRFHmacAlgSHA224: CFString
@available(macOS 10.7, *)
let kSecAttrPRFHmacAlgSHA256: CFString
@available(macOS 10.7, *)
let kSecAttrPRFHmacAlgSHA384: CFString
@available(macOS 10.7, *)
let kSecAttrPRFHmacAlgSHA512: CFString
@available(macOS 10.6, *)
let kSecMatchPolicy: CFString
@available(macOS 10.6, *)
let kSecMatchItemList: CFString
@available(macOS 10.6, *)
let kSecMatchSearchList: CFString
@available(macOS 10.6, *)
let kSecMatchIssuers: CFString
@available(macOS 10.6, *)
let kSecMatchEmailAddressIfPresent: CFString
@available(macOS 10.6, *)
let kSecMatchSubjectContains: CFString
@available(macOS 10.7, *)
let kSecMatchSubjectStartsWith: CFString
@available(macOS 10.7, *)
let kSecMatchSubjectEndsWith: CFString
@available(macOS 10.7, *)
let kSecMatchSubjectWholeString: CFString
@available(macOS 10.6, *)
let kSecMatchCaseInsensitive: CFString
@available(macOS 10.7, *)
let kSecMatchDiacriticInsensitive: CFString
@available(macOS 10.7, *)
let kSecMatchWidthInsensitive: CFString
@available(macOS 10.6, *)
let kSecMatchTrustedOnly: CFString
@available(macOS 10.6, *)
let kSecMatchValidOnDate: CFString
@available(macOS 10.6, *)
let kSecMatchLimit: CFString
@available(macOS 10.6, *)
let kSecMatchLimitOne: CFString
@available(macOS 10.6, *)
let kSecMatchLimitAll: CFString
@available(macOS 10.6, *)
let kSecReturnData: CFString
@available(macOS 10.6, *)
let kSecReturnAttributes: CFString
@available(macOS 10.6, *)
let kSecReturnRef: CFString
@available(macOS 10.6, *)
let kSecReturnPersistentRef: CFString
@available(macOS 10.6, *)
let kSecValueData: CFString
@available(macOS 10.6, *)
let kSecValueRef: CFString
@available(macOS 10.6, *)
let kSecValuePersistentRef: CFString
@available(macOS 10.6, *)
let kSecUseItemList: CFString
@available(macOS 10.7, *)
let kSecUseKeychain: CFString
@available(macOS, introduced: 10.10, deprecated: 11.0, message: "Use kSecUseAuthenticationContext and set LAContext.localizedReason property")
let kSecUseOperationPrompt: CFString
@available(macOS, introduced: 10.10, deprecated: 10.11, message: "Use kSecUseAuthenticationUI instead.")
let kSecUseNoAuthenticationUI: CFString
@available(macOS 10.11, *)
let kSecUseAuthenticationUI: CFString
@available(macOS 10.11, *)
let kSecUseAuthenticationContext: CFString
@available(macOS 10.15, *)
let kSecUseDataProtectionKeychain: CFString
@available(macOS, introduced: 10.11, deprecated: 11.0, message: "Instead of kSecUseAuthenticationUI, use kSecUseAuthenticationContext and set LAContext.interactionNotAllowed property")
let kSecUseAuthenticationUIAllow: CFString
@available(macOS, introduced: 10.11, deprecated: 11.0, message: "Instead of kSecUseAuthenticationUI, use kSecUseAuthenticationContext and set LAContext.interactionNotAllowed property")
let kSecUseAuthenticationUIFail: CFString
@available(macOS 10.11, *)
let kSecUseAuthenticationUISkip: CFString
@available(macOS 10.12, *)
let kSecAttrTokenIDSecureEnclave: CFString
@available(macOS 10.12, *)
let kSecAttrAccessGroupToken: CFString
@available(macOS 10.6, *)
func SecItemCopyMatching(_ query: CFDictionary, _ result: UnsafeMutablePointer<CFTypeRef?>?) -> OSStatus
@available(macOS 10.6, *)
func SecItemAdd(_ attributes: CFDictionary, _ result: UnsafeMutablePointer<CFTypeRef?>?) -> OSStatus
@available(macOS 10.6, *)
func SecItemUpdate(_ query: CFDictionary, _ attributesToUpdate: CFDictionary) -> OSStatus
@available(macOS 10.6, *)
func SecItemDelete(_ query: CFDictionary) -> OSStatus
