
@available(iOS 4.0, *)
let kCGImagePropertyTIFFDictionary: CFString
@available(iOS 4.0, *)
let kCGImagePropertyGIFDictionary: CFString
@available(iOS 4.0, *)
let kCGImagePropertyJFIFDictionary: CFString
@available(iOS 13.0, *)
let kCGImagePropertyHEICSDictionary: CFString
@available(iOS 4.0, *)
let kCGImagePropertyExifDictionary: CFString
@available(iOS 4.0, *)
let kCGImagePropertyPNGDictionary: CFString
@available(iOS 4.0, *)
let kCGImagePropertyIPTCDictionary: CFString
@available(iOS 4.0, *)
let kCGImagePropertyGPSDictionary: CFString
@available(iOS 4.0, *)
let kCGImagePropertyRawDictionary: CFString
@available(iOS 4.0, *)
let kCGImagePropertyCIFFDictionary: CFString
@available(iOS 4.0, *)
let kCGImagePropertyMakerCanonDictionary: CFString
@available(iOS 4.0, *)
let kCGImagePropertyMakerNikonDictionary: CFString
@available(iOS 4.0, *)
let kCGImagePropertyMakerMinoltaDictionary: CFString
@available(iOS 4.0, *)
let kCGImagePropertyMakerFujiDictionary: CFString
@available(iOS 4.0, *)
let kCGImagePropertyMakerOlympusDictionary: CFString
@available(iOS 4.0, *)
let kCGImagePropertyMakerPentaxDictionary: CFString
@available(iOS 4.0, *)
let kCGImageProperty8BIMDictionary: CFString
@available(iOS 4.0, *)
let kCGImagePropertyDNGDictionary: CFString
@available(iOS 4.0, *)
let kCGImagePropertyExifAuxDictionary: CFString
@available(iOS 11.3, *)
let kCGImagePropertyOpenEXRDictionary: CFString
@available(iOS 7.0, *)
let kCGImagePropertyMakerAppleDictionary: CFString
@available(iOS 11.0, *)
let kCGImagePropertyFileContentsDictionary: CFString
@available(iOS 14.0, *)
let kCGImagePropertyWebPDictionary: CFString
@available(iOS 4.0, *)
let kCGImagePropertyFileSize: CFString
@available(iOS 4.0, *)
let kCGImagePropertyPixelHeight: CFString
@available(iOS 4.0, *)
let kCGImagePropertyPixelWidth: CFString
@available(iOS 4.0, *)
let kCGImagePropertyDPIHeight: CFString
@available(iOS 4.0, *)
let kCGImagePropertyDPIWidth: CFString
@available(iOS 4.0, *)
let kCGImagePropertyDepth: CFString
@available(iOS 4.0, *)
let kCGImagePropertyOrientation: CFString
@available(iOS 4.0, *)
let kCGImagePropertyIsFloat: CFString
@available(iOS 4.0, *)
let kCGImagePropertyIsIndexed: CFString
@available(iOS 4.0, *)
let kCGImagePropertyHasAlpha: CFString
@available(iOS 4.0, *)
let kCGImagePropertyColorModel: CFString
@available(iOS 4.0, *)
let kCGImagePropertyProfileName: CFString
@available(iOS 11.0, *)
let kCGImagePropertyPrimaryImage: CFString
@available(iOS 4.0, *)
let kCGImagePropertyColorModelRGB: CFString
@available(iOS 4.0, *)
let kCGImagePropertyColorModelGray: CFString
@available(iOS 4.0, *)
let kCGImagePropertyColorModelCMYK: CFString
@available(iOS 4.0, *)
let kCGImagePropertyColorModelLab: CFString
@available(iOS 4.0, *)
let kCGImagePropertyTIFFCompression: CFString
@available(iOS 4.0, *)
let kCGImagePropertyTIFFPhotometricInterpretation: CFString
@available(iOS 4.0, *)
let kCGImagePropertyTIFFDocumentName: CFString
@available(iOS 4.0, *)
let kCGImagePropertyTIFFImageDescription: CFString
@available(iOS 4.0, *)
let kCGImagePropertyTIFFMake: CFString
@available(iOS 4.0, *)
let kCGImagePropertyTIFFModel: CFString
@available(iOS 4.0, *)
let kCGImagePropertyTIFFOrientation: CFString
@available(iOS 4.0, *)
let kCGImagePropertyTIFFXResolution: CFString
@available(iOS 4.0, *)
let kCGImagePropertyTIFFYResolution: CFString
@available(iOS 4.0, *)
let kCGImagePropertyTIFFResolutionUnit: CFString
@available(iOS 4.0, *)
let kCGImagePropertyTIFFSoftware: CFString
@available(iOS 4.0, *)
let kCGImagePropertyTIFFTransferFunction: CFString
@available(iOS 4.0, *)
let kCGImagePropertyTIFFDateTime: CFString
@available(iOS 4.0, *)
let kCGImagePropertyTIFFArtist: CFString
@available(iOS 4.0, *)
let kCGImagePropertyTIFFHostComputer: CFString
@available(iOS 4.0, *)
let kCGImagePropertyTIFFCopyright: CFString
@available(iOS 4.0, *)
let kCGImagePropertyTIFFWhitePoint: CFString
@available(iOS 4.0, *)
let kCGImagePropertyTIFFPrimaryChromaticities: CFString
@available(iOS 9.0, *)
let kCGImagePropertyTIFFTileWidth: CFString
@available(iOS 9.0, *)
let kCGImagePropertyTIFFTileLength: CFString
@available(iOS 4.0, *)
let kCGImagePropertyJFIFVersion: CFString
@available(iOS 4.0, *)
let kCGImagePropertyJFIFXDensity: CFString
@available(iOS 4.0, *)
let kCGImagePropertyJFIFYDensity: CFString
@available(iOS 4.0, *)
let kCGImagePropertyJFIFDensityUnit: CFString
@available(iOS 4.0, *)
let kCGImagePropertyJFIFIsProgressive: CFString
@available(iOS 13.0, *)
let kCGImagePropertyHEICSLoopCount: CFString
@available(iOS 13.0, *)
let kCGImagePropertyHEICSDelayTime: CFString
@available(iOS 13.0, *)
let kCGImagePropertyHEICSUnclampedDelayTime: CFString
@available(iOS 13.0, *)
let kCGImagePropertyHEICSCanvasPixelWidth: CFString
@available(iOS 13.0, *)
let kCGImagePropertyHEICSCanvasPixelHeight: CFString
@available(iOS 13.0, *)
let kCGImagePropertyHEICSFrameInfoArray: CFString
@available(iOS 4.0, *)
let kCGImagePropertyExifExposureTime: CFString
@available(iOS 4.0, *)
let kCGImagePropertyExifFNumber: CFString
@available(iOS 4.0, *)
let kCGImagePropertyExifExposureProgram: CFString
@available(iOS 4.0, *)
let kCGImagePropertyExifSpectralSensitivity: CFString
@available(iOS 4.0, *)
let kCGImagePropertyExifISOSpeedRatings: CFString
@available(iOS 4.0, *)
let kCGImagePropertyExifOECF: CFString
@available(iOS 7.0, *)
let kCGImagePropertyExifSensitivityType: CFString
@available(iOS 7.0, *)
let kCGImagePropertyExifStandardOutputSensitivity: CFString
@available(iOS 7.0, *)
let kCGImagePropertyExifRecommendedExposureIndex: CFString
@available(iOS 7.0, *)
let kCGImagePropertyExifISOSpeed: CFString
@available(iOS 7.0, *)
let kCGImagePropertyExifISOSpeedLatitudeyyy: CFString
@available(iOS 7.0, *)
let kCGImagePropertyExifISOSpeedLatitudezzz: CFString
@available(iOS 4.0, *)
let kCGImagePropertyExifVersion: CFString
@available(iOS 4.0, *)
let kCGImagePropertyExifDateTimeOriginal: CFString
@available(iOS 4.0, *)
let kCGImagePropertyExifDateTimeDigitized: CFString
@available(iOS 13.0, *)
let kCGImagePropertyExifOffsetTime: CFString
@available(iOS 13.0, *)
let kCGImagePropertyExifOffsetTimeOriginal: CFString
@available(iOS 13.0, *)
let kCGImagePropertyExifOffsetTimeDigitized: CFString
@available(iOS 4.0, *)
let kCGImagePropertyExifComponentsConfiguration: CFString
@available(iOS 4.0, *)
let kCGImagePropertyExifCompressedBitsPerPixel: CFString
@available(iOS 4.0, *)
let kCGImagePropertyExifShutterSpeedValue: CFString
@available(iOS 4.0, *)
let kCGImagePropertyExifApertureValue: CFString
@available(iOS 4.0, *)
let kCGImagePropertyExifBrightnessValue: CFString
@available(iOS 4.0, *)
let kCGImagePropertyExifExposureBiasValue: CFString
@available(iOS 4.0, *)
let kCGImagePropertyExifMaxApertureValue: CFString
@available(iOS 4.0, *)
let kCGImagePropertyExifSubjectDistance: CFString
@available(iOS 4.0, *)
let kCGImagePropertyExifMeteringMode: CFString
@available(iOS 4.0, *)
let kCGImagePropertyExifLightSource: CFString
@available(iOS 4.0, *)
let kCGImagePropertyExifFlash: CFString
@available(iOS 4.0, *)
let kCGImagePropertyExifFocalLength: CFString
@available(iOS 4.0, *)
let kCGImagePropertyExifSubjectArea: CFString
@available(iOS 4.0, *)
let kCGImagePropertyExifMakerNote: CFString
@available(iOS 4.0, *)
let kCGImagePropertyExifUserComment: CFString
@available(iOS 4.0, *)
let kCGImagePropertyExifSubsecTime: CFString
@available(iOS 10.0, *)
let kCGImagePropertyExifSubsecTimeOriginal: CFString
@available(iOS 4.0, *)
let kCGImagePropertyExifSubsecTimeDigitized: CFString
@available(iOS 4.0, *)
let kCGImagePropertyExifFlashPixVersion: CFString
@available(iOS 4.0, *)
let kCGImagePropertyExifColorSpace: CFString
@available(iOS 4.0, *)
let kCGImagePropertyExifPixelXDimension: CFString
@available(iOS 4.0, *)
let kCGImagePropertyExifPixelYDimension: CFString
@available(iOS 4.0, *)
let kCGImagePropertyExifRelatedSoundFile: CFString
@available(iOS 4.0, *)
let kCGImagePropertyExifFlashEnergy: CFString
@available(iOS 4.0, *)
let kCGImagePropertyExifSpatialFrequencyResponse: CFString
@available(iOS 4.0, *)
let kCGImagePropertyExifFocalPlaneXResolution: CFString
@available(iOS 4.0, *)
let kCGImagePropertyExifFocalPlaneYResolution: CFString
@available(iOS 4.0, *)
let kCGImagePropertyExifFocalPlaneResolutionUnit: CFString
@available(iOS 4.0, *)
let kCGImagePropertyExifSubjectLocation: CFString
@available(iOS 4.0, *)
let kCGImagePropertyExifExposureIndex: CFString
@available(iOS 4.0, *)
let kCGImagePropertyExifSensingMethod: CFString
@available(iOS 4.0, *)
let kCGImagePropertyExifFileSource: CFString
@available(iOS 4.0, *)
let kCGImagePropertyExifSceneType: CFString
@available(iOS 4.0, *)
let kCGImagePropertyExifCFAPattern: CFString
@available(iOS 4.0, *)
let kCGImagePropertyExifCustomRendered: CFString
@available(iOS 4.0, *)
let kCGImagePropertyExifExposureMode: CFString
@available(iOS 4.0, *)
let kCGImagePropertyExifWhiteBalance: CFString
@available(iOS 4.0, *)
let kCGImagePropertyExifDigitalZoomRatio: CFString
@available(iOS 4.0, *)
let kCGImagePropertyExifFocalLenIn35mmFilm: CFString
@available(iOS 4.0, *)
let kCGImagePropertyExifSceneCaptureType: CFString
@available(iOS 4.0, *)
let kCGImagePropertyExifGainControl: CFString
@available(iOS 4.0, *)
let kCGImagePropertyExifContrast: CFString
@available(iOS 4.0, *)
let kCGImagePropertyExifSaturation: CFString
@available(iOS 4.0, *)
let kCGImagePropertyExifSharpness: CFString
@available(iOS 4.0, *)
let kCGImagePropertyExifDeviceSettingDescription: CFString
@available(iOS 4.0, *)
let kCGImagePropertyExifSubjectDistRange: CFString
@available(iOS 4.0, *)
let kCGImagePropertyExifImageUniqueID: CFString
@available(iOS 5.0, *)
let kCGImagePropertyExifCameraOwnerName: CFString
@available(iOS 5.0, *)
let kCGImagePropertyExifBodySerialNumber: CFString
@available(iOS 5.0, *)
let kCGImagePropertyExifLensSpecification: CFString
@available(iOS 5.0, *)
let kCGImagePropertyExifLensMake: CFString
@available(iOS 5.0, *)
let kCGImagePropertyExifLensModel: CFString
@available(iOS 5.0, *)
let kCGImagePropertyExifLensSerialNumber: CFString
@available(iOS 4.0, *)
let kCGImagePropertyExifGamma: CFString
@available(iOS 13.1, *)
let kCGImagePropertyExifCompositeImage: CFString
@available(iOS 13.1, *)
let kCGImagePropertyExifSourceImageNumberOfCompositeImage: CFString
@available(iOS 13.1, *)
let kCGImagePropertyExifSourceExposureTimesOfCompositeImage: CFString
@available(iOS, introduced: 4.0, deprecated: 10.0, message: "No longer supported")
let kCGImagePropertyExifSubsecTimeOrginal: CFString
@available(iOS 4.0, *)
let kCGImagePropertyExifAuxLensInfo: CFString
@available(iOS 4.0, *)
let kCGImagePropertyExifAuxLensModel: CFString
@available(iOS 4.0, *)
let kCGImagePropertyExifAuxSerialNumber: CFString
@available(iOS 4.0, *)
let kCGImagePropertyExifAuxLensID: CFString
@available(iOS 4.0, *)
let kCGImagePropertyExifAuxLensSerialNumber: CFString
@available(iOS 4.0, *)
let kCGImagePropertyExifAuxImageNumber: CFString
@available(iOS 4.0, *)
let kCGImagePropertyExifAuxFlashCompensation: CFString
@available(iOS 4.0, *)
let kCGImagePropertyExifAuxOwnerName: CFString
@available(iOS 4.0, *)
let kCGImagePropertyExifAuxFirmware: CFString
@available(iOS 4.0, *)
let kCGImagePropertyGIFLoopCount: CFString
@available(iOS 4.0, *)
let kCGImagePropertyGIFDelayTime: CFString
@available(iOS 4.0, *)
let kCGImagePropertyGIFImageColorMap: CFString
@available(iOS 4.0, *)
let kCGImagePropertyGIFHasGlobalColorMap: CFString
@available(iOS 4.0, *)
let kCGImagePropertyGIFUnclampedDelayTime: CFString
@available(iOS 13.0, *)
let kCGImagePropertyGIFCanvasPixelWidth: CFString
@available(iOS 13.0, *)
let kCGImagePropertyGIFCanvasPixelHeight: CFString
@available(iOS 13.0, *)
let kCGImagePropertyGIFFrameInfoArray: CFString
@available(iOS 5.0, *)
let kCGImagePropertyPNGAuthor: CFString
@available(iOS 4.0, *)
let kCGImagePropertyPNGChromaticities: CFString
@available(iOS 12.0, *)
let kCGImagePropertyPNGComment: CFString
@available(iOS 5.0, *)
let kCGImagePropertyPNGCopyright: CFString
@available(iOS 5.0, *)
let kCGImagePropertyPNGCreationTime: CFString
@available(iOS 5.0, *)
let kCGImagePropertyPNGDescription: CFString
@available(iOS 12.0, *)
let kCGImagePropertyPNGDisclaimer: CFString
@available(iOS 4.0, *)
let kCGImagePropertyPNGGamma: CFString
@available(iOS 4.0, *)
let kCGImagePropertyPNGInterlaceType: CFString
@available(iOS 5.0, *)
let kCGImagePropertyPNGModificationTime: CFString
@available(iOS 5.0, *)
let kCGImagePropertyPNGSoftware: CFString
@available(iOS 12.0, *)
let kCGImagePropertyPNGSource: CFString
@available(iOS 4.0, *)
let kCGImagePropertyPNGsRGBIntent: CFString
@available(iOS 5.0, *)
let kCGImagePropertyPNGTitle: CFString
@available(iOS 12.0, *)
let kCGImagePropertyPNGWarning: CFString
@available(iOS 4.0, *)
let kCGImagePropertyPNGXPixelsPerMeter: CFString
@available(iOS 4.0, *)
let kCGImagePropertyPNGYPixelsPerMeter: CFString
@available(iOS 8.0, *)
let kCGImagePropertyAPNGLoopCount: CFString
@available(iOS 8.0, *)
let kCGImagePropertyAPNGDelayTime: CFString
@available(iOS 8.0, *)
let kCGImagePropertyAPNGUnclampedDelayTime: CFString
@available(iOS 13.0, *)
let kCGImagePropertyAPNGFrameInfoArray: CFString
@available(iOS 13.0, *)
let kCGImagePropertyAPNGCanvasPixelWidth: CFString
@available(iOS 13.0, *)
let kCGImagePropertyAPNGCanvasPixelHeight: CFString
@available(iOS 14.0, *)
let kCGImagePropertyWebPLoopCount: CFString
@available(iOS 14.0, *)
let kCGImagePropertyWebPDelayTime: CFString
@available(iOS 14.0, *)
let kCGImagePropertyWebPUnclampedDelayTime: CFString
@available(iOS 14.0, *)
let kCGImagePropertyWebPFrameInfoArray: CFString
@available(iOS 14.0, *)
let kCGImagePropertyWebPCanvasPixelWidth: CFString
@available(iOS 14.0, *)
let kCGImagePropertyWebPCanvasPixelHeight: CFString
@available(iOS 4.0, *)
let kCGImagePropertyGPSVersion: CFString
@available(iOS 4.0, *)
let kCGImagePropertyGPSLatitudeRef: CFString
@available(iOS 4.0, *)
let kCGImagePropertyGPSLatitude: CFString
@available(iOS 4.0, *)
let kCGImagePropertyGPSLongitudeRef: CFString
@available(iOS 4.0, *)
let kCGImagePropertyGPSLongitude: CFString
@available(iOS 4.0, *)
let kCGImagePropertyGPSAltitudeRef: CFString
@available(iOS 4.0, *)
let kCGImagePropertyGPSAltitude: CFString
@available(iOS 4.0, *)
let kCGImagePropertyGPSTimeStamp: CFString
@available(iOS 4.0, *)
let kCGImagePropertyGPSSatellites: CFString
@available(iOS 4.0, *)
let kCGImagePropertyGPSStatus: CFString
@available(iOS 4.0, *)
let kCGImagePropertyGPSMeasureMode: CFString
@available(iOS 4.0, *)
let kCGImagePropertyGPSDOP: CFString
@available(iOS 4.0, *)
let kCGImagePropertyGPSSpeedRef: CFString
@available(iOS 4.0, *)
let kCGImagePropertyGPSSpeed: CFString
@available(iOS 4.0, *)
let kCGImagePropertyGPSTrackRef: CFString
@available(iOS 4.0, *)
let kCGImagePropertyGPSTrack: CFString
@available(iOS 4.0, *)
let kCGImagePropertyGPSImgDirectionRef: CFString
@available(iOS 4.0, *)
let kCGImagePropertyGPSImgDirection: CFString
@available(iOS 4.0, *)
let kCGImagePropertyGPSMapDatum: CFString
@available(iOS 4.0, *)
let kCGImagePropertyGPSDestLatitudeRef: CFString
@available(iOS 4.0, *)
let kCGImagePropertyGPSDestLatitude: CFString
@available(iOS 4.0, *)
let kCGImagePropertyGPSDestLongitudeRef: CFString
@available(iOS 4.0, *)
let kCGImagePropertyGPSDestLongitude: CFString
@available(iOS 4.0, *)
let kCGImagePropertyGPSDestBearingRef: CFString
@available(iOS 4.0, *)
let kCGImagePropertyGPSDestBearing: CFString
@available(iOS 4.0, *)
let kCGImagePropertyGPSDestDistanceRef: CFString
@available(iOS 4.0, *)
let kCGImagePropertyGPSDestDistance: CFString
@available(iOS 4.0, *)
let kCGImagePropertyGPSProcessingMethod: CFString
@available(iOS 4.0, *)
let kCGImagePropertyGPSAreaInformation: CFString
@available(iOS 4.0, *)
let kCGImagePropertyGPSDateStamp: CFString
@available(iOS 4.0, *)
let kCGImagePropertyGPSDifferental: CFString
@available(iOS 8.0, *)
let kCGImagePropertyGPSHPositioningError: CFString
@available(iOS 4.0, *)
let kCGImagePropertyIPTCObjectTypeReference: CFString
@available(iOS 4.0, *)
let kCGImagePropertyIPTCObjectAttributeReference: CFString
@available(iOS 4.0, *)
let kCGImagePropertyIPTCObjectName: CFString
@available(iOS 4.0, *)
let kCGImagePropertyIPTCEditStatus: CFString
@available(iOS 4.0, *)
let kCGImagePropertyIPTCEditorialUpdate: CFString
@available(iOS 4.0, *)
let kCGImagePropertyIPTCUrgency: CFString
@available(iOS 4.0, *)
let kCGImagePropertyIPTCSubjectReference: CFString
@available(iOS 4.0, *)
let kCGImagePropertyIPTCCategory: CFString
@available(iOS 4.0, *)
let kCGImagePropertyIPTCSupplementalCategory: CFString
@available(iOS 4.0, *)
let kCGImagePropertyIPTCFixtureIdentifier: CFString
@available(iOS 4.0, *)
let kCGImagePropertyIPTCKeywords: CFString
@available(iOS 4.0, *)
let kCGImagePropertyIPTCContentLocationCode: CFString
@available(iOS 4.0, *)
let kCGImagePropertyIPTCContentLocationName: CFString
@available(iOS 4.0, *)
let kCGImagePropertyIPTCReleaseDate: CFString
@available(iOS 4.0, *)
let kCGImagePropertyIPTCReleaseTime: CFString
@available(iOS 4.0, *)
let kCGImagePropertyIPTCExpirationDate: CFString
@available(iOS 4.0, *)
let kCGImagePropertyIPTCExpirationTime: CFString
@available(iOS 4.0, *)
let kCGImagePropertyIPTCSpecialInstructions: CFString
@available(iOS 4.0, *)
let kCGImagePropertyIPTCActionAdvised: CFString
@available(iOS 4.0, *)
let kCGImagePropertyIPTCReferenceService: CFString
@available(iOS 4.0, *)
let kCGImagePropertyIPTCReferenceDate: CFString
@available(iOS 4.0, *)
let kCGImagePropertyIPTCReferenceNumber: CFString
@available(iOS 4.0, *)
let kCGImagePropertyIPTCDateCreated: CFString
@available(iOS 4.0, *)
let kCGImagePropertyIPTCTimeCreated: CFString
@available(iOS 4.0, *)
let kCGImagePropertyIPTCDigitalCreationDate: CFString
@available(iOS 4.0, *)
let kCGImagePropertyIPTCDigitalCreationTime: CFString
@available(iOS 4.0, *)
let kCGImagePropertyIPTCOriginatingProgram: CFString
@available(iOS 4.0, *)
let kCGImagePropertyIPTCProgramVersion: CFString
@available(iOS 4.0, *)
let kCGImagePropertyIPTCObjectCycle: CFString
@available(iOS 4.0, *)
let kCGImagePropertyIPTCByline: CFString
@available(iOS 4.0, *)
let kCGImagePropertyIPTCBylineTitle: CFString
@available(iOS 4.0, *)
let kCGImagePropertyIPTCCity: CFString
@available(iOS 4.0, *)
let kCGImagePropertyIPTCSubLocation: CFString
@available(iOS 4.0, *)
let kCGImagePropertyIPTCProvinceState: CFString
@available(iOS 4.0, *)
let kCGImagePropertyIPTCCountryPrimaryLocationCode: CFString
@available(iOS 4.0, *)
let kCGImagePropertyIPTCCountryPrimaryLocationName: CFString
@available(iOS 4.0, *)
let kCGImagePropertyIPTCOriginalTransmissionReference: CFString
@available(iOS 4.0, *)
let kCGImagePropertyIPTCHeadline: CFString
@available(iOS 4.0, *)
let kCGImagePropertyIPTCCredit: CFString
@available(iOS 4.0, *)
let kCGImagePropertyIPTCSource: CFString
@available(iOS 4.0, *)
let kCGImagePropertyIPTCCopyrightNotice: CFString
@available(iOS 4.0, *)
let kCGImagePropertyIPTCContact: CFString
@available(iOS 4.0, *)
let kCGImagePropertyIPTCCaptionAbstract: CFString
@available(iOS 4.0, *)
let kCGImagePropertyIPTCWriterEditor: CFString
@available(iOS 4.0, *)
let kCGImagePropertyIPTCImageType: CFString
@available(iOS 4.0, *)
let kCGImagePropertyIPTCImageOrientation: CFString
@available(iOS 4.0, *)
let kCGImagePropertyIPTCLanguageIdentifier: CFString
@available(iOS 4.0, *)
let kCGImagePropertyIPTCStarRating: CFString
@available(iOS 4.0, *)
let kCGImagePropertyIPTCCreatorContactInfo: CFString
@available(iOS 4.0, *)
let kCGImagePropertyIPTCRightsUsageTerms: CFString
@available(iOS 4.0, *)
let kCGImagePropertyIPTCScene: CFString
@available(iOS 11.3, *)
let kCGImagePropertyIPTCExtAboutCvTerm: CFString
@available(iOS 11.3, *)
let kCGImagePropertyIPTCExtAboutCvTermCvId: CFString
@available(iOS 11.3, *)
let kCGImagePropertyIPTCExtAboutCvTermId: CFString
@available(iOS 11.3, *)
let kCGImagePropertyIPTCExtAboutCvTermName: CFString
@available(iOS 11.3, *)
let kCGImagePropertyIPTCExtAboutCvTermRefinedAbout: CFString
@available(iOS 11.3, *)
let kCGImagePropertyIPTCExtAddlModelInfo: CFString
@available(iOS 11.3, *)
let kCGImagePropertyIPTCExtArtworkOrObject: CFString
@available(iOS 11.3, *)
let kCGImagePropertyIPTCExtArtworkCircaDateCreated: CFString
@available(iOS 11.3, *)
let kCGImagePropertyIPTCExtArtworkContentDescription: CFString
@available(iOS 11.3, *)
let kCGImagePropertyIPTCExtArtworkContributionDescription: CFString
@available(iOS 11.3, *)
let kCGImagePropertyIPTCExtArtworkCopyrightNotice: CFString
@available(iOS 11.3, *)
let kCGImagePropertyIPTCExtArtworkCreator: CFString
@available(iOS 11.3, *)
let kCGImagePropertyIPTCExtArtworkCreatorID: CFString
@available(iOS 11.3, *)
let kCGImagePropertyIPTCExtArtworkCopyrightOwnerID: CFString
@available(iOS 11.3, *)
let kCGImagePropertyIPTCExtArtworkCopyrightOwnerName: CFString
@available(iOS 11.3, *)
let kCGImagePropertyIPTCExtArtworkLicensorID: CFString
@available(iOS 11.3, *)
let kCGImagePropertyIPTCExtArtworkLicensorName: CFString
@available(iOS 11.3, *)
let kCGImagePropertyIPTCExtArtworkDateCreated: CFString
@available(iOS 11.3, *)
let kCGImagePropertyIPTCExtArtworkPhysicalDescription: CFString
@available(iOS 11.3, *)
let kCGImagePropertyIPTCExtArtworkSource: CFString
@available(iOS 11.3, *)
let kCGImagePropertyIPTCExtArtworkSourceInventoryNo: CFString
@available(iOS 11.3, *)
let kCGImagePropertyIPTCExtArtworkSourceInvURL: CFString
@available(iOS 11.3, *)
let kCGImagePropertyIPTCExtArtworkStylePeriod: CFString
@available(iOS 11.3, *)
let kCGImagePropertyIPTCExtArtworkTitle: CFString
@available(iOS 11.3, *)
let kCGImagePropertyIPTCExtAudioBitrate: CFString
@available(iOS 11.3, *)
let kCGImagePropertyIPTCExtAudioBitrateMode: CFString
@available(iOS 11.3, *)
let kCGImagePropertyIPTCExtAudioChannelCount: CFString
@available(iOS 11.3, *)
let kCGImagePropertyIPTCExtCircaDateCreated: CFString
@available(iOS 11.3, *)
let kCGImagePropertyIPTCExtContainerFormat: CFString
@available(iOS 11.3, *)
let kCGImagePropertyIPTCExtContainerFormatIdentifier: CFString
@available(iOS 11.3, *)
let kCGImagePropertyIPTCExtContainerFormatName: CFString
@available(iOS 11.3, *)
let kCGImagePropertyIPTCExtContributor: CFString
@available(iOS 11.3, *)
let kCGImagePropertyIPTCExtContributorIdentifier: CFString
@available(iOS 11.3, *)
let kCGImagePropertyIPTCExtContributorName: CFString
@available(iOS 11.3, *)
let kCGImagePropertyIPTCExtContributorRole: CFString
@available(iOS 11.3, *)
let kCGImagePropertyIPTCExtCopyrightYear: CFString
@available(iOS 11.3, *)
let kCGImagePropertyIPTCExtCreator: CFString
@available(iOS 11.3, *)
let kCGImagePropertyIPTCExtCreatorIdentifier: CFString
@available(iOS 11.3, *)
let kCGImagePropertyIPTCExtCreatorName: CFString
@available(iOS 11.3, *)
let kCGImagePropertyIPTCExtCreatorRole: CFString
@available(iOS 11.3, *)
let kCGImagePropertyIPTCExtControlledVocabularyTerm: CFString
@available(iOS 11.3, *)
let kCGImagePropertyIPTCExtDataOnScreen: CFString
@available(iOS 11.3, *)
let kCGImagePropertyIPTCExtDataOnScreenRegion: CFString
@available(iOS 11.3, *)
let kCGImagePropertyIPTCExtDataOnScreenRegionD: CFString
@available(iOS 11.3, *)
let kCGImagePropertyIPTCExtDataOnScreenRegionH: CFString
@available(iOS 11.3, *)
let kCGImagePropertyIPTCExtDataOnScreenRegionText: CFString
@available(iOS 11.3, *)
let kCGImagePropertyIPTCExtDataOnScreenRegionUnit: CFString
@available(iOS 11.3, *)
let kCGImagePropertyIPTCExtDataOnScreenRegionW: CFString
@available(iOS 11.3, *)
let kCGImagePropertyIPTCExtDataOnScreenRegionX: CFString
@available(iOS 11.3, *)
let kCGImagePropertyIPTCExtDataOnScreenRegionY: CFString
@available(iOS 11.3, *)
let kCGImagePropertyIPTCExtDigitalImageGUID: CFString
@available(iOS 11.3, *)
let kCGImagePropertyIPTCExtDigitalSourceFileType: CFString
@available(iOS 11.3, *)
let kCGImagePropertyIPTCExtDigitalSourceType: CFString
@available(iOS 11.3, *)
let kCGImagePropertyIPTCExtDopesheet: CFString
@available(iOS 11.3, *)
let kCGImagePropertyIPTCExtDopesheetLink: CFString
@available(iOS 11.3, *)
let kCGImagePropertyIPTCExtDopesheetLinkLink: CFString
@available(iOS 11.3, *)
let kCGImagePropertyIPTCExtDopesheetLinkLinkQualifier: CFString
@available(iOS 11.3, *)
let kCGImagePropertyIPTCExtEmbdEncRightsExpr: CFString
@available(iOS 11.3, *)
let kCGImagePropertyIPTCExtEmbeddedEncodedRightsExpr: CFString
@available(iOS 11.3, *)
let kCGImagePropertyIPTCExtEmbeddedEncodedRightsExprType: CFString
@available(iOS 11.3, *)
let kCGImagePropertyIPTCExtEmbeddedEncodedRightsExprLangID: CFString
@available(iOS 11.3, *)
let kCGImagePropertyIPTCExtEpisode: CFString
@available(iOS 11.3, *)
let kCGImagePropertyIPTCExtEpisodeIdentifier: CFString
@available(iOS 11.3, *)
let kCGImagePropertyIPTCExtEpisodeName: CFString
@available(iOS 11.3, *)
let kCGImagePropertyIPTCExtEpisodeNumber: CFString
@available(iOS 11.3, *)
let kCGImagePropertyIPTCExtEvent: CFString
@available(iOS 11.3, *)
let kCGImagePropertyIPTCExtShownEvent: CFString
@available(iOS 11.3, *)
let kCGImagePropertyIPTCExtShownEventIdentifier: CFString
@available(iOS 11.3, *)
let kCGImagePropertyIPTCExtShownEventName: CFString
@available(iOS 11.3, *)
let kCGImagePropertyIPTCExtExternalMetadataLink: CFString
@available(iOS 11.3, *)
let kCGImagePropertyIPTCExtFeedIdentifier: CFString
@available(iOS 11.3, *)
let kCGImagePropertyIPTCExtGenre: CFString
@available(iOS 11.3, *)
let kCGImagePropertyIPTCExtGenreCvId: CFString
@available(iOS 11.3, *)
let kCGImagePropertyIPTCExtGenreCvTermId: CFString
@available(iOS 11.3, *)
let kCGImagePropertyIPTCExtGenreCvTermName: CFString
@available(iOS 11.3, *)
let kCGImagePropertyIPTCExtGenreCvTermRefinedAbout: CFString
@available(iOS 11.3, *)
let kCGImagePropertyIPTCExtHeadline: CFString
@available(iOS 11.3, *)
let kCGImagePropertyIPTCExtIPTCLastEdited: CFString
@available(iOS 11.3, *)
let kCGImagePropertyIPTCExtLinkedEncRightsExpr: CFString
@available(iOS 11.3, *)
let kCGImagePropertyIPTCExtLinkedEncodedRightsExpr: CFString
@available(iOS 11.3, *)
let kCGImagePropertyIPTCExtLinkedEncodedRightsExprType: CFString
@available(iOS 11.3, *)
let kCGImagePropertyIPTCExtLinkedEncodedRightsExprLangID: CFString
@available(iOS 11.3, *)
let kCGImagePropertyIPTCExtLocationCreated: CFString
@available(iOS 11.3, *)
let kCGImagePropertyIPTCExtLocationCity: CFString
@available(iOS 11.3, *)
let kCGImagePropertyIPTCExtLocationCountryCode: CFString
@available(iOS 11.3, *)
let kCGImagePropertyIPTCExtLocationCountryName: CFString
@available(iOS 11.3, *)
let kCGImagePropertyIPTCExtLocationGPSAltitude: CFString
@available(iOS 11.3, *)
let kCGImagePropertyIPTCExtLocationGPSLatitude: CFString
@available(iOS 11.3, *)
let kCGImagePropertyIPTCExtLocationGPSLongitude: CFString
@available(iOS 11.3, *)
let kCGImagePropertyIPTCExtLocationIdentifier: CFString
@available(iOS 11.3, *)
let kCGImagePropertyIPTCExtLocationLocationId: CFString
@available(iOS 11.3, *)
let kCGImagePropertyIPTCExtLocationLocationName: CFString
@available(iOS 11.3, *)
let kCGImagePropertyIPTCExtLocationProvinceState: CFString
@available(iOS 11.3, *)
let kCGImagePropertyIPTCExtLocationSublocation: CFString
@available(iOS 11.3, *)
let kCGImagePropertyIPTCExtLocationWorldRegion: CFString
@available(iOS 11.3, *)
let kCGImagePropertyIPTCExtLocationShown: CFString
@available(iOS 11.3, *)
let kCGImagePropertyIPTCExtMaxAvailHeight: CFString
@available(iOS 11.3, *)
let kCGImagePropertyIPTCExtMaxAvailWidth: CFString
@available(iOS 11.3, *)
let kCGImagePropertyIPTCExtModelAge: CFString
@available(iOS 11.3, *)
let kCGImagePropertyIPTCExtOrganisationInImageCode: CFString
@available(iOS 11.3, *)
let kCGImagePropertyIPTCExtOrganisationInImageName: CFString
@available(iOS 11.3, *)
let kCGImagePropertyIPTCExtPersonHeard: CFString
@available(iOS 11.3, *)
let kCGImagePropertyIPTCExtPersonHeardIdentifier: CFString
@available(iOS 11.3, *)
let kCGImagePropertyIPTCExtPersonHeardName: CFString
@available(iOS 11.3, *)
let kCGImagePropertyIPTCExtPersonInImage: CFString
@available(iOS 11.3, *)
let kCGImagePropertyIPTCExtPersonInImageWDetails: CFString
@available(iOS 11.3, *)
let kCGImagePropertyIPTCExtPersonInImageCharacteristic: CFString
@available(iOS 11.3, *)
let kCGImagePropertyIPTCExtPersonInImageCvTermCvId: CFString
@available(iOS 11.3, *)
let kCGImagePropertyIPTCExtPersonInImageCvTermId: CFString
@available(iOS 11.3, *)
let kCGImagePropertyIPTCExtPersonInImageCvTermName: CFString
@available(iOS 11.3, *)
let kCGImagePropertyIPTCExtPersonInImageCvTermRefinedAbout: CFString
@available(iOS 11.3, *)
let kCGImagePropertyIPTCExtPersonInImageDescription: CFString
@available(iOS 11.3, *)
let kCGImagePropertyIPTCExtPersonInImageId: CFString
@available(iOS 11.3, *)
let kCGImagePropertyIPTCExtPersonInImageName: CFString
@available(iOS 11.3, *)
let kCGImagePropertyIPTCExtProductInImage: CFString
@available(iOS 11.3, *)
let kCGImagePropertyIPTCExtProductInImageDescription: CFString
@available(iOS 11.3, *)
let kCGImagePropertyIPTCExtProductInImageGTIN: CFString
@available(iOS 11.3, *)
let kCGImagePropertyIPTCExtProductInImageName: CFString
@available(iOS 11.3, *)
let kCGImagePropertyIPTCExtPublicationEvent: CFString
@available(iOS 11.3, *)
let kCGImagePropertyIPTCExtPublicationEventDate: CFString
@available(iOS 11.3, *)
let kCGImagePropertyIPTCExtPublicationEventIdentifier: CFString
@available(iOS 11.3, *)
let kCGImagePropertyIPTCExtPublicationEventName: CFString
@available(iOS 11.3, *)
let kCGImagePropertyIPTCExtRating: CFString
@available(iOS 11.3, *)
let kCGImagePropertyIPTCExtRatingRatingRegion: CFString
@available(iOS 11.3, *)
let kCGImagePropertyIPTCExtRatingRegionCity: CFString
@available(iOS 11.3, *)
let kCGImagePropertyIPTCExtRatingRegionCountryCode: CFString
@available(iOS 11.3, *)
let kCGImagePropertyIPTCExtRatingRegionCountryName: CFString
@available(iOS 11.3, *)
let kCGImagePropertyIPTCExtRatingRegionGPSAltitude: CFString
@available(iOS 11.3, *)
let kCGImagePropertyIPTCExtRatingRegionGPSLatitude: CFString
@available(iOS 11.3, *)
let kCGImagePropertyIPTCExtRatingRegionGPSLongitude: CFString
@available(iOS 11.3, *)
let kCGImagePropertyIPTCExtRatingRegionIdentifier: CFString
@available(iOS 11.3, *)
let kCGImagePropertyIPTCExtRatingRegionLocationId: CFString
@available(iOS 11.3, *)
let kCGImagePropertyIPTCExtRatingRegionLocationName: CFString
@available(iOS 11.3, *)
let kCGImagePropertyIPTCExtRatingRegionProvinceState: CFString
@available(iOS 11.3, *)
let kCGImagePropertyIPTCExtRatingRegionSublocation: CFString
@available(iOS 11.3, *)
let kCGImagePropertyIPTCExtRatingRegionWorldRegion: CFString
@available(iOS 11.3, *)
let kCGImagePropertyIPTCExtRatingScaleMaxValue: CFString
@available(iOS 11.3, *)
let kCGImagePropertyIPTCExtRatingScaleMinValue: CFString
@available(iOS 11.3, *)
let kCGImagePropertyIPTCExtRatingSourceLink: CFString
@available(iOS 11.3, *)
let kCGImagePropertyIPTCExtRatingValue: CFString
@available(iOS 11.3, *)
let kCGImagePropertyIPTCExtRatingValueLogoLink: CFString
@available(iOS 11.3, *)
let kCGImagePropertyIPTCExtRegistryID: CFString
@available(iOS 11.3, *)
let kCGImagePropertyIPTCExtRegistryEntryRole: CFString
@available(iOS 11.3, *)
let kCGImagePropertyIPTCExtRegistryItemID: CFString
@available(iOS 11.3, *)
let kCGImagePropertyIPTCExtRegistryOrganisationID: CFString
@available(iOS 11.3, *)
let kCGImagePropertyIPTCExtReleaseReady: CFString
@available(iOS 11.3, *)
let kCGImagePropertyIPTCExtSeason: CFString
@available(iOS 11.3, *)
let kCGImagePropertyIPTCExtSeasonIdentifier: CFString
@available(iOS 11.3, *)
let kCGImagePropertyIPTCExtSeasonName: CFString
@available(iOS 11.3, *)
let kCGImagePropertyIPTCExtSeasonNumber: CFString
@available(iOS 11.3, *)
let kCGImagePropertyIPTCExtSeries: CFString
@available(iOS 11.3, *)
let kCGImagePropertyIPTCExtSeriesIdentifier: CFString
@available(iOS 11.3, *)
let kCGImagePropertyIPTCExtSeriesName: CFString
@available(iOS 11.3, *)
let kCGImagePropertyIPTCExtStorylineIdentifier: CFString
@available(iOS 11.3, *)
let kCGImagePropertyIPTCExtStreamReady: CFString
@available(iOS 11.3, *)
let kCGImagePropertyIPTCExtStylePeriod: CFString
@available(iOS 11.3, *)
let kCGImagePropertyIPTCExtSupplyChainSource: CFString
@available(iOS 11.3, *)
let kCGImagePropertyIPTCExtSupplyChainSourceIdentifier: CFString
@available(iOS 11.3, *)
let kCGImagePropertyIPTCExtSupplyChainSourceName: CFString
@available(iOS 11.3, *)
let kCGImagePropertyIPTCExtTemporalCoverage: CFString
@available(iOS 11.3, *)
let kCGImagePropertyIPTCExtTemporalCoverageFrom: CFString
@available(iOS 11.3, *)
let kCGImagePropertyIPTCExtTemporalCoverageTo: CFString
@available(iOS 11.3, *)
let kCGImagePropertyIPTCExtTranscript: CFString
@available(iOS 11.3, *)
let kCGImagePropertyIPTCExtTranscriptLink: CFString
@available(iOS 11.3, *)
let kCGImagePropertyIPTCExtTranscriptLinkLink: CFString
@available(iOS 11.3, *)
let kCGImagePropertyIPTCExtTranscriptLinkLinkQualifier: CFString
@available(iOS 11.3, *)
let kCGImagePropertyIPTCExtVideoBitrate: CFString
@available(iOS 11.3, *)
let kCGImagePropertyIPTCExtVideoBitrateMode: CFString
@available(iOS 11.3, *)
let kCGImagePropertyIPTCExtVideoDisplayAspectRatio: CFString
@available(iOS 11.3, *)
let kCGImagePropertyIPTCExtVideoEncodingProfile: CFString
@available(iOS 11.3, *)
let kCGImagePropertyIPTCExtVideoShotType: CFString
@available(iOS 11.3, *)
let kCGImagePropertyIPTCExtVideoShotTypeIdentifier: CFString
@available(iOS 11.3, *)
let kCGImagePropertyIPTCExtVideoShotTypeName: CFString
@available(iOS 11.3, *)
let kCGImagePropertyIPTCExtVideoStreamsCount: CFString
@available(iOS 11.3, *)
let kCGImagePropertyIPTCExtVisualColor: CFString
@available(iOS 11.3, *)
let kCGImagePropertyIPTCExtWorkflowTag: CFString
@available(iOS 11.3, *)
let kCGImagePropertyIPTCExtWorkflowTagCvId: CFString
@available(iOS 11.3, *)
let kCGImagePropertyIPTCExtWorkflowTagCvTermId: CFString
@available(iOS 11.3, *)
let kCGImagePropertyIPTCExtWorkflowTagCvTermName: CFString
@available(iOS 11.3, *)
let kCGImagePropertyIPTCExtWorkflowTagCvTermRefinedAbout: CFString
@available(iOS 4.0, *)
let kCGImagePropertyIPTCContactInfoCity: CFString
@available(iOS 4.0, *)
let kCGImagePropertyIPTCContactInfoCountry: CFString
@available(iOS 4.0, *)
let kCGImagePropertyIPTCContactInfoAddress: CFString
@available(iOS 4.0, *)
let kCGImagePropertyIPTCContactInfoPostalCode: CFString
@available(iOS 4.0, *)
let kCGImagePropertyIPTCContactInfoStateProvince: CFString
@available(iOS 4.0, *)
let kCGImagePropertyIPTCContactInfoEmails: CFString
@available(iOS 4.0, *)
let kCGImagePropertyIPTCContactInfoPhones: CFString
@available(iOS 4.0, *)
let kCGImagePropertyIPTCContactInfoWebURLs: CFString
@available(iOS 4.0, *)
let kCGImageProperty8BIMLayerNames: CFString
@available(iOS 8.0, *)
let kCGImageProperty8BIMVersion: CFString
@available(iOS 4.0, *)
let kCGImagePropertyDNGVersion: CFString
@available(iOS 4.0, *)
let kCGImagePropertyDNGBackwardVersion: CFString
@available(iOS 4.0, *)
let kCGImagePropertyDNGUniqueCameraModel: CFString
@available(iOS 4.0, *)
let kCGImagePropertyDNGLocalizedCameraModel: CFString
@available(iOS 4.0, *)
let kCGImagePropertyDNGCameraSerialNumber: CFString
@available(iOS 4.0, *)
let kCGImagePropertyDNGLensInfo: CFString
@available(iOS 10.0, *)
let kCGImagePropertyDNGBlackLevel: CFString
@available(iOS 10.0, *)
let kCGImagePropertyDNGWhiteLevel: CFString
@available(iOS 10.0, *)
let kCGImagePropertyDNGCalibrationIlluminant1: CFString
@available(iOS 10.0, *)
let kCGImagePropertyDNGCalibrationIlluminant2: CFString
@available(iOS 10.0, *)
let kCGImagePropertyDNGColorMatrix1: CFString
@available(iOS 10.0, *)
let kCGImagePropertyDNGColorMatrix2: CFString
@available(iOS 10.0, *)
let kCGImagePropertyDNGCameraCalibration1: CFString
@available(iOS 10.0, *)
let kCGImagePropertyDNGCameraCalibration2: CFString
@available(iOS 10.0, *)
let kCGImagePropertyDNGAsShotNeutral: CFString
@available(iOS 10.0, *)
let kCGImagePropertyDNGAsShotWhiteXY: CFString
@available(iOS 10.0, *)
let kCGImagePropertyDNGBaselineExposure: CFString
@available(iOS 10.0, *)
let kCGImagePropertyDNGBaselineNoise: CFString
@available(iOS 10.0, *)
let kCGImagePropertyDNGBaselineSharpness: CFString
@available(iOS 10.0, *)
let kCGImagePropertyDNGPrivateData: CFString
@available(iOS 10.0, *)
let kCGImagePropertyDNGCameraCalibrationSignature: CFString
@available(iOS 10.0, *)
let kCGImagePropertyDNGProfileCalibrationSignature: CFString
@available(iOS 10.0, *)
let kCGImagePropertyDNGNoiseProfile: CFString
@available(iOS 10.0, *)
let kCGImagePropertyDNGWarpRectilinear: CFString
@available(iOS 10.0, *)
let kCGImagePropertyDNGWarpFisheye: CFString
@available(iOS 10.0, *)
let kCGImagePropertyDNGFixVignetteRadial: CFString
@available(iOS 12.0, *)
let kCGImagePropertyDNGActiveArea: CFString
@available(iOS 12.0, *)
let kCGImagePropertyDNGAnalogBalance: CFString
@available(iOS 12.0, *)
let kCGImagePropertyDNGAntiAliasStrength: CFString
@available(iOS 12.0, *)
let kCGImagePropertyDNGAsShotICCProfile: CFString
@available(iOS 12.0, *)
let kCGImagePropertyDNGAsShotPreProfileMatrix: CFString
@available(iOS 12.0, *)
let kCGImagePropertyDNGAsShotProfileName: CFString
@available(iOS 12.0, *)
let kCGImagePropertyDNGBaselineExposureOffset: CFString
@available(iOS 12.0, *)
let kCGImagePropertyDNGBayerGreenSplit: CFString
@available(iOS 12.0, *)
let kCGImagePropertyDNGBestQualityScale: CFString
@available(iOS 12.0, *)
let kCGImagePropertyDNGBlackLevelDeltaH: CFString
@available(iOS 12.0, *)
let kCGImagePropertyDNGBlackLevelDeltaV: CFString
@available(iOS 12.0, *)
let kCGImagePropertyDNGBlackLevelRepeatDim: CFString
@available(iOS 12.0, *)
let kCGImagePropertyDNGCFALayout: CFString
@available(iOS 12.0, *)
let kCGImagePropertyDNGCFAPlaneColor: CFString
@available(iOS 12.0, *)
let kCGImagePropertyDNGChromaBlurRadius: CFString
@available(iOS 12.0, *)
let kCGImagePropertyDNGColorimetricReference: CFString
@available(iOS 12.0, *)
let kCGImagePropertyDNGCurrentICCProfile: CFString
@available(iOS 12.0, *)
let kCGImagePropertyDNGCurrentPreProfileMatrix: CFString
@available(iOS 12.0, *)
let kCGImagePropertyDNGDefaultBlackRender: CFString
@available(iOS 12.0, *)
let kCGImagePropertyDNGDefaultCropOrigin: CFString
@available(iOS 12.0, *)
let kCGImagePropertyDNGDefaultCropSize: CFString
@available(iOS 12.0, *)
let kCGImagePropertyDNGDefaultScale: CFString
@available(iOS 12.0, *)
let kCGImagePropertyDNGDefaultUserCrop: CFString
@available(iOS 12.0, *)
let kCGImagePropertyDNGExtraCameraProfiles: CFString
@available(iOS 12.0, *)
let kCGImagePropertyDNGForwardMatrix1: CFString
@available(iOS 12.0, *)
let kCGImagePropertyDNGForwardMatrix2: CFString
@available(iOS 12.0, *)
let kCGImagePropertyDNGLinearizationTable: CFString
@available(iOS 12.0, *)
let kCGImagePropertyDNGLinearResponseLimit: CFString
@available(iOS 12.0, *)
let kCGImagePropertyDNGMakerNoteSafety: CFString
@available(iOS 12.0, *)
let kCGImagePropertyDNGMaskedAreas: CFString
@available(iOS 12.0, *)
let kCGImagePropertyDNGNewRawImageDigest: CFString
@available(iOS 12.0, *)
let kCGImagePropertyDNGNoiseReductionApplied: CFString
@available(iOS 12.0, *)
let kCGImagePropertyDNGOpcodeList1: CFString
@available(iOS 12.0, *)
let kCGImagePropertyDNGOpcodeList2: CFString
@available(iOS 12.0, *)
let kCGImagePropertyDNGOpcodeList3: CFString
@available(iOS 12.0, *)
let kCGImagePropertyDNGOriginalBestQualityFinalSize: CFString
@available(iOS 12.0, *)
let kCGImagePropertyDNGOriginalDefaultCropSize: CFString
@available(iOS 12.0, *)
let kCGImagePropertyDNGOriginalDefaultFinalSize: CFString
@available(iOS 12.0, *)
let kCGImagePropertyDNGOriginalRawFileData: CFString
@available(iOS 12.0, *)
let kCGImagePropertyDNGOriginalRawFileDigest: CFString
@available(iOS 12.0, *)
let kCGImagePropertyDNGOriginalRawFileName: CFString
@available(iOS 12.0, *)
let kCGImagePropertyDNGPreviewApplicationName: CFString
@available(iOS 12.0, *)
let kCGImagePropertyDNGPreviewApplicationVersion: CFString
@available(iOS 12.0, *)
let kCGImagePropertyDNGPreviewColorSpace: CFString
@available(iOS 12.0, *)
let kCGImagePropertyDNGPreviewDateTime: CFString
@available(iOS 12.0, *)
let kCGImagePropertyDNGPreviewSettingsDigest: CFString
@available(iOS 12.0, *)
let kCGImagePropertyDNGPreviewSettingsName: CFString
@available(iOS 12.0, *)
let kCGImagePropertyDNGProfileCopyright: CFString
@available(iOS 12.0, *)
let kCGImagePropertyDNGProfileEmbedPolicy: CFString
@available(iOS 12.0, *)
let kCGImagePropertyDNGProfileHueSatMapData1: CFString
@available(iOS 12.0, *)
let kCGImagePropertyDNGProfileHueSatMapData2: CFString
@available(iOS 12.0, *)
let kCGImagePropertyDNGProfileHueSatMapDims: CFString
@available(iOS 12.0, *)
let kCGImagePropertyDNGProfileHueSatMapEncoding: CFString
@available(iOS 12.0, *)
let kCGImagePropertyDNGProfileLookTableData: CFString
@available(iOS 12.0, *)
let kCGImagePropertyDNGProfileLookTableDims: CFString
@available(iOS 12.0, *)
let kCGImagePropertyDNGProfileLookTableEncoding: CFString
@available(iOS 12.0, *)
let kCGImagePropertyDNGProfileName: CFString
@available(iOS 12.0, *)
let kCGImagePropertyDNGProfileToneCurve: CFString
@available(iOS 12.0, *)
let kCGImagePropertyDNGRawDataUniqueID: CFString
@available(iOS 12.0, *)
let kCGImagePropertyDNGRawImageDigest: CFString
@available(iOS 12.0, *)
let kCGImagePropertyDNGRawToPreviewGain: CFString
@available(iOS 12.0, *)
let kCGImagePropertyDNGReductionMatrix1: CFString
@available(iOS 12.0, *)
let kCGImagePropertyDNGReductionMatrix2: CFString
@available(iOS 12.0, *)
let kCGImagePropertyDNGRowInterleaveFactor: CFString
@available(iOS 12.0, *)
let kCGImagePropertyDNGShadowScale: CFString
@available(iOS 12.0, *)
let kCGImagePropertyDNGSubTileBlockSize: CFString
@available(iOS 4.0, *)
let kCGImagePropertyCIFFDescription: CFString
@available(iOS 4.0, *)
let kCGImagePropertyCIFFFirmware: CFString
@available(iOS 4.0, *)
let kCGImagePropertyCIFFOwnerName: CFString
@available(iOS 4.0, *)
let kCGImagePropertyCIFFImageName: CFString
@available(iOS 4.0, *)
let kCGImagePropertyCIFFImageFileName: CFString
@available(iOS 4.0, *)
let kCGImagePropertyCIFFReleaseMethod: CFString
@available(iOS 4.0, *)
let kCGImagePropertyCIFFReleaseTiming: CFString
@available(iOS 4.0, *)
let kCGImagePropertyCIFFRecordID: CFString
@available(iOS 4.0, *)
let kCGImagePropertyCIFFSelfTimingTime: CFString
@available(iOS 4.0, *)
let kCGImagePropertyCIFFCameraSerialNumber: CFString
@available(iOS 4.0, *)
let kCGImagePropertyCIFFImageSerialNumber: CFString
@available(iOS 4.0, *)
let kCGImagePropertyCIFFContinuousDrive: CFString
@available(iOS 4.0, *)
let kCGImagePropertyCIFFFocusMode: CFString
@available(iOS 4.0, *)
let kCGImagePropertyCIFFMeteringMode: CFString
@available(iOS 4.0, *)
let kCGImagePropertyCIFFShootingMode: CFString
@available(iOS 4.0, *)
let kCGImagePropertyCIFFLensModel: CFString
@available(iOS 4.0, *)
let kCGImagePropertyCIFFLensMaxMM: CFString
@available(iOS 4.0, *)
let kCGImagePropertyCIFFLensMinMM: CFString
@available(iOS 4.0, *)
let kCGImagePropertyCIFFWhiteBalanceIndex: CFString
@available(iOS 4.0, *)
let kCGImagePropertyCIFFFlashExposureComp: CFString
@available(iOS 4.0, *)
let kCGImagePropertyCIFFMeasuredEV: CFString
@available(iOS 4.0, *)
let kCGImagePropertyMakerNikonISOSetting: CFString
@available(iOS 4.0, *)
let kCGImagePropertyMakerNikonColorMode: CFString
@available(iOS 4.0, *)
let kCGImagePropertyMakerNikonQuality: CFString
@available(iOS 4.0, *)
let kCGImagePropertyMakerNikonWhiteBalanceMode: CFString
@available(iOS 4.0, *)
let kCGImagePropertyMakerNikonSharpenMode: CFString
@available(iOS 4.0, *)
let kCGImagePropertyMakerNikonFocusMode: CFString
@available(iOS 4.0, *)
let kCGImagePropertyMakerNikonFlashSetting: CFString
@available(iOS 4.0, *)
let kCGImagePropertyMakerNikonISOSelection: CFString
@available(iOS 4.0, *)
let kCGImagePropertyMakerNikonFlashExposureComp: CFString
@available(iOS 4.0, *)
let kCGImagePropertyMakerNikonImageAdjustment: CFString
@available(iOS 4.0, *)
let kCGImagePropertyMakerNikonLensAdapter: CFString
@available(iOS 4.0, *)
let kCGImagePropertyMakerNikonLensType: CFString
@available(iOS 4.0, *)
let kCGImagePropertyMakerNikonLensInfo: CFString
@available(iOS 4.0, *)
let kCGImagePropertyMakerNikonFocusDistance: CFString
@available(iOS 4.0, *)
let kCGImagePropertyMakerNikonDigitalZoom: CFString
@available(iOS 4.0, *)
let kCGImagePropertyMakerNikonShootingMode: CFString
@available(iOS 4.0, *)
let kCGImagePropertyMakerNikonCameraSerialNumber: CFString
@available(iOS 4.0, *)
let kCGImagePropertyMakerNikonShutterCount: CFString
@available(iOS 4.0, *)
let kCGImagePropertyMakerCanonOwnerName: CFString
@available(iOS 4.0, *)
let kCGImagePropertyMakerCanonCameraSerialNumber: CFString
@available(iOS 4.0, *)
let kCGImagePropertyMakerCanonImageSerialNumber: CFString
@available(iOS 4.0, *)
let kCGImagePropertyMakerCanonFlashExposureComp: CFString
@available(iOS 4.0, *)
let kCGImagePropertyMakerCanonContinuousDrive: CFString
@available(iOS 4.0, *)
let kCGImagePropertyMakerCanonLensModel: CFString
@available(iOS 4.0, *)
let kCGImagePropertyMakerCanonFirmware: CFString
@available(iOS 4.0, *)
let kCGImagePropertyMakerCanonAspectRatioInfo: CFString
@available(iOS 11.3, *)
let kCGImagePropertyOpenEXRAspectRatio: CFString
@frozen enum CGImagePropertyOrientation : UInt32 {
  init?(rawValue: UInt32)
  var rawValue: UInt32 { get }
  case up
  case upMirrored
  case down
  case downMirrored
  case leftMirrored
  case right
  case rightMirrored
  case left
}
@available(iOS 9.0, *)
let kCGImagePropertyPNGCompressionFilter: CFString
var IMAGEIO_PNG_NO_FILTERS: Int32 { get }
var IMAGEIO_PNG_FILTER_NONE: Int32 { get }
var IMAGEIO_PNG_FILTER_SUB: Int32 { get }
var IMAGEIO_PNG_FILTER_UP: Int32 { get }
var IMAGEIO_PNG_FILTER_AVG: Int32 { get }
var IMAGEIO_PNG_FILTER_PAETH: Int32 { get }
@available(iOS 11.0, *)
let kCGImageAuxiliaryDataTypeDepth: CFString
@available(iOS 11.0, *)
let kCGImageAuxiliaryDataTypeDisparity: CFString
@available(iOS 12.0, *)
let kCGImageAuxiliaryDataTypePortraitEffectsMatte: CFString
@available(iOS 13.0, *)
let kCGImageAuxiliaryDataTypeSemanticSegmentationSkinMatte: CFString
@available(iOS 13.0, *)
let kCGImageAuxiliaryDataTypeSemanticSegmentationHairMatte: CFString
@available(iOS 13.0, *)
let kCGImageAuxiliaryDataTypeSemanticSegmentationTeethMatte: CFString
@available(iOS 11.0, *)
let kCGImageAuxiliaryDataInfoData: CFString
@available(iOS 11.0, *)
let kCGImageAuxiliaryDataInfoDataDescription: CFString
@available(iOS 11.0, *)
let kCGImageAuxiliaryDataInfoMetadata: CFString
@available(iOS 11.0, *)
let kCGImagePropertyImageCount: CFString
@available(iOS 11.0, *)
let kCGImagePropertyWidth: CFString
@available(iOS 11.0, *)
let kCGImagePropertyHeight: CFString
@available(iOS 11.0, *)
let kCGImagePropertyBytesPerRow: CFString
@available(iOS 11.0, *)
let kCGImagePropertyNamedColorSpace: CFString
@available(iOS 11.0, *)
let kCGImagePropertyPixelFormat: CFString
@available(iOS 11.0, *)
let kCGImagePropertyImages: CFString
@available(iOS 11.0, *)
let kCGImagePropertyThumbnailImages: CFString
@available(iOS 11.0, *)
let kCGImagePropertyAuxiliaryData: CFString
@available(iOS 11.0, *)
let kCGImagePropertyAuxiliaryDataType: CFString
