
var kLAPolicyDeviceOwnerAuthenticationWithBiometrics: Int32 { get }
var kLAPolicyDeviceOwnerAuthentication: Int32 { get }
var kLAPolicyDeviceOwnerAuthenticationWithWatch: Int32 { get }
var kLAPolicyDeviceOwnerAuthenticationWithBiometricsOrWatch: Int32 { get }
var kLACredentialTypeApplicationPassword: Int32 { get }
var kLACredentialSmartCardPIN: Int32 { get }
var kLAErrorAuthenticationFailed: Int32 { get }
var kLAErrorUserCancel: Int32 { get }
var kLAErrorUserFallback: Int32 { get }
var kLAErrorSystemCancel: Int32 { get }
var kLAErrorPasscodeNotSet: Int32 { get }
var kLAErrorTouchIDNotAvailable: Int32 { get }
var kLAErrorTouchIDNotEnrolled: Int32 { get }
var kLAErrorTouchIDLockout: Int32 { get }
var kLAErrorAppCancel: Int32 { get }
var kLAErrorInvalidContext: Int32 { get }
var kLAErrorWatchNotAvailable: Int32 { get }
var kLAErrorNotInteractive: Int32 { get }
var kLAErrorBiometryNotAvailable: Int32 { get }
var kLAErrorBiometryNotEnrolled: Int32 { get }
var kLAErrorBiometryLockout: Int32 { get }
var kLAErrorDomain: String { get }
