
@available(macOS 10.6, *)
func CFNetworkCopySystemProxySettings() -> Unmanaged<CFDictionary>?
@available(macOS 10.5, *)
func CFNetworkCopyProxiesForURL(_ url: CFURL, _ proxySettings: CFDictionary) -> Unmanaged<CFArray>
typealias CFProxyAutoConfigurationResultCallback = @convention(c) (UnsafeMutableRawPointer, CFArray, CFError?) -> Void
@available(macOS 10.5, *)
func CFNetworkCopyProxiesForAutoConfigurationScript(_ proxyAutoConfigurationScript: CFString, _ targetURL: CFURL, _ error: UnsafeMutablePointer<Unmanaged<CFError>?>?) -> Unmanaged<CFArray>?
@available(macOS 10.5, *)
func CFNetworkExecuteProxyAutoConfigurationScript(_ proxyAutoConfigurationScript: CFString, _ targetURL: CFURL, _ cb: CFProxyAutoConfigurationResultCallback, _ clientContext: UnsafeMutablePointer<CFStreamClientContext>) -> Unmanaged<CFRunLoopSource>
@available(macOS 10.5, *)
func CFNetworkExecuteProxyAutoConfigurationURL(_ proxyAutoConfigURL: CFURL, _ targetURL: CFURL, _ cb: CFProxyAutoConfigurationResultCallback, _ clientContext: UnsafeMutablePointer<CFStreamClientContext>) -> Unmanaged<CFRunLoopSource>
@available(macOS 10.5, *)
let kCFProxyTypeKey: CFString
@available(macOS 10.5, *)
let kCFProxyHostNameKey: CFString
@available(macOS 10.5, *)
let kCFProxyPortNumberKey: CFString
@available(macOS 10.5, *)
let kCFProxyAutoConfigurationURLKey: CFString
@available(macOS 10.7, *)
let kCFProxyAutoConfigurationJavaScriptKey: CFString
@available(macOS 10.5, *)
let kCFProxyUsernameKey: CFString
@available(macOS 10.5, *)
let kCFProxyPasswordKey: CFString
@available(macOS 10.5, *)
let kCFProxyTypeNone: CFString
@available(macOS 10.5, *)
let kCFProxyTypeHTTP: CFString
@available(macOS 10.5, *)
let kCFProxyTypeHTTPS: CFString
@available(macOS 10.5, *)
let kCFProxyTypeSOCKS: CFString
@available(macOS 10.5, *)
let kCFProxyTypeFTP: CFString
@available(macOS 10.5, *)
let kCFProxyTypeAutoConfigurationURL: CFString
@available(macOS 10.7, *)
let kCFProxyTypeAutoConfigurationJavaScript: CFString
@available(macOS 10.5, *)
let kCFProxyAutoConfigurationHTTPResponseKey: CFString
@available(macOS 10.6, *)
let kCFNetworkProxiesExceptionsList: CFString
@available(macOS 10.6, *)
let kCFNetworkProxiesExcludeSimpleHostnames: CFString
@available(macOS 10.6, *)
let kCFNetworkProxiesFTPEnable: CFString
@available(macOS 10.6, *)
let kCFNetworkProxiesFTPPassive: CFString
@available(macOS 10.6, *)
let kCFNetworkProxiesFTPPort: CFString
@available(macOS 10.6, *)
let kCFNetworkProxiesFTPProxy: CFString
@available(macOS 10.6, *)
let kCFNetworkProxiesGopherEnable: CFString
@available(macOS 10.6, *)
let kCFNetworkProxiesGopherPort: CFString
@available(macOS 10.6, *)
let kCFNetworkProxiesGopherProxy: CFString
@available(macOS 10.6, *)
let kCFNetworkProxiesHTTPEnable: CFString
@available(macOS 10.6, *)
let kCFNetworkProxiesHTTPPort: CFString
@available(macOS 10.6, *)
let kCFNetworkProxiesHTTPProxy: CFString
@available(macOS 10.6, *)
let kCFNetworkProxiesHTTPSEnable: CFString
@available(macOS 10.6, *)
let kCFNetworkProxiesHTTPSPort: CFString
@available(macOS 10.6, *)
let kCFNetworkProxiesHTTPSProxy: CFString
@available(macOS 10.6, *)
let kCFNetworkProxiesRTSPEnable: CFString
@available(macOS 10.6, *)
let kCFNetworkProxiesRTSPPort: CFString
@available(macOS 10.6, *)
let kCFNetworkProxiesRTSPProxy: CFString
@available(macOS 10.6, *)
let kCFNetworkProxiesSOCKSEnable: CFString
@available(macOS 10.6, *)
let kCFNetworkProxiesSOCKSPort: CFString
@available(macOS 10.6, *)
let kCFNetworkProxiesSOCKSProxy: CFString
@available(macOS 10.6, *)
let kCFNetworkProxiesProxyAutoConfigEnable: CFString
@available(macOS 10.6, *)
let kCFNetworkProxiesProxyAutoConfigURLString: CFString
@available(macOS 10.7, *)
let kCFNetworkProxiesProxyAutoConfigJavaScript: CFString
@available(macOS 10.6, *)
let kCFNetworkProxiesProxyAutoDiscoveryEnable: CFString
