
@available(tvOS 11.0, *)
class VNTargetedImageRequest : VNImageBasedRequest {
  init(targetedCVPixelBuffer pixelBuffer: CVPixelBuffer, options: [VNImageOption : Any] = [:])
  init(targetedCVPixelBuffer pixelBuffer: CVPixelBuffer, options: [VNImageOption : Any] = [:], completionHandler: VNRequestCompletionHandler? = nil)
  init(targetedCVPixelBuffer pixelBuffer: CVPixelBuffer, orientation: CGImagePropertyOrientation, options: [VNImageOption : Any] = [:])
  init(targetedCVPixelBuffer pixelBuffer: CVPixelBuffer, orientation: CGImagePropertyOrientation, options: [VNImageOption : Any] = [:], completionHandler: VNRequestCompletionHandler? = nil)
  init(targetedCGImage cgImage: CGImage, options: [VNImageOption : Any] = [:])
  init(targetedCGImage cgImage: CGImage, options: [VNImageOption : Any] = [:], completionHandler: VNRequestCompletionHandler? = nil)
  init(targetedCGImage cgImage: CGImage, orientation: CGImagePropertyOrientation, options: [VNImageOption : Any] = [:])
  init(targetedCGImage cgImage: CGImage, orientation: CGImagePropertyOrientation, options: [VNImageOption : Any] = [:], completionHandler: VNRequestCompletionHandler? = nil)
  init(targetedImageURL imageURL: URL, options: [VNImageOption : Any] = [:])
  init(targetedImageURL imageURL: URL, options: [VNImageOption : Any] = [:], completionHandler: VNRequestCompletionHandler? = nil)
  init(targetedImageURL imageURL: URL, orientation: CGImagePropertyOrientation, options: [VNImageOption : Any] = [:])
  init(targetedImageURL imageURL: URL, orientation: CGImagePropertyOrientation, options: [VNImageOption : Any] = [:], completionHandler: VNRequestCompletionHandler? = nil)
  init(targetedImageData imageData: Data, options: [VNImageOption : Any] = [:])
  init(targetedImageData imageData: Data, options: [VNImageOption : Any] = [:], completionHandler: VNRequestCompletionHandler? = nil)
  init(targetedImageData imageData: Data, orientation: CGImagePropertyOrientation, options: [VNImageOption : Any] = [:])
  init(targetedImageData imageData: Data, orientation: CGImagePropertyOrientation, options: [VNImageOption : Any] = [:], completionHandler: VNRequestCompletionHandler? = nil)
  @available(tvOS 14.0, *)
  init(targetedCMSampleBuffer sampleBuffer: CMSampleBuffer, options: [VNImageOption : Any] = [:])
  @available(tvOS 14.0, *)
  init(targetedCMSampleBuffer sampleBuffer: CMSampleBuffer, options: [VNImageOption : Any] = [:], completionHandler: VNRequestCompletionHandler? = nil)
  @available(tvOS 14.0, *)
  init(targetedCMSampleBuffer sampleBuffer: CMSampleBuffer, orientation: CGImagePropertyOrientation, options: [VNImageOption : Any] = [:])
  @available(tvOS 14.0, *)
  init(targetedCMSampleBuffer sampleBuffer: CMSampleBuffer, orientation: CGImagePropertyOrientation, options: [VNImageOption : Any] = [:], completionHandler: VNRequestCompletionHandler? = nil)
}
