
extension CSSearchableItemAttributeSet {
  var headline: String?
  var instructions: String?
  var thoroughfare: String?
  var subThoroughfare: String?
  var postalCode: String?
  var city: String?
  var stateOrProvince: String?
  var country: String?
  var fullyFormattedAddress: String?
  var altitude: NSNumber?
  var latitude: NSNumber?
  var longitude: NSNumber?
  var speed: NSNumber?
  var timestamp: Date?
  var imageDirection: NSNumber?
  var namedLocation: String?
  var gpsTrack: NSNumber?
  var gpsStatus: String?
  var gpsMeasureMode: String?
  var gpsdop: NSNumber?
  var gpsMapDatum: String?
  var gpsDestLatitude: NSNumber?
  var gpsDestLongitude: NSNumber?
  var gpsDestBearing: NSNumber?
  var gpsDestDistance: NSNumber?
  var gpsProcessingMethod: String?
  var gpsAreaInformation: String?
  var gpsDateStamp: Date?
  var gpsDifferental: NSNumber?
}
