
var COREMEDIA_TRUE: Bool { get }
var COREMEDIA_FALSE: Bool { get }
typealias CMItemCount = CFIndex
typealias CMItemIndex = CFIndex
var CMITEMCOUNT_MAX: Int { get }
var COREMEDIA_USE_ALIGNED_CMBASECLASS_VERSION: Bool { get }
typealias CMBaseClassVersion = UInt32
typealias CMStructVersion = UInt32
var COREMEDIA_CMBASECLASS_VERSION_IS_POINTER_ALIGNED: Bool { get }
var COREMEDIA_USE_DERIVED_ENUMS_FOR_CONSTANTS: Bool { get }
var COREMEDIA_DECLARE_NULLABILITY: Bool { get }
var COREMEDIA_DECLARE_NULLABILITY_BEGIN_END: Bool { get }
var COREMEDIA_DECLARE_BRIDGED_TYPES: Bool { get }
var COREMEDIA_DECLARE_RETURNS_RETAINED: Bool { get }
var COREMEDIA_DECLARE_RETURNS_RETAINED_ON_PARAMETERS: Bool { get }
var COREMEDIA_DECLARE_RETURNS_NOT_RETAINED_ON_PARAMETERS: Bool { get }
var COREMEDIA_DECLARE_RETURNS_RETAINED_BLOCK: Bool { get }
var COREMEDIA_DECLARE_RELEASES_ARGUMENT: Bool { get }
typealias CMPersistentTrackID = Int32
var kCMPersistentTrackID_Invalid: CMPersistentTrackID { get }
