
extension NSObject {
  class func webPlugInInitialize()
  func webPlugInInitialize()
  class func webPlugInStart()
  func webPlugInStart()
  class func webPlugInStop()
  func webPlugInStop()
  class func webPlugInDestroy()
  func webPlugInDestroy()
  class func webPlugInSetIsSelected(_ isSelected: Bool)
  func webPlugInSetIsSelected(_ isSelected: Bool)
  var objectForWebScript: Any! { get }
  @available(macOS 10.6, *)
  class func webPlugInMainResourceDidReceive(_ response: URLResponse!)
  @available(macOS 10.6, *)
  func webPlugInMainResourceDidReceive(_ response: URLResponse!)
  @available(macOS 10.6, *)
  class func webPlugInMainResourceDidReceive(_ data: Data!)
  @available(macOS 10.6, *)
  func webPlugInMainResourceDidReceive(_ data: Data!)
  @available(macOS 10.6, *)
  class func webPlugInMainResourceDidFailWithError(_ error: Error!)
  @available(macOS 10.6, *)
  func webPlugInMainResourceDidFailWithError(_ error: Error!)
  @available(macOS 10.6, *)
  class func webPlugInMainResourceDidFinishLoading()
  @available(macOS 10.6, *)
  func webPlugInMainResourceDidFinishLoading()
  class func objectForWebScript() -> Any!
}
