
@available(watchOS, introduced: 3.2, deprecated: 6.0, message: "INStartAudioCallIntentIdentifier is deprecated. Please adopt INStartCallIntentIdentifier instead")
let INStartAudioCallIntentIdentifier: String
@available(watchOS, introduced: 3.2, deprecated: 6.0, message: "INStartVideoCallIntentIdentifier is deprecated. Please adopt INStartCallIntentIdentifier instead")
let INStartVideoCallIntentIdentifier: String
@available(watchOS 3.2, *)
let INSearchCallHistoryIntentIdentifier: String
@available(watchOS 6.0, *)
let INStartCallIntentIdentifier: String
@available(watchOS 3.0, *)
let INSetAudioSourceInCarIntentIdentifier: String
@available(watchOS 3.0, *)
let INSetClimateSettingsInCarIntentIdentifier: String
@available(watchOS 3.0, *)
let INSetDefrosterSettingsInCarIntentIdentifier: String
@available(watchOS 3.0, *)
let INSetSeatSettingsInCarIntentIdentifier: String
@available(watchOS 3.0, *)
let INSetProfileInCarIntentIdentifier: String
@available(watchOS 3.0, *)
let INSaveProfileInCarIntentIdentifier: String
@available(watchOS 3.2, *)
let INStartWorkoutIntentIdentifier: String
@available(watchOS 3.2, *)
let INPauseWorkoutIntentIdentifier: String
@available(watchOS 3.2, *)
let INEndWorkoutIntentIdentifier: String
@available(watchOS 3.2, *)
let INCancelWorkoutIntentIdentifier: String
@available(watchOS 3.2, *)
let INResumeWorkoutIntentIdentifier: String
@available(watchOS 3.0, *)
let INSetRadioStationIntentIdentifier: String
@available(watchOS 3.2, *)
let INSendMessageIntentIdentifier: String
@available(watchOS 3.2, *)
let INSearchForMessagesIntentIdentifier: String
@available(watchOS 3.0, *)
let INSetMessageAttributeIntentIdentifier: String
@available(watchOS 3.2, *)
let INSendPaymentIntentIdentifier: String
@available(watchOS 3.2, *)
let INRequestPaymentIntentIdentifier: String
@available(watchOS 3.2, *)
let INSearchForPhotosIntentIdentifier: String
@available(watchOS 3.2, *)
let INStartPhotoPlaybackIntentIdentifier: String
@available(watchOS 3.2, *)
let INListRideOptionsIntentIdentifier: String
@available(watchOS 3.2, *)
let INRequestRideIntentIdentifier: String
@available(watchOS 3.2, *)
let INGetRideStatusIntentIdentifier: String
