
var STOP_CODE: Int32 { get }
var POP_TOP: Int32 { get }
var ROT_TWO: Int32 { get }
var ROT_THREE: Int32 { get }
var DUP_TOP: Int32 { get }
var ROT_FOUR: Int32 { get }
var NOP: Int32 { get }
var UNARY_POSITIVE: Int32 { get }
var UNARY_NEGATIVE: Int32 { get }
var UNARY_NOT: Int32 { get }
var UNARY_CONVERT: Int32 { get }
var UNARY_INVERT: Int32 { get }
var BINARY_POWER: Int32 { get }
var BINARY_MULTIPLY: Int32 { get }
var BINARY_DIVIDE: Int32 { get }
var BINARY_MODULO: Int32 { get }
var BINARY_ADD: Int32 { get }
var BINARY_SUBTRACT: Int32 { get }
var BINARY_SUBSCR: Int32 { get }
var BINARY_FLOOR_DIVIDE: Int32 { get }
var BINARY_TRUE_DIVIDE: Int32 { get }
var INPLACE_FLOOR_DIVIDE: Int32 { get }
var INPLACE_TRUE_DIVIDE: Int32 { get }
var SLICE: Int32 { get }
var SLICE_1: Int32 { get }
var SLICE_2: Int32 { get }
var SLICE_3: Int32 { get }
var STORE_SLICE: Int32 { get }
var STORE_SLICE_1: Int32 { get }
var STORE_SLICE_2: Int32 { get }
var STORE_SLICE_3: Int32 { get }
var DELETE_SLICE: Int32 { get }
var DELETE_SLICE_1: Int32 { get }
var DELETE_SLICE_2: Int32 { get }
var DELETE_SLICE_3: Int32 { get }
var STORE_MAP: Int32 { get }
var INPLACE_ADD: Int32 { get }
var INPLACE_SUBTRACT: Int32 { get }
var INPLACE_MULTIPLY: Int32 { get }
var INPLACE_DIVIDE: Int32 { get }
var INPLACE_MODULO: Int32 { get }
var STORE_SUBSCR: Int32 { get }
var DELETE_SUBSCR: Int32 { get }
var BINARY_LSHIFT: Int32 { get }
var BINARY_RSHIFT: Int32 { get }
var BINARY_AND: Int32 { get }
var BINARY_XOR: Int32 { get }
var BINARY_OR: Int32 { get }
var INPLACE_POWER: Int32 { get }
var GET_ITER: Int32 { get }
var PRINT_EXPR: Int32 { get }
var PRINT_ITEM: Int32 { get }
var PRINT_NEWLINE: Int32 { get }
var PRINT_ITEM_TO: Int32 { get }
var PRINT_NEWLINE_TO: Int32 { get }
var INPLACE_LSHIFT: Int32 { get }
var INPLACE_RSHIFT: Int32 { get }
var INPLACE_AND: Int32 { get }
var INPLACE_XOR: Int32 { get }
var INPLACE_OR: Int32 { get }
var BREAK_LOOP: Int32 { get }
var WITH_CLEANUP: Int32 { get }
var LOAD_LOCALS: Int32 { get }
var RETURN_VALUE: Int32 { get }
var IMPORT_STAR: Int32 { get }
var EXEC_STMT: Int32 { get }
var YIELD_VALUE: Int32 { get }
var POP_BLOCK: Int32 { get }
var END_FINALLY: Int32 { get }
var BUILD_CLASS: Int32 { get }
var HAVE_ARGUMENT: Int32 { get }
var STORE_NAME: Int32 { get }
var DELETE_NAME: Int32 { get }
var UNPACK_SEQUENCE: Int32 { get }
var FOR_ITER: Int32 { get }
var LIST_APPEND: Int32 { get }
var STORE_ATTR: Int32 { get }
var DELETE_ATTR: Int32 { get }
var STORE_GLOBAL: Int32 { get }
var DELETE_GLOBAL: Int32 { get }
var DUP_TOPX: Int32 { get }
var LOAD_CONST: Int32 { get }
var LOAD_NAME: Int32 { get }
var BUILD_TUPLE: Int32 { get }
var BUILD_LIST: Int32 { get }
var BUILD_SET: Int32 { get }
var BUILD_MAP: Int32 { get }
var LOAD_ATTR: Int32 { get }
var COMPARE_OP: Int32 { get }
var IMPORT_NAME: Int32 { get }
var IMPORT_FROM: Int32 { get }
var JUMP_FORWARD: Int32 { get }
var JUMP_IF_FALSE_OR_POP: Int32 { get }
var JUMP_IF_TRUE_OR_POP: Int32 { get }
var JUMP_ABSOLUTE: Int32 { get }
var POP_JUMP_IF_FALSE: Int32 { get }
var POP_JUMP_IF_TRUE: Int32 { get }
var LOAD_GLOBAL: Int32 { get }
var CONTINUE_LOOP: Int32 { get }
var SETUP_LOOP: Int32 { get }
var SETUP_EXCEPT: Int32 { get }
var SETUP_FINALLY: Int32 { get }
var LOAD_FAST: Int32 { get }
var STORE_FAST: Int32 { get }
var DELETE_FAST: Int32 { get }
var RAISE_VARARGS: Int32 { get }
var CALL_FUNCTION: Int32 { get }
var MAKE_FUNCTION: Int32 { get }
var BUILD_SLICE: Int32 { get }
var MAKE_CLOSURE: Int32 { get }
var LOAD_CLOSURE: Int32 { get }
var LOAD_DEREF: Int32 { get }
var STORE_DEREF: Int32 { get }
var CALL_FUNCTION_VAR: Int32 { get }
var CALL_FUNCTION_KW: Int32 { get }
var CALL_FUNCTION_VAR_KW: Int32 { get }
var SETUP_WITH: Int32 { get }
var EXTENDED_ARG: Int32 { get }
var SET_ADD: Int32 { get }
var MAP_ADD: Int32 { get }
struct cmp_op : Equatable, RawRepresentable {
  init(_ rawValue: UInt32)
  init(rawValue: UInt32)
  var rawValue: UInt32
}
var PyCmp_LT: cmp_op { get }
var PyCmp_LE: cmp_op { get }
var PyCmp_EQ: cmp_op { get }
var PyCmp_NE: cmp_op { get }
var PyCmp_GT: cmp_op { get }
var PyCmp_GE: cmp_op { get }
var PyCmp_IN: cmp_op { get }
var PyCmp_NOT_IN: cmp_op { get }
var PyCmp_IS: cmp_op { get }
var PyCmp_IS_NOT: cmp_op { get }
var PyCmp_EXC_MATCH: cmp_op { get }
var PyCmp_BAD: cmp_op { get }
