
@available(macOS 10.2, *)
let kDRISOLevel: CFString!
@available(macOS 10.2, *)
let kDRVolumeSet: CFString!
@available(macOS 10.2, *)
let kDRPublisher: CFString!
@available(macOS 10.2, *)
let kDRDataPreparer: CFString!
@available(macOS 10.2, *)
let kDRSystemIdentifier: CFString!
@available(macOS 10.2, *)
let kDRApplicationIdentifier: CFString!
@available(macOS 10.2, *)
let kDRCopyrightFile: CFString!
@available(macOS 10.2, *)
let kDRAbstractFile: CFString!
@available(macOS 10.2, *)
let kDRBibliographicFile: CFString!
@available(macOS 10.2, *)
let kDRBlockSize: CFString!
@available(macOS 10.2, *)
let kDRDefaultDate: CFString!
@available(macOS 10.2, *)
let kDRVolumeCreationDate: CFString!
@available(macOS 10.2, *)
let kDRVolumeModificationDate: CFString!
@available(macOS 10.2, *)
let kDRVolumeCheckedDate: CFString!
@available(macOS 10.2, *)
let kDRVolumeExpirationDate: CFString!
@available(macOS 10.2, *)
let kDRVolumeEffectiveDate: CFString!
@available(macOS 10.2, *)
let kDRISOMacExtensions: CFString!
@available(macOS 10.2, *)
let kDRISORockRidgeExtensions: CFString!
@available(macOS 10.3, *)
let kDRSuppressMacSpecificFiles: CFString!
@available(macOS 10.2, *)
let kDRAllFilesystems: CFString!
@available(macOS 10.2, *)
let kDRISO9660: CFString!
@available(macOS 10.2, *)
let kDRISO9660LevelOne: CFString!
@available(macOS 10.2, *)
let kDRISO9660LevelTwo: CFString!
@available(macOS 10.2, *)
let kDRJoliet: CFString!
@available(macOS 10.2, *)
let kDRHFSPlus: CFString!
@available(macOS 10.4, *)
let kDRUDF: CFString!
@available(macOS 10.2, *)
let kDRISO9660VersionNumber: CFString!
@available(macOS 10.2, *)
let kDRInvisible: CFString!
@available(macOS 10.2, *)
let kDRCreationDate: CFString!
@available(macOS 10.2, *)
let kDRContentModificationDate: CFString!
@available(macOS 10.2, *)
let kDRAttributeModificationDate: CFString!
@available(macOS 10.2, *)
let kDRAccessDate: CFString!
@available(macOS 10.2, *)
let kDRBackupDate: CFString!
@available(macOS 10.2, *)
let kDRRecordingDate: CFString!
@available(macOS 10.2, *)
let kDREffectiveDate: CFString!
@available(macOS 10.2, *)
let kDRExpirationDate: CFString!
@available(macOS 10.2, *)
let kDRPosixFileMode: CFString!
@available(macOS 10.2, *)
let kDRPosixUID: CFString!
@available(macOS 10.2, *)
let kDRPosixGID: CFString!
@available(macOS 10.2, *)
let kDRHFSPlusTextEncodingHint: CFString!
@available(macOS 10.2, *)
let kDRHFSPlusCatalogNodeID: CFString!
@available(macOS 10.2, *)
let kDRMacFileType: CFString!
@available(macOS 10.2, *)
let kDRMacFileCreator: CFString!
@available(macOS 10.2, *)
let kDRMacWindowBounds: CFString!
@available(macOS 10.2, *)
let kDRMacIconLocation: CFString!
@available(macOS 10.2, *)
let kDRMacScrollPosition: CFString!
@available(macOS 10.2, *)
let kDRMacWindowView: CFString!
@available(macOS 10.2, *)
let kDRMacFinderFlags: CFString!
@available(macOS 10.2, *)
let kDRMacExtendedFinderFlags: CFString!
@available(macOS 10.5, *)
let kDRMacFinderHideExtension: CFString!
@available(macOS 10.4, *)
let kDRUDFWriteVersion: CFString!
@available(macOS 10.4, *)
let kDRUDFVersion102: CFString!
@available(macOS 10.4, *)
let kDRUDFVersion150: CFString!
@available(macOS 10.4, *)
let kDRUDFPrimaryVolumeDescriptorNumber: CFString!
@available(macOS 10.4, *)
let kDRUDFVolumeSequenceNumber: CFString!
@available(macOS 10.4, *)
let kDRUDFMaxVolumeSequenceNumber: CFString!
@available(macOS 10.4, *)
let kDRUDFInterchangeLevel: CFString!
@available(macOS 10.4, *)
let kDRUDFMaxInterchangeLevel: CFString!
@available(macOS 10.4, *)
let kDRUDFApplicationIdentifierSuffix: CFString!
@available(macOS 10.4, *)
let kDRUDFVolumeSetIdentifier: CFString!
@available(macOS 10.4, *)
let kDRUDFVolumeSetTimestamp: CFString!
@available(macOS 10.4, *)
let kDRUDFVolumeSetImplementationUse: CFString!
@available(macOS 10.4, *)
let kDRUDFRealTimeFile: CFString!
@available(macOS 10.4, *)
let kDRUDFExtendedFilePermissions: CFString!
