
@available(macOS 10.11, *)
struct MTLBlitOption : OptionSet {
  init(rawValue: UInt)
  let rawValue: UInt
  static var depthFromDepthStencil: MTLBlitOption { get }
  static var stencilFromDepthStencil: MTLBlitOption { get }
  @available(macOS 11.0, *)
  static var rowLinearPVRTC: MTLBlitOption { get }
}
@available(macOS 10.11, *)
protocol MTLBlitCommandEncoder : MTLCommandEncoder {
  @available(macOS 10.11, *)
  func synchronize(resource: MTLResource)
  @available(macOS 10.11, *)
  func synchronize(texture: MTLTexture, slice: Int, level: Int)
  func copy(from sourceTexture: MTLTexture, sourceSlice: Int, sourceLevel: Int, sourceOrigin: MTLOrigin, sourceSize: MTLSize, to destinationTexture: MTLTexture, destinationSlice: Int, destinationLevel: Int, destinationOrigin: MTLOrigin)
  func copy(from sourceBuffer: MTLBuffer, sourceOffset: Int, sourceBytesPerRow: Int, sourceBytesPerImage: Int, sourceSize: MTLSize, to destinationTexture: MTLTexture, destinationSlice: Int, destinationLevel: Int, destinationOrigin: MTLOrigin)
  @available(macOS 10.11, *)
  func copy(from sourceBuffer: MTLBuffer, sourceOffset: Int, sourceBytesPerRow: Int, sourceBytesPerImage: Int, sourceSize: MTLSize, to destinationTexture: MTLTexture, destinationSlice: Int, destinationLevel: Int, destinationOrigin: MTLOrigin, options: MTLBlitOption)
  func copy(from sourceTexture: MTLTexture, sourceSlice: Int, sourceLevel: Int, sourceOrigin: MTLOrigin, sourceSize: MTLSize, to destinationBuffer: MTLBuffer, destinationOffset: Int, destinationBytesPerRow: Int, destinationBytesPerImage: Int)
  @available(macOS 10.11, *)
  func copy(from sourceTexture: MTLTexture, sourceSlice: Int, sourceLevel: Int, sourceOrigin: MTLOrigin, sourceSize: MTLSize, to destinationBuffer: MTLBuffer, destinationOffset: Int, destinationBytesPerRow: Int, destinationBytesPerImage: Int, options: MTLBlitOption)
  func generateMipmaps(for texture: MTLTexture)
  func __fill(_ buffer: MTLBuffer, range: NSRange, value: UInt8)
  @available(macOS 10.15, *)
  func copy(from sourceTexture: MTLTexture, sourceSlice: Int, sourceLevel: Int, to destinationTexture: MTLTexture, destinationSlice: Int, destinationLevel: Int, sliceCount: Int, levelCount: Int)
  @available(macOS 10.15, *)
  func copy(from sourceTexture: MTLTexture, to destinationTexture: MTLTexture)
  func copy(from sourceBuffer: MTLBuffer, sourceOffset: Int, to destinationBuffer: MTLBuffer, destinationOffset: Int, size: Int)
  @available(macOS 10.13, *)
  func updateFence(_ fence: MTLFence)
  @available(macOS 10.13, *)
  func waitForFence(_ fence: MTLFence)
  @available(macOS 11.0, *)
  optional func getTextureAccessCounters(_ texture: MTLTexture, region: MTLRegion, mipLevel: Int, slice: Int, resetCounters: Bool, countersBuffer: MTLBuffer, countersBufferOffset: Int)
  @available(macOS 11.0, *)
  optional func resetTextureAccessCounters(_ texture: MTLTexture, region: MTLRegion, mipLevel: Int, slice: Int)
  @available(macOS 10.14, *)
  func optimizeContentsForGPUAccess(texture: MTLTexture)
  @available(macOS 10.14, *)
  func optimizeContentsForGPUAccess(texture: MTLTexture, slice: Int, level: Int)
  @available(macOS 10.14, *)
  func optimizeContentsForCPUAccess(texture: MTLTexture)
  @available(macOS 10.14, *)
  func optimizeContentsForCPUAccess(texture: MTLTexture, slice: Int, level: Int)
  @available(macOS 10.14, *)
  func __resetCommands(in buffer: MTLIndirectCommandBuffer, with range: NSRange)
  @available(macOS 10.14, *)
  func __copy(_ source: MTLIndirectCommandBuffer, sourceRange: NSRange, destination: MTLIndirectCommandBuffer, destinationIndex: Int)
  @available(macOS 10.14, *)
  func __optimizeIndirectCommandBuffer(_ indirectCommandBuffer: MTLIndirectCommandBuffer, with range: NSRange)
  @available(macOS 10.15, *)
  func sampleCounters(sampleBuffer: MTLCounterSampleBuffer, sampleIndex: Int, barrier: Bool)
  @available(macOS 10.15, *)
  func __resolveCounters(_ sampleBuffer: MTLCounterSampleBuffer, in range: NSRange, destinationBuffer: MTLBuffer, destinationOffset: Int)
}

@available(macOS 10.11, iOS 8.0, tvOS 8.0, *)
extension MTLBlitCommandEncoder {
  func fill(buffer: MTLBuffer, range: Range<Int>, value: UInt8)
  @available(macOS 10.14, iOS 12.0, tvOS 12.0, *)
  func resetCommandsInBuffer(_ buffer: MTLIndirectCommandBuffer, range: Range<Int>)
  @available(macOS 10.14, iOS 12.0, tvOS 12.0, *)
  func copyIndirectCommandBuffer(_ buffer: MTLIndirectCommandBuffer, sourceRange: Range<Int>, destination: MTLIndirectCommandBuffer, destinationIndex: Int)
  @available(macOS 10.14, iOS 12.0, tvOS 12.0, *)
  func optimizeIndirectCommandBuffer(_ buffer: MTLIndirectCommandBuffer, range: Range<Int>)
  @available(macOS 11.0, iOS 14.0, tvOS 14.0, *)
  func resolveCounters(_ sampleBuffer: MTLCounterSampleBuffer, range: Range<Int>, destinationBuffer: MTLBuffer, destinationOffset: Int)
}
