
struct MTLDispatchThreadgroupsIndirectArguments {
  var threadgroupsPerGrid: (UInt32, UInt32, UInt32)
  init()
  init(threadgroupsPerGrid: (UInt32, UInt32, UInt32))
}
@available(macOS 10.14, *)
struct MTLStageInRegionIndirectArguments {
  var stageInOrigin: (UInt32, UInt32, UInt32)
  var stageInSize: (UInt32, UInt32, UInt32)
  init()
  init(stageInOrigin: (UInt32, UInt32, UInt32), stageInSize: (UInt32, UInt32, UInt32))
}
@available(macOS 10.11, *)
protocol MTLComputeCommandEncoder : MTLCommandEncoder {
  @available(macOS 10.14, *)
  var dispatchType: MTLDispatchType { get }
  func setComputePipelineState(_ state: MTLComputePipelineState)
  @available(macOS 10.11, *)
  func setBytes(_ bytes: UnsafeRawPointer, length: Int, index: Int)
  func setBuffer(_ buffer: MTLBuffer?, offset: Int, index: Int)
  @available(macOS 10.11, *)
  func setBufferOffset(_ offset: Int, index: Int)
  func __setBuffers(_ buffers: UnsafePointer<MTLBuffer?>, offsets: UnsafePointer<Int>, with range: NSRange)
  @available(macOS 11.0, *)
  func setVisibleFunctionTable(_ visibleFunctionTable: MTLVisibleFunctionTable?, bufferIndex: Int)
  @available(macOS 11.0, *)
  func __setVisibleFunctionTables(_ visibleFunctionTables: UnsafePointer<MTLVisibleFunctionTable?>, withBufferRange range: NSRange)
  @available(macOS 11.0, *)
  func setIntersectionFunctionTable(_ intersectionFunctionTable: MTLIntersectionFunctionTable?, bufferIndex: Int)
  @available(macOS 11.0, *)
  func __setIntersectionFunctionTables(_ intersectionFunctionTables: UnsafePointer<MTLIntersectionFunctionTable?>, withBufferRange range: NSRange)
  @available(macOS 11.0, *)
  func setAccelerationStructure(_ accelerationStructure: MTLAccelerationStructure?, bufferIndex: Int)
  func setTexture(_ texture: MTLTexture?, index: Int)
  func __setTextures(_ textures: UnsafePointer<MTLTexture?>, with range: NSRange)
  func setSamplerState(_ sampler: MTLSamplerState?, index: Int)
  func __setSamplerStates(_ samplers: UnsafePointer<MTLSamplerState?>, with range: NSRange)
  func setSamplerState(_ sampler: MTLSamplerState?, lodMinClamp: Float, lodMaxClamp: Float, index: Int)
  func __setSamplerStates(_ samplers: UnsafePointer<MTLSamplerState?>, lodMinClamps: UnsafePointer<Float>, lodMaxClamps: UnsafePointer<Float>, with range: NSRange)
  func setThreadgroupMemoryLength(_ length: Int, index: Int)
  @available(macOS 11.0, *)
  func setImageblockWidth(_ width: Int, height: Int)
  @available(macOS 10.12, *)
  func setStageInRegion(_ region: MTLRegion)
  @available(macOS 10.14, *)
  func setStageInRegionWithIndirectBuffer(_ indirectBuffer: MTLBuffer, indirectBufferOffset: Int)
  func dispatchThreadgroups(_ threadgroupsPerGrid: MTLSize, threadsPerThreadgroup: MTLSize)
  @available(macOS 10.11, *)
  func dispatchThreadgroups(indirectBuffer: MTLBuffer, indirectBufferOffset: Int, threadsPerThreadgroup: MTLSize)
  @available(macOS 10.13, *)
  func dispatchThreads(_ threadsPerGrid: MTLSize, threadsPerThreadgroup: MTLSize)
  @available(macOS 10.13, *)
  func updateFence(_ fence: MTLFence)
  @available(macOS 10.13, *)
  func waitForFence(_ fence: MTLFence)
  @available(macOS 10.13, *)
  func useResource(_ resource: MTLResource, usage: MTLResourceUsage)
  @available(macOS 10.13, *)
  func __use(_ resources: UnsafePointer<MTLResource>, count: Int, usage: MTLResourceUsage)
  @available(macOS 10.13, *)
  func useHeap(_ heap: MTLHeap)
  @available(macOS 10.13, *)
  func __use(_ heaps: UnsafePointer<MTLHeap>, count: Int)
  @available(macOS 11.0, *)
  func __executeCommands(in indirectCommandBuffer: MTLIndirectCommandBuffer, with executionRange: NSRange)
  @available(macOS 11.0, *)
  func __executeCommands(in indirectCommandbuffer: MTLIndirectCommandBuffer, indirectBuffer indirectRangeBuffer: MTLBuffer, indirectBufferOffset: Int)
  @available(macOS 10.14, *)
  func memoryBarrier(scope: MTLBarrierScope)
  @available(macOS 10.14, *)
  func __memoryBarrier(resources: UnsafePointer<MTLResource>, count: Int)
  @available(macOS 10.15, *)
  func sampleCounters(sampleBuffer: MTLCounterSampleBuffer, sampleIndex: Int, barrier: Bool)
}

@available(macOS 10.11, iOS 8.0, tvOS 8.0, *)
extension MTLComputeCommandEncoder {
  @available(macOS 10.13, iOS 11.0, tvOS 11.0, *)
  func useResources(_ resources: [MTLResource], usage: MTLResourceUsage)
  @available(macOS 10.13, iOS 11.0, tvOS 11.0, *)
  func useHeaps(_ heaps: [MTLHeap])
  func setBuffers(_ buffers: [MTLBuffer?], offsets: [Int], range: Range<Int>)
  func setTextures(_ textures: [MTLTexture?], range: Range<Int>)
  func setSamplerStates(_ samplers: [MTLSamplerState?], range: Range<Int>)
  func setSamplerStates(_ samplers: [MTLSamplerState?], lodMinClamps: [Float], lodMaxClamps: [Float], range: Range<Int>)
  @available(macOS 10.14, iOS 12.0, tvOS 12.0, *)
  func memoryBarrier(resources: [MTLResource])
  @available(macOS 11.0, iOS 14.0, *)
  @available(tvOS, unavailable)
  func setVisibleFunctionTables(_ visibleFunctionTables: [MTLVisibleFunctionTable?], bufferRange: Range<Int>)
  @available(macOS 11.0, iOS 14.0, *)
  @available(tvOS, unavailable)
  func setIntersectionFunctionTables(_ intersectionFunctionTables: [MTLIntersectionFunctionTable?], bufferRange: Range<Int>)
}
